<div class="box">
    <div class="box-header">
        <h2>权限管理</h2>
    </div>
    <div class="box-content">
        <ul>
            <li>
                <a href="<?php echo $this->url('backend' , array('controller' => 'role' , 'action' => 'index'));?>">
            <i class="icon-add"></i>角色管理</a>
            </li>
            <li>
            <a href="<?php echo $this->url('backend' , array('controller' => 'resource' , 'action' => 'index'));?>">
            <i class="icon-add"></i>资源管理</a>
            
        </ul>
    </div>
</div>