            <h3 class="f14"><span class="switchs cu on" title="个人信息"></span>个人信息</h3>
            <ul>
                <li id="_MP1" class="sub_menu">
                	<a href="javascript:_MP('1','index.html');" hidefocus="true" style="outline:none;">个人信息修改</a></li>
                <li id="_MP2" class="sub_menu">
                	<a href="javascript:_MP('2','index.html');" hidefocus="true" style="outline:none;">密码修改</a></li>
            </ul>
			<script type="text/javascript">
            $(".switchs").each(function(i){
                var ul = $(this).parent().next();
                $(this).click(
                function(){
                    if(ul.is(':visible')){
                        ul.hide();
                        $(this).removeClass('on');
                            }else{
                        ul.show();
                        $(this).addClass('on');
                    }
                })
            });
            </script>
