<?php
$this->headScript()->appendFile($this->basePath('js/jquery-ui-1.10.2.custom.min.js'));
$this->headLink()->appendStylesheet('http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css');
$msg = $this->flashMessages();
$region = $this->region;
$regionList = $this->regionList;
?>
<div class="box">
    <div class="box-header">
<!--         <h2><i class="icon-box"></i>会员列表</h2> -->
        <div class="t_top">
        	<div class="t_inline">
        	<form class="form-inline" action="<?php echo $this->url('backend', array('controller' 
            => 'member', 'action' => 'all')); ?>" method="get">
                <div class="input-group" style="width:500px;">
                <?php if (isset($regionList['Province'])):?>
<!--                 	<label>区域</label> -->
                    <select name="Province" style="width:80px;">
                    	<option value="">省</option>
                    <?php foreach ($regionList['Province'] as $k=>$v):?>
                    	<option value="<?php echo $k;?>" <?php echo $this->Province==$k ? 'selected=selected' : '';?>><?php echo $v;?></option>
                    <?php endforeach;?>
                    </select>
                    <select name="City" style="width:80px;">
                    	<option value="">市</option>
                    <?php foreach ($regionList['City'] as $k=>$v):?>
                    	<option value="<?php echo $k;?>" <?php echo $this->City==$k ? 'selected=selected' : '';?>><?php echo $v;?></option>
                    <?php endforeach;?>
                    </select>
                    <select name="District" style="width:80px;">
                    	<option value="">区</option>
                    <?php foreach ($regionList['District'] as $k=>$v):?>
                    	<option value="<?php echo $k;?>" <?php echo $this->District==$k ? 'selected=selected' : '';?>><?php echo $v;?></option>
                    <?php endforeach;?>
                    </select>
                <?php endif;?>
                    <input autocomplete="off" style="width:80px" class="input-element span3" value="<?php echo isset($this->k) ? $this->k : '';?>" name="k" type="text">
                    
                <button class="button-element" type="submit">搜索</button>
                
                <button class="button-element" type='button' id="selector">筛选</button>
                </div>
        	</form>
        	</div>
        	<p class='t_right'><a class="btn btn-success" href="<?php echo $this->url('backend' 
            , array('controller' => 'member' , 'action' => 'allSave'))?>">
        <i class="icon-plus"></i>新增</a>
        					<a class="btn btn-edit" href="javascript:;" _href="<?php echo $this->url('backend', array('controller' 
                                => 'member', 'action' => 'allSave')) ?>?id=">
                                <i class="icon-edit"></i>编辑
                            </a>
                            <a class="btn btn-edit" href="javascript:;" _href="<?php echo $this->url('backend', array('controller' 
                                => 'member', 'action' => 'allPwd')) ?>?id=">
                                <i class="icon-edit"></i>设密
                            </a>
                            <a class="btn btn-edit" editMult="true" href="javascript:;" _href="<?php echo $this->url('backend', array('controller' 
                                => 'member', 'action' => 'allSendMail')) ?>?id=">
                                <i class="icon-edit"></i>邮件
                            </a>
                            <a class="btn btn-delete" href="javascript:;" _href="<?php echo $this->url('backend', array('controller' 
                                => 'member', 'action' => 'allDelete')) ?>?id=" onClick="diyConfirm('删除' , $(this).attr('href'), this);return false;"><i class="icon-delete"></i>删除
                            </a>
        </p>
     </div>
    </div>
    <div class="box-content">
    <?php if(!empty($msg['error'])):?>
            <div class="alert alert-error fade in">
            <button class="close" data-dismiss="alert" type="button">×</button>
            <?php foreach($msg['error'] as $v):?>
            <p><?php echo $v;?></p>
            <?php endforeach;?>
            </div>
            <?php endif;?>
            
            <?php if(!empty($msg['success'])):?>
            <div class="alert alert-success fade in">
            <button class="close" data-dismiss="alert" type="button">×</button>
            <?php foreach($msg['success'] as $v):?>
            <p><?php echo $v;?></p>
            <?php endforeach;?>
            </div>
            <?php endif;?>
        <table class="table" id="table1">
            <thead>
                <tr class="row">
	                <th>全选<input type="checkbox" name="select_all" value="all"/></th>
	                <th>编号</th>
                    <th key="UserName" editable="true">
                    <?php if (isset($this->order['UserName'])):?>
                    <?php $name = $this->order['UserName'];?>
                    <a href="<?php echo $name['href'];?>">用户名<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	用户名
                    <?php endif;?>
                    </th>
                    <th key="Email" editable="true">
                     <?php if (isset($this->order['Email'])):?>
                    <?php $name = $this->order['Email'];?>
                    <a href="<?php echo $name['href'];?>">邮箱<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	邮箱
                    <?php endif;?>
 					</th>
                    <th key="Mobile" editable="true">
       <?php if (isset($this->order['Mobile'])):?>
                    <?php $name = $this->order['Mobile'];?>
                    <a href="<?php echo $name['href'];?>"> 手机<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	 手机
                    <?php endif;?>             
                   </th>
                    <th key="Nick" editable="true">
       <?php if (isset($this->order['Nick'])):?>
                    <?php $name = $this->order['Nick'];?>
                    <a href="<?php echo $name['href'];?>">昵称<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	昵称
                    <?php endif;?>             
                    </th>
                    <th key="Points" editable="true">
                    <?php if (isset($this->order['Points'])):?>
                    <?php $name = $this->order['Points'];?>
                    <a href="<?php echo $name['href'];?>">积分<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	积分
                    <?php endif;?>
                    	</th>
                    	<th>电话</th>
                    	<th>真实姓名</th>
                    	<th>性别</th>
                    	<th>区域</th>
                    	<th>地址</th>
                    	<th>QQ</th>
                    	<th>MSN</th>
                    <th>
      <?php if (isset($this->order['LastLogin'])):?>
                    <?php $name = $this->order['LastLogin'];?>
                    <a href="<?php echo $name['href'];?>"> 最后登录时间<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	 最后登录时间
                    <?php endif;?>              
                   </th>
                    <th>
      <?php if (isset($this->order['LoginCount'])):?>
                    <?php $name = $this->order['LoginCount'];?>
                    <a href="<?php echo $name['href'];?>"> 登录次数<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	登录次数
                    <?php endif;?>              
                    </th>
                    <th>
      <?php if (isset($this->order['LastUpdate'])):?>
                    <?php $name = $this->order['LastUpdate'];?>
                    <a href="<?php echo $name['href'];?>"> 最后修改时间<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	最后修改时间
                    <?php endif;?>              
                    </th>
                </tr>
            </thead>
            <tfoot>
                <tr class="row">
	                <th>全选<input type="checkbox" name="select_all" value="all"/></th>
	                <th>编号</th>
                    <th key="UserName" editable="true">
                    <?php if (isset($this->order['UserName'])):?>
                    <?php $name = $this->order['UserName'];?>
                    <a href="<?php echo $name['href'];?>">用户名<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	用户名
                    <?php endif;?>
                    </th>
                    <th key="Email" editable="true">
                     <?php if (isset($this->order['Email'])):?>
                    <?php $name = $this->order['Email'];?>
                    <a href="<?php echo $name['href'];?>">邮箱<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	邮箱
                    <?php endif;?>
 					</th>
                    <th key="Mobile" editable="true">
       <?php if (isset($this->order['Mobile'])):?>
                    <?php $name = $this->order['Mobile'];?>
                    <a href="<?php echo $name['href'];?>"> 手机<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	 手机
                    <?php endif;?>             
                   </th>
                    <th key="Nick" editable="true">
       <?php if (isset($this->order['Nick'])):?>
                    <?php $name = $this->order['Nick'];?>
                    <a href="<?php echo $name['href'];?>">昵称<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	昵称
                    <?php endif;?>             
                    </th>
                    <th key="Points" editable="true">
                    <?php if (isset($this->order['Points'])):?>
                    <?php $name = $this->order['Points'];?>
                    <a href="<?php echo $name['href'];?>">积分<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	积分
                    <?php endif;?>
                    	</th>
                    	<th>电话</th>
                    	<th>真实姓名</th>
                    	<th>性别</th>
                    	<th>区域</th>
                    	<th>地址</th>
                    	<th>QQ</th>
                    	<th>MSN</th>
                    <th>
      <?php if (isset($this->order['LastLogin'])):?>
                    <?php $name = $this->order['LastLogin'];?>
                    <a href="<?php echo $name['href'];?>"> 最后登录时间<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	 最后登录时间
                    <?php endif;?>              
                   </th>
                    <th>
      <?php if (isset($this->order['LoginCount'])):?>
                    <?php $name = $this->order['LoginCount'];?>
                    <a href="<?php echo $name['href'];?>"> 登录次数<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	登录次数
                    <?php endif;?>              
                    </th>
                    <th>
      <?php if (isset($this->order['LastUpdate'])):?>
                    <?php $name = $this->order['LastUpdate'];?>
                    <a href="<?php echo $name['href'];?>"> 最后修改时间<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	最后修改时间
                    <?php endif;?>              
                    </th>
                </tr>
            </tfoot>
            <tbody>
                <?php $startNumber = $this->startNumber;foreach ($this->paginaction as $user): ?>
                    <tr class="row" primary_value="<?php echo $user->UserID; ?>">
                    	<td width="60"><input type="checkbox" name="select" value="<?php echo $user->UserID; ?>" data-key="用户名" data-value="<?php echo $user->UserName; ?>" /></td>
                    	<td><?php echo $startNumber++;?></td>
                        <td key="UserName" editable="true"><?php echo $user->UserName; ?></td>
                        <td key="Email" editable="true"><?php echo $user->Email; ?></td>
                        <td key="Mobile" editable="true"><?php echo $user->Mobile; ?></td>
                        <td key="Nick" editable="true"><?php echo $user->Nick; ?></td>
                        <td key="Points" editable="true"><?php echo $user->Points; ?></td>
                        <td><?php echo $user->Tel;?></td>
                        <td><?php echo $user->TrueName;?></td>
                        <td><?php echo $user->Gender == 0 ? '保密' : ($user->Gender = 1 ?  '男' : '女') ;?></td>
                        <td><?php echo (isset($region[$user->Province]) ? $region[$user->Province] : ''),'-',isset($region[$user->City]) ? $region[$user->City] : '','-',isset($region[$user->District]) ? $region[$user->District] : '';?></td>
                        <td><?php echo $user->Address;?></td>
                        <td><?php echo $user->QQ;?></td>
                        <td><?php echo $user->MSN;?></td>
                        <td><?php echo $user->LastLogin; ?></td>
                        <td><?php echo $user->LoginCount; ?></td>
                        <td><?php echo $user->LastUpdate; ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
        <?php echo $this->paginationControl($this->paginaction,'Sliding','layout/pagination' , array('link' 
            => $this->url('backend' , array('controller' => 'member' , 'action' => 'all')).'?'.$this->query));?>
    </div>
</div>
<div id="dialog" title="筛选" style="display: none;">
	<form id="frmFilter">
		<div class="filter_item">
			<div class="filter_label"></div>
			<div class="filter_opt">
			</div>
			<div class='filter_val'><input value="" type="text" name="filter_value" /></div>
			<div class='condition_opt'><span class='add_c'>+</span></div>
			<div style='clear: both;'>&nbsp;</div>
		</div>
	</form>
</div>
<script type="text/javascript">
all = 1;
<!--
var productEditableParam={
		'postUrl':'/index/updateColumn',
		'primary_key':'UserID',
		'table':'MemberTable',
// 		'isShow':{
// 			type:'radio',
// 	        group:{
// 	            1:'显示',
// 	            0:'不显示'
// 	        }
// 		},
// 		'order':{
// 			type:'text',
// 			reg: /^\d+$/,
// 			tip:'只能为数字!'
// 		},
		'UserName':{
			type:'text',
			reg:/^[a-zA-Z0-9_]{3,16}$/,
			tip:'格式不正确：3-16个字母、数字或下划线组成'
		},
		'Email':{
			type:'text',
			reg:/^[_a-z0-9-]+(\.[_a-z0-9-]+)*@[a-z0-9-]+(\.[a-z0-9-]+)*$/,
			tip:'邮箱格式不正确'
		},
		'Mobile':{
			type:'text',
			reg:/^((\+86)|(86))?(13|4|5|8)\d{9}$/,
			tip:'手机号码格式不正确'
		},
		'Nick':{
			type:'text'
		},
		'Points':{
			type:'text',
			reg:/^[0-9]+(\.[0-9]{1,2})?$/,
			tip:'格式不正确'
		}
	};
var options={
		tableID:'table1',
		editableParam:productEditableParam
}
new Editable(options,$("#table1"));
var url = '<?php echo $this->url('backend' , array('controller' => 'member' , 'action' => 'all'));?>';
var query = '<?php echo $this->filterQuery?>';
$(function(){
	$(".col-1").css({'width':'1600px'});
// 	$(".box-header").css({'width' :parseInt($("#table1").width())-500+'px'});
	var select_field = [
	        			{name: 'UserName', vtype:'string',ctype:'text',html:'用户名'},
	        			{name: 'Email', vtype:'string',ctype:'text',html:'邮箱'},
	        			{name: 'Mobile',vtype:'string',ctype:'text',html:'手机'},
	        			{name: 'Tel',vtype:'string',ctype:'text',html:'电话'},
	        			{name: 'Nick',vtype:'string',ctype:'text',html:'昵称'},
	        			{name: 'TrueName',vtype:'string',ctype:'text',html:'真实姓名'},
	        			{name: 'Address',vtype:'string',ctype:'text',html:'地址'},
	        			{name: 'QQ',vtype:'string',ctype:'text',html:'QQ'},
	        			{name: 'MSN',vtype:'string',ctype:'text',html:'MSN'},
	        			{name: 'LoginCount',vtype:'int',ctype:'text',html:'登录次数'}
	        	    ];
    filter.init(select_field);
	$("#selector").click(function(){
		$("#dialog").dialog({position:'center',width:500,buttons: [ { text: "确定", click: function() {
			var query = filter.getQuery();
			location.href=url+'?'+query;
			 $( this ).dialog( "close" ); 
			} } ]});
	});
	var memory_list = getcookie('memory_id_list');
	var strs = memory_list.split(',');
	for (i=0;i<strs.length ;i++ )    
    {    
		$("input[type='checkbox'][name='select'][value='"+strs[i]+"']").click();
    }
	var options = {prov : "select[name='Province']", city : "select[name='City']", dist : "select[name='District']"};
	new Area(options);
})
//-->
</script>