<?php
$this->headScript()->appendFile($this->basePath('js/jquery-ui-1.10.2.custom.min.js'))
->appendFile($this->basePath('js/jquery.cleditor.min.js'))
->appendFile($this->basePath('js/jquery.ui.datepicker-zh-CN.js'));
$this->headLink()->appendStylesheet($this->basePath('styles/jquery-ui-1.10.2.custom.min.css'))
->appendStylesheet($this->basePath('styles/jquery.cleditor.css'));
$form = $this->form;
$msg = $this->flashMessages();
?>
<div class="box">
    <div class="box-header">
        <h2><i class="icon-box"></i>
   <?php echo $form->get('UserID')->getValue() ? '修改会员' : '新增会员';?>     
       </h2>
    <div class="t_top">
    <p class='t_right'>
    <a class="btn btn-return" href="<?php echo $this->url('backend' 
            , array('controller' => 'member' , 'action' => 'index'))?>">
        <i class="icon-plus"></i>返回</a>
    <a class="btn btn-submit" href="javascript:;">
        <i class="icon-plus"></i>提交</a>
        <a class="btn btn-reset" href="javascript:;">
        <i class="icon-plus"></i>重填</a>
    </p>
    </div>
    </div>
    <div class="box-content">
	   <?php if(!empty($msg['error'])):?>
            <div class="alert alert-error fade in">
            <button class="close" data-dismiss="alert" type="button">×</button>
            <?php foreach($msg['error'] as $v):?>
            <p><?php echo $v;?></p>
            <?php endforeach;?>
            </div>
            <?php endif;?>
            
            <?php if(!empty($msg['success'])):?>
            <div class="alert alert-success fade in">
            <button class="close" data-dismiss="alert" type="button">×</button>
            <?php foreach($msg['success'] as $v):?>
            <p><?php echo $v;?></p>
            <?php endforeach;?>
            </div>
            <?php endif;?>
        <form class="box-form" action="<?php echo $this->url('backend' , array('controller' => 'member' , 'action' => 'contactSave'))?>"
              method="post" enctype="multipart/form-data">
              <?php $img =  $form->get('ImgUrl')->getValue();?>
              <?php if (!empty($img)):?>
              <span class="show_image">
				<img height="150px" src="<?php echo $img;?>" />
				</span>
			<?php endif;?>
            <fieldset style="border:0;">
            	<?php echo $this->formHidden($form->get('UserID'))?>
                <?php echo $this->formText($form->get('UserName'))?>
                <?php //echo $this->formText($form->get('Password'))?>
                <?php echo $this->formText($form->get('Nick'))?>
                <?php echo $this->formFile($form->get('ImgUrl'))?>
                <?php echo $this->formText($form->get('Email'))?>
                <?php echo $this->formText($form->get('Mobile'))?>
                <?php echo $this->formText($form->get('Tel'))?>
                <?php echo $this->formText($form->get('Points'))?>
                <?php echo $this->formSelect($form->get('Gender'))?>
                <?php echo $this->formSelect($form->get('Province'))?>
                <?php echo $this->formSelect($form->get('City'))?>
                <?php echo $this->formSelect($form->get('District'))?>
                <?php echo $this->formText($form->get('Address'))?>
                <?php echo $this->formText($form->get('Birthday'))?>
                <?php echo $this->formText($form->get('QQ'))?>
                <?php echo $this->formText($form->get('MSN'))?>
                <?php echo $this->formSelect($form->get('Status'))?>
                <?php echo $this->formHidden($form->get('Source'));?>
                <?php echo $this->formSubmit($form->get('submit') , '提交')?>
            </fieldset>
        </form>
    </div>
</div>
<script>
var options = {prov : "select[name='Province']", city : "select[name='City']", dist : "select[name='District']"};
new Area(options);
$(function() {
	$("input[name='Birthday']").datepicker();
	$(".btn-submit").click(function(){
		$("input[type='submit'][class='button-element']").trigger('click');
	});
	$(".btn-reset").click(function(){
		$("input[type='reset'][class='button-element']").trigger('click');
	});
})
</script>