<?php
$this->headScript()->appendFile($this->basePath('js/jquery-ui-1.10.2.custom.min.js'))
->appendFile($this->basePath('ueditor/ueditor.config.js'))
->appendFile($this->basePath('ueditor/ueditor.all.js'))
->appendFile($this->basePath('js/jquery.ui.datepicker-zh-CN.js'));
$this->headLink()->appendStylesheet('http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css');
$user = $this->user;
$msg = $this->flashMessages();
$name=array_filter($user['name']);
$email = array_filter($user['email']);
// 			if ($user['mult'] == 1) {
// 				$sendTitleStr = '';
// 				$email = array_filter($user['email']);
// 				if (count($email) > 3) {
// 					$sendTitleStr = '('.implode(',', array_slice($email, 0, 3)).'……)';
// 				} else {
// 					$sendTitleStr = '('.implode(',', $email).')';
// 				}
// 				echo $sendTitleStr;
// 			} else {
//         		echo $user['UserName'],'('.$user['Email'].')';
//         	}
        ?>
<div class="box">
    <div class="box-header">
    <!-- 
        <h2><i class="icon-box"></i>给会员<span style="color:#ff0000; font-weight: blod;">
        </span>发送邮件<span style="float: right;"><a href="/member">返回</a></span></h2> -->
        <div class="t_top">
    <p class='t_right'>
    <a class="btn btn-return" href="<?php echo $this->url('backend' 
            , array('controller' => 'member' , 'action' => 'index'))?>">
        <i class="icon-plus"></i>返回</a>
    <a class="btn btn-submit" href="javascript:;">
        <i class="icon-plus"></i>发送</a>
    </p>
    </div>
    </div>
    <div class="box-content">
        	<?php if(!empty($msg['error'])):?>
            <div class="alert alert-error fade in">
            <button class="close" data-dismiss="alert" type="button">×</button>
            <?php foreach($msg['error'] as $v):?>
            <p><?php echo $v;?></p>
            <?php endforeach;?>
            </div>
            <?php endif;?>
            
            <?php if(!empty($msg['success'])):?>
            <div class="alert alert-success fade in">
            <button class="close" data-dismiss="alert" type="button">×</button>
            <?php foreach($msg['success'] as $v):?>
            <p><?php echo $v;?></p>
            <?php endforeach;?>
            </div>
            <?php endif;?>
        <form class="box-form" action="<?php echo $this->url('backend' , array('controller' => 'member' , 'action' => 'contactSendMail')).'?id='.$this->id;?>"
              method="post" enctype="multipart/form-data">
            <fieldset>
            <div class="input-group">
            	<div style="float:left;width:750px;">
            	<label for="name" class="input-label-mail">收件人</label>
            	<div class="input-item-mail receiver_style">
	            	<?php if (isset($user['name'])):?>
	            	<ul id="nameList">
	            	<?php foreach($name as $k=>$v):?>
	            	<li data-name="<?php echo $v;?>" data-email="<?php echo isset($email[$k]) ? $email[$k] : '';?>"><span class='cont'><?php echo $v;?></span><span class="clo">×</span><span class="segment">，</span></li>
	            	<?php endforeach;?>
	            	<?php endif;?>
	            	</ul>
            	</div>
            	</div>
            	<div style="float:left; padding-left:6px;"><?php echo '共<span class="totalCount">',count($name),'</span>人';?></div>
            </div>
            <div style='clear:both;'>&nbsp;</div>
            <div class="input-group">
            	<div style="float:left;width:750px;">
	            	<label for="name" class="input-label-mail">地址</label>
	            	<div class="input-item-mail receiver_style">
	            	<?php if (isset($user['email'])):?>
	            	<ul id='emailList'>
	            	<?php foreach($email as $k=>$v):?>
	            	<li data-name="<?php echo isset($email[$k]) ? $email[$k] : '';?>" data-email="<?php echo $v;?>"><?php echo '<span class="cont">'.$v.'</span><span class="clo">×</span>';?><span class="segment">，</span></li>
	            	<?php endforeach;?>
	            	</ul>
	            	<?php endif;?>
	            	</div>
	            </div>
	            <div style="float:left; padding-left:6px;"><input type='button' name='modify' value='调整' /></div>
            </div>
            <div style='clear:both;'>&nbsp;</div>
            <div class="input-group">
            	<label for="name" class="input-label-mail">标题</label>
            	<div class="input-item-mail"><input autocomplete="off" type="text" value="" name="subject" class="input-element"></div>
            </div>
            <div class="input-group">
            	<label for="name" class="input-label-mail">附件</label>
            	<div class="input-item-mail"><input autocomplete="off" type="file" value="" name="attach" class="input-element"></div>
            </div>
            <input style="color:#996633; width:300px;" type="hidden" readonly value="<?php echo implode(',', $user['email']);?>" name="email" class="input-element">
<!--             <div class="input-group"> -->
<!--             	<label for="name" class="input-label">收件人地址</label> -->
            	<div class="input-item-mail"></div>
<!--             </div> -->
            <div class="input-group">
<!--          	<label class="input-label-mail" for="footer">邮件内容</label> -->
         	     <div class="input-item-mail">
         	     <textarea id="myEditor" class="cleditor" type="text" name="content" class="input-element"></textarea>
         	     </div>
         	</div>
         	<div class="button-group"><input type="submit" class="button-element" name="submit" value="发送">&nbsp;&nbsp;&nbsp;&nbsp;<input type="reset" class="button-element" name="rest" value="取消"></div>
            </fieldset>
        </form>
    </div>
</div>
<div id="dialog" title="请选择收件人" class="none">
</div>
<script type="text/javascript">
var emailStore = <?php echo json_encode($email);?>;
var emailName = <?php echo json_encode($name);?>;
$(function(){
    UE.getEditor('myEditor');
    $(".btn-submit").click(function(){
		$("input[type='submit'][class='button-element']").trigger('click');
	});

//     $("input[name='modify']").click(function(){
// 		$('<div class="modal fade"><div class="modal-dialog"><div class="modal-content"><div class="modal-body">是否</div><div class="modal-footer"><button type="button" class="btn btn-default" data-dismiss="modal">关闭</button><a href="" class="btn btn-primary">dd</a></div></div></div></div>').modal({keyboard: false});
// 	});
	$("input[name='modify']").click(function(){
		var url = "/ajax/memberList";
		$.ajax({
			type:'POST',
			url:url,
			data:null,
			dataType:'json',
			cache:false,
			async:false,
			success:function(s) {
				var html = "<table class='table' id='table1'>";
				html += "<tr><th>全选<input type='checkbox' name='dialog_name_all' /></th><th>用户名</th><th>邮箱</th><th>手机号</th></tr>";
				for(var o in s) {
					html += "<tr><td><input type='checkbox' name='dialog_name' data-name='"+s[o].UserName+"' data-email='"+s[o].Email+"' data-mobile='"+s[o].Mobile+"' value='"+s[o].UserID+"' /></td><td>"+s[o].UserName+"</td><td>"+s[o].Email+"</td><td>"+s[o].Mobile+"</td><tr>";
// 					html += "<option value='"+s[o].region_id+"'>"+s[o].region_name+"</option>";
				}
				html += "</table>";
				$("#dialog").html(html);
				$("input[type='checkbox'][name='dialog_name_all']").click(
						function() {
							if ($(this).is(':checked')) {
								$("input[type='checkbox'][name='dialog_name']").prop('checked', this.checked);
							} else {
								$("input[type='checkbox'][name='dialog_name']").removeAttr('checked');
							}
						}
					);
			}
		});
		$("#dialog").dialog({position:'right',width:500,buttons: [ { text: "确定", click: function() {
			var nameList = '';
			var emailList = '';
			var email = '';
			var num = 0;
			emailStore = new Array();
			emailName = new Array();
			$("#nameList").html('');
			$("#emailList").html('');
			$("input[type='checkbox'][name='dialog_name']:checked").each(function(){
				if ($(this).attr('data-email') != '') {
					$("#nameList").append("<li data-name='"+$(this).attr('data-name')+"' data-email='"+$(this).attr('data-email')+"'><span class='cont'>"+$(this).attr('data-name')+"</span></span><span class='clo'>×</span><span class='segment'>，</span></li>");
					$("#emailList").append("<li data-name='"+$(this).attr('data-name')+"' data-email='"+$(this).attr('data-email')+"'><span class='cont'>"+$(this).attr('data-email')+"</span></span><span class='clo'>×</span><span class='segment'>，</span></li>");
					email += email ? ','+$(this).attr('data-email') : $(this).attr('data-email');
					num ++;
					emailName.push($(this).attr('data-name'));
					emailStore.push($(this).attr('data-email'));
				}
			});
// 			$("#nameList").html(nameList);
// 			$("#emailList").html(emailList);
			$(".totalCount").html(num);
			$("input[name='email']").val(email);
			 $( this ).dialog( "close" ); 
			} } ]});
	});
	$("#emailList,#nameList").on("click",'.clo',function(){
		var curEmail = $(this).parents('li').attr('data-email');
		var curName = $(this).parents('li').attr('data-name');
		for (var i = 0; i < emailStore.length; i ++) {
			if (emailStore[i] == curEmail) {
				emailStore.splice(i, 1);
				emailName.splice(i, 1);
				$("#emailList li[data-email='"+curEmail+"']").remove();
				$("#nameList li[data-email='"+curEmail+"']").remove();
				var num = $('.totalCount').html();
				$('.totalCount').html(num-1);
			}
		}
		$("input[name='email']").val(emailStore.join(','));
	});
})
</script>