<?php 
$params = $this->params;
$msg = $this->flashMessages();
?>
<div class="box">
    <div class="box-header">
<!--         <h2><i class="icon-box"></i>身份认证</h2> -->
        <div class="t_top">
        <div class="t_inline">
        	<form class="form-inline" action="<?php echo $this->url('backend', array('controller' 
            => 'member', 'action' => 'identity')); ?>" method="get">
                <div class="input-group">
<!--                     <label>认证类型</label> -->
                    <select name="type">
                        <option value="">认证类型筛选</option>
                        <option value="1" <?php echo isset($params['type']) && $params['type']==1 ? 'selected=selected' : '';?>>个人</option>
                        <option value="2" <?php echo isset($params['type']) && $params['type']==2 ? 'selected=selected' : '';?>>企业</option>
                    </select>
<!--                 	<label>审核</label> -->
                    <select name="status">
                        <option value="no" <?php echo ((isset($params['status']) && $params['status']=='no') || (!isset($params['status']))) ? 'selected=selected' : '';?>>审核状态筛选</option>
                        <option value="0" <?php echo isset($params['status']) && $params['status']=='0' ? 'selected=selected' : '';?>>未审核</option>
                        <option value="1" <?php echo isset($params['status']) && $params['status']=='1' ? 'selected=selected' : '';?>>已审核</option>
                        <option value="2" <?php echo isset($params['status']) && $params['status']=='2' ? 'selected=selected' : '';?>>未通过</option>
                    </select>
                    <input autocomplete="off" class="input-element span3" value="<?php echo isset($this->k) ? $this->k : '';?>" name="k" type="text">
                    
                <button class="button-element" type="submit">搜索</button>
                
<!--                 <button class="button-element" type='button' id="selector">筛选</button> -->
                </div>
        	</form>
        	</div>
        <p class="t_right">
     <a class="btn btn-success" id="chk_Approved" key='1' href="javascript:;">
        <i class="icon-plus"></i>审核通过</a>
        <a class="btn btn-success" id="chk_unApproved" key='0' href="javascript:;">
        <i class="icon-plus"></i>审核不通过</a>
        <a class="btn btn-delete" href="javascript:;" _href="<?php echo $this->url('backend', array('controller' 
                                => 'member', 'action' => 'deleteIdentity')) ?>?id=" onClick="diyConfirm('删除' , $(this).attr('href'), this);return false;"><i class="icon-delete"></i>删除
                            </a>
        </p>
        </div>
    </div>
    
    <div class="box-content">
    <?php if(!empty($msg['error'])):?>
            <div class="alert alert-error fade in">
            <button class="close" data-dismiss="alert" type="button">×</button>
            <?php foreach($msg['error'] as $v):?>
            <p><?php echo $v;?></p>
            <?php endforeach;?>
            </div>
            <?php endif;?>
            
            <?php if(!empty($msg['success'])):?>
            <div class="alert alert-success fade in">
            <button class="close" data-dismiss="alert" type="button">×</button>
            <?php foreach($msg['success'] as $v):?>
            <p><?php echo $v;?></p>
            <?php endforeach;?>
            </div>
            <?php endif;?>
        <table class="table" id="table1">
            <thead>
                <tr class="row">
                	<th>全选<input type="checkbox" name="select_all" value="all"/></th>
                	<th>编号</th>
                    <th>
                    <?php if (isset($this->order['UserName'])):?>
                    <?php $name = $this->order['UserName'];?>
                    <a href="<?php echo $name['href'];?>">用户名<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	用户名
                    <?php endif;?>
                    </th>
                    <th>
                    <?php if (isset($this->order['type'])):?>
                    <?php $name = $this->order['type'];?>
                    <a href="<?php echo $name['href'];?>">认证类型<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	认证类型
                    <?php endif;?></th>
                    <th>
                    <?php if (isset($this->order['name'])):?>
                    <?php $name = $this->order['name'];?>
                    <a href="<?php echo $name['href'];?>">真实姓名/公司名称<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	真实姓名/公司名称
                    <?php endif;?></th>
                    <th>
                    <?php if (isset($this->order['code'])):?>
                    <?php $name = $this->order['code'];?>
                    <a href="<?php echo $name['href'];?>">身份证号码/组织代码机构<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	身份证号码/组织代码机构
                    <?php endif;?>              
                    </th>
                    <th>
                    <?php if (isset($this->order['addTime'])):?>
                    <?php $name = $this->order['addTime'];?>
                    <a href="<?php echo $name['href'];?>">申请时间<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	申请时间
                    <?php endif;?>
                    </th>
                    <th key="status" editable="true">
                    <?php if (isset($this->order['status'])):?>
                    <?php $name = $this->order['status'];?>
                    <a href="<?php echo $name['href'];?>">审核状态<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	审核状态
                    <?php endif;?>              
                    </th>
                    <th>
                    <?php if (isset($this->order['lastApproved'])):?>
                    <?php $name = $this->order['lastApproved'];?>
                    <a href="<?php echo $name['href'];?>">批准时间<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	批准时间
                    <?php endif;?></th>
                </tr>
            </thead>
            <tfoot>
                <tr class="row">
                	<th>全选<input type="checkbox" name="select_all" value="all"/></th>
                	<th>编号</th>
                    <th>
                    <?php if (isset($this->order['UserName'])):?>
                    <?php $name = $this->order['UserName'];?>
                    <a href="<?php echo $name['href'];?>">用户名<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	用户名
                    <?php endif;?>
                    </th>
                    <th>
                    <?php if (isset($this->order['type'])):?>
                    <?php $name = $this->order['type'];?>
                    <a href="<?php echo $name['href'];?>">认证类型<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	认证类型
                    <?php endif;?></th>
                    <th>
                    <?php if (isset($this->order['name'])):?>
                    <?php $name = $this->order['name'];?>
                    <a href="<?php echo $name['href'];?>">真实姓名/公司名称<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	真实姓名/公司名称
                    <?php endif;?></th>
                    <th>
                    <?php if (isset($this->order['code'])):?>
                    <?php $name = $this->order['code'];?>
                    <a href="<?php echo $name['href'];?>">身份证号码/组织代码机构<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	身份证号码/组织代码机构
                    <?php endif;?>              
                    </th>
                    <th>
                    <?php if (isset($this->order['addTime'])):?>
                    <?php $name = $this->order['addTime'];?>
                    <a href="<?php echo $name['href'];?>">申请时间<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	申请时间
                    <?php endif;?>
                    </th>
                    <th key="status" editable="true">
                    <?php if (isset($this->order['status'])):?>
                    <?php $name = $this->order['status'];?>
                    <a href="<?php echo $name['href'];?>">审核状态<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	审核状态
                    <?php endif;?>              
                    </th>
                    <th>
                    <?php if (isset($this->order['lastApproved'])):?>
                    <?php $name = $this->order['lastApproved'];?>
                    <a href="<?php echo $name['href'];?>">批准时间<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	批准时间
                    <?php endif;?></th>
                </tr>
            </tfoot>
            <tbody>
                <?php if(count($this->records) > 0):?>
                <?php $startNumber = $this->startNumber;foreach($this->records as $r):?>
                <tr class="row" primary_value="<?php echo $r['id']?>">
                	<td><input type="checkbox" name="select" value="<?php echo $r['id']?>" data-key="认证记录" data-value="<?php echo $r['UserName']; ?>" /></td>
                    <td><?php echo $startNumber++;?></td>
                    <td><?php echo $r['UserName'];?></td>
                    <td><?php echo $r['type_name']?></td>
                    <td><?php echo $r['name']?></td>
                    <td><?php echo $r['code']?></td>
                    <td><?php echo $r['addTime']?></td>
                    <td key="status" editable="true"><?php echo $r['check_desc']?></td>
                    <td><?php echo $r['lastApproved']?></td>
                </tr>
                <?php endforeach;?>
                <?php endif;?>
            </tbody>
        </table>
        <?php echo $this->paginationControl($this->paginaction,'Sliding','layout/pagination' , array('link' => $this->url));?>
    </div>
</div>
<script>
var productEditableParam={
		'postUrl':'/index/updateColumn',
		'primary_key':'id',
		'table':'IdentityTable',
		'status':{
			type:'radio',
	        group:{
				0:'<span class=red>未审核</span>',
	            1:'已审核',
	            2:'未通过'
	        }
		}
	};
var options={
		tableID:'table1',
		editableParam:productEditableParam
}
new Editable(options,$("#table1"));
$(function(){
	$("#chk_Approved, #chk_unApproved").click(function(){
		var ids = '';
		$("input[type='checkbox'][name='select']").each(function(){
			if ($(this).is(':checked')) {
				ids += ','+$(this).val();
			}
		});
		if (ids != '') {
			var url = "/ajax/approved";
			var key = $(this).attr('key');
			$.ajax({
                type: 'POST',
                url: url,
                data: "ids="+ids+"&key="+key,
                success: function(data){
					if (data.code == 0) {
						location.reload();
					} else {
						alert(data.msg);
					}
                },
                dataType: 'JSON'
			});
// 			Ajax.call(url, "ids="+ids, function(s){
				
// 			});
		}
	});
})
</script>