<?php
$this->headScript()->appendFile($this->basePath('js/jquery-ui-1.10.2.custom.min.js'));
$this->headLink()->appendStylesheet('http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css');
$msg = $this->flashMessages();
?>
<div class="box">
    <div class="box-header">
<!--         <h2><i class="icon-box"></i>会员列表</h2> -->
        <div class="t_top">
        	<div class="t_inline">
        	<form class="form-inline" action="<?php echo $this->url('backend', array('controller' 
            => 'member', 'action' => 'index')); ?>" method="get">
                <div class="input-group">
                    <input autocomplete="off" class="input-element span3" value="<?php echo isset($this->k) ? $this->k : '';?>" name="k" type="text">
                    
                <button class="button-element" type="submit">搜索</button>
                
                <button class="button-element" type='button' id="selector">筛选</button>
                </div>
        	</form>
        	</div>
        	<p class='t_right'><a class="btn btn-success" href="<?php echo $this->url('backend' 
            , array('controller' => 'member' , 'action' => 'save'))?>">
        <i class="icon-plus"></i>新增</a>
        					<a class="btn btn-edit" href="javascript:;" _href="<?php echo $this->url('backend', array('controller' 
                                => 'member', 'action' => 'save')) ?>?id=">
                                <i class="icon-edit"></i>编辑
                            </a>
                            <a class="btn btn-edit" href="javascript:;" _href="<?php echo $this->url('backend', array('controller' 
                                => 'member', 'action' => 'pwd')) ?>?id=">
                                <i class="icon-edit"></i>设密
                            </a>
                            <a class="btn btn-edit" editMult="true" href="javascript:;" _href="<?php echo $this->url('backend', array('controller' 
                                => 'member', 'action' => 'sendMail')) ?>?id=">
                                <i class="icon-edit"></i>邮件
                            </a>
                            <a class="btn btn-delete" href="javascript:;" _href="<?php echo $this->url('backend', array('controller' 
                                => 'member', 'action' => 'delete')) ?>?id=" onClick="diyConfirm('删除' , $(this).attr('href'), this);return false;"><i class="icon-delete"></i>删除
                            </a>
        </p>
     </div>
    </div>
    <div class="box-content">
    <?php if(!empty($msg['error'])):?>
            <div class="alert alert-error fade in">
            <button class="close" data-dismiss="alert" type="button">×</button>
            <?php foreach($msg['error'] as $v):?>
            <p><?php echo $v;?></p>
            <?php endforeach;?>
            </div>
            <?php endif;?>
            
            <?php if(!empty($msg['success'])):?>
            <div class="alert alert-success fade in">
            <button class="close" data-dismiss="alert" type="button">×</button>
            <?php foreach($msg['success'] as $v):?>
            <p><?php echo $v;?></p>
            <?php endforeach;?>
            </div>
            <?php endif;?>
        <table class="table" id="table1">
            <thead>
                <tr class="row">
	                <th>全选<input type="checkbox" name="select_all" value="all"/></th>
	                <th>编号</th>
                    <th key="UserName" editable="true">
                    <?php if (isset($this->order['UserName'])):?>
                    <?php $name = $this->order['UserName'];?>
                    <a href="<?php echo $name['href'];?>">用户名<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	用户名
                    <?php endif;?>
                    </th>
                    <th key="Email" editable="true">
                     <?php if (isset($this->order['Email'])):?>
                    <?php $name = $this->order['Email'];?>
                    <a href="<?php echo $name['href'];?>">邮箱<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	邮箱
                    <?php endif;?>
 					</th>
                    <th key="Mobile" editable="true">
       <?php if (isset($this->order['Mobile'])):?>
                    <?php $name = $this->order['Mobile'];?>
                    <a href="<?php echo $name['href'];?>"> 手机<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	 手机
                    <?php endif;?>             
                   </th>
                    <th key="Nick" editable="true">
       <?php if (isset($this->order['Nick'])):?>
                    <?php $name = $this->order['Nick'];?>
                    <a href="<?php echo $name['href'];?>">昵称<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	昵称
                    <?php endif;?>             
                    </th>
                    <th key="Points" editable="true">
                    <?php if (isset($this->order['Points'])):?>
                    <?php $name = $this->order['Points'];?>
                    <a href="<?php echo $name['href'];?>">积分<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	积分
                    <?php endif;?>
                    	</th>
                    <th>
      <?php if (isset($this->order['LastLogin'])):?>
                    <?php $name = $this->order['LastLogin'];?>
                    <a href="<?php echo $name['href'];?>"> 最后登录时间<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	 最后登录时间
                    <?php endif;?>              
                   </th>
                    <th>
      <?php if (isset($this->order['LoginCount'])):?>
                    <?php $name = $this->order['LoginCount'];?>
                    <a href="<?php echo $name['href'];?>"> 登录次数<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	登录次数
                    <?php endif;?>              
                    </th>
                    <th>
      <?php if (isset($this->order['LastUpdate'])):?>
                    <?php $name = $this->order['LastUpdate'];?>
                    <a href="<?php echo $name['href'];?>"> 最后修改时间<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	最后修改时间
                    <?php endif;?>              
                    </th>
                </tr>
            </thead>
            <tbody>
                <?php $startNumber = $this->startNumber;foreach ($this->paginaction as $user): ?>
                    <tr class="row" primary_value="<?php echo $user->UserID; ?>">
                    	<td><input type="checkbox" name="select" value="<?php echo $user->UserID; ?>" data-key="用户名" data-value="<?php echo $user->UserName; ?>" /></td>
                    	<td><?php echo $startNumber++;?></td>
                        <td key="UserName" editable="true"><?php echo $user->UserName; ?></td>
                        <td key="Email" editable="true"><?php echo $user->Email; ?></td>
                        <td key="Mobile" editable="true"><?php echo $user->Mobile; ?></td>
                        <td key="Nick" editable="true"><?php echo $user->Nick; ?></td>
                        <td key="Points" editable="true"><?php echo $user->Points; ?></td>
                        <td><?php echo $user->LastLogin; ?></td>
                        <td><?php echo $user->LoginCount; ?></td>
                        <td><?php echo $user->LastUpdate; ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
        <?php echo $this->paginationControl($this->paginaction,'Sliding','layout/pagination' , array('link' 
            => $this->url('backend' , array('controller' => 'member' , 'action' => 'index')).'?'.$this->query));?>
    </div>
</div>
<div id="dialog" title="筛选" style="display: none;">
<!-- 	添加筛选条件：<select name="selector_limit" id="select_all_options"> -->
<!-- 		<option value="Point" vtype="int" ctype="select">积分</option> -->
<!-- 		<option value="Gender" vtype="int" ctype="radio">性别</option> -->
<!-- 	</select> -->
	<form id="frmFilter">
		<div id="Point">
			<div class="filter_label">积分</div>
			<div class="filter_opt">
				<select name="select_Point"><option value="than">大于</option><option value="lthan">小于</option><option value="nequal">等于</option><option value="sthan">小于等于</option><option value="bthan">大于等于</option></select>
			</div>
			<div class='filter_val'><input id="filter_value" value="" type="text" name="Point" /></div>
		</div>
		<div style='clear: both;'>&nbsp;</div>
		<div class="filter_line">
			<ul>
				<li>
				<select name="relationship">
				<option value="1">与</option>
				<option value="2">或</option>
				</select></li>
				<li>
				<select name="filter_fields">
					<option value="Mobile">手机</option>
					<option value="Mobile">手机</option>
					<option value="Mobile">手机</option>
				</select>
				</li>
			</ul>
		</div>
		<div id="Gender">
			<div class="filter_label">性别</div>
			<div class="filter_opt">
			</div>
			<div class='filter_val'>
				<input type="radio" value="0" name="Gender">保密
				<input type="radio" value="1" name="Gender">男
				<input type="radio" value="2" name="Gender">女
			</div>
		</div>
	</form>
</div>
<script type="text/javascript">
<!--
var productEditableParam={
		'postUrl':'/index/updateColumn',
		'primary_key':'UserID',
		'table':'MemberTable',
// 		'isShow':{
// 			type:'radio',
// 	        group:{
// 	            1:'显示',
// 	            0:'不显示'
// 	        }
// 		},
// 		'order':{
// 			type:'text',
// 			reg: /^\d+$/,
// 			tip:'只能为数字!'
// 		},
		'UserName':{
			type:'text',
			reg:/^[a-zA-Z0-9_]{3,16}$/,
			tip:'格式不正确：3-16个字母、数字或下划线组成'
		},
		'Email':{
			type:'text',
			reg:/^[_a-z0-9-]+(\.[_a-z0-9-]+)*@[a-z0-9-]+(\.[a-z0-9-]+)*$/,
			tip:'邮箱格式不正确'
		},
		'Mobile':{
			type:'text',
			reg:/^((\+86)|(86))?(13|4|5|8)\d{9}$/,
			tip:'手机号码格式不正确'
		},
		'Nick':{
			type:'text'
		},
		'Points':{
			type:'text',
			reg:/^[0-9]+(\.[0-9]{1,2})?$/,
			tip:'格式不正确'
		}
	};
var options={
		tableID:'table1',
		editableParam:productEditableParam
}
new Editable(options,$("#table1"));
var url = '<?php echo $this->url('backend' , array('controller' => 'member' , 'action' => 'index'));?>';
var query = '<?php echo $this->filterQuery?>';
$(function(){
	$("#selector").click(function(){
		$("#dialog").dialog({position:'center',width:300,buttons: [ { text: "确定", click: function() {
			var point_val = $("input[type='text'][name='Point']").val();
			if (point_val != '') {
				var p_filter = $("select[name='select_Point']").val();
				query += "&Points=Points|" + p_filter + "|" + point_val;
			}
			var gender_val = $("input[type='radio'][name='Gender']:checked").val();	
			if (typeof gender_val != 'undefined') {
				query += "&Gender="+gender_val;
			}
			location.href=url+'?'+query;
			 $( this ).dialog( "close" ); 
			} } ]});
	});
	var memory_list = getcookie('memory_id_list');
	var strs = memory_list.split(',');
	for (i=0;i<strs.length ;i++ )    
    {    
		$("input[type='checkbox'][name='select'][value='"+strs[i]+"']").click();
    }
})
//-->
</script>