<?php
$this->headScript()->appendFile($this->basePath('js/jquery-ui-1.10.2.custom.min.js'))
->appendFile($this->basePath('js/jquery.cleditor.min.js'))
->appendFile($this->basePath('js/jquery.ui.datepicker-zh-CN.js'));
$this->headLink()->appendStylesheet($this->basePath('styles/jquery-ui-1.10.2.custom.min.css'))
->appendStylesheet($this->basePath('styles/jquery.cleditor.css'));
$form = $this->form;
$msg = $this->flashMessages();
?>
<div class="box">
    <div class="box-header">
        <h2><i class="icon-box"></i>设置会员<span style="color:#ff0000; font-weight: blod;"><?php echo $form->get('UserName')->getValue();?></span>的密码</h2>
    </div>
    <div class="box-content">
        	<?php if(!empty($msg['error'])):?>
            <div class="alert alert-error fade in">
            <button class="close" data-dismiss="alert" type="button">×</button>
            <?php foreach($msg['error'] as $v):?>
            <p><?php echo $v;?></p>
            <?php endforeach;?>
            </div>
            <?php endif;?>
            
            <?php if(!empty($msg['success'])):?>
            <div class="alert alert-success fade in">
            <button class="close" data-dismiss="alert" type="button">×</button>
            <?php foreach($msg['success'] as $v):?>
            <p><?php echo $v;?></p>
            <?php endforeach;?>
            </div>
            <?php endif;?>
        <form class="box-form" action="<?php echo $this->url('backend' , array('controller' => 'member' , 'action' => 'pwd')).'?id='.$form->get('UserID')->getValue();?>"
              method="post" enctype="multipart/form-data">
            <fieldset>
            	<?php echo $this->formHidden($form->get('UserID'))?>
            	<?php echo $this->formText($form->get('Password'))?>
                <?php echo $this->formText($form->get('rePassword'))?>
                <?php echo $this->formSubmit($form->get('submit') , '提交')?>
            </fieldset>
        </form>
    </div>
</div>
<script>
$(function() {

})
</script>