<?php
$this->headScript()->appendFile($this->basePath('js/jquery-ui-1.10.2.custom.min.js'))
->appendFile($this->basePath('js/jquery.cleditor.min.js'))
->appendFile($this->basePath('js/jquery.ui.datepicker-zh-CN.js'));
$this->headLink()->appendStylesheet($this->basePath('styles/jquery-ui-1.10.2.custom.min.css'))
->appendStylesheet($this->basePath('styles/jquery.cleditor.css'));
$user = $this->user;
$msg = $this->flashMessages();
?>
<div class="box">
    <div class="box-header">
        <h2><i class="icon-box"></i>给会员<span style="color:#ff0000; font-weight: blod;">
        <?php
			if ($user['mult'] == 1) {
				$sendTitleStr = '';
				$email = array_filter($user['email']);
				if (count($email) > 3) {
					$sendTitleStr = '('.implode(',', array_slice($email, 0, 3)).'……)';
				} else {
					$sendTitleStr = '('.implode(',', $email).')';
				}
				echo $sendTitleStr;
			} else {
        		echo $user['UserName'],'('.$user['Email'].')';
        	}
        ?></span>发送邮件<span style="float: right;"><a href="/member">返回</a></span></h2>
    </div>
    <div class="box-content">
        	<?php if(!empty($msg['error'])):?>
            <div class="alert alert-error fade in">
            <button class="close" data-dismiss="alert" type="button">×</button>
            <?php foreach($msg['error'] as $v):?>
            <p><?php echo $v;?></p>
            <?php endforeach;?>
            </div>
            <?php endif;?>
            
            <?php if(!empty($msg['success'])):?>
            <div class="alert alert-success fade in">
            <button class="close" data-dismiss="alert" type="button">×</button>
            <?php foreach($msg['success'] as $v):?>
            <p><?php echo $v;?></p>
            <?php endforeach;?>
            </div>
            <?php endif;?>
        <form class="box-form" action="<?php echo $this->url('backend' , array('controller' => 'member' , 'action' => 'sendMail')).'?id='.$this->id;?>"
              method="post" enctype="multipart/form-data">
            <fieldset>
            <div class="input-group">
            	<label for="name" class="input-label">邮件标题</label>
            	<div class="input-item"><input autocomplete="off" type="text" value="" name="subject" class="input-element"></div>
            </div>
            <div class="input-group">
            	<label for="name" class="input-label">收件人地址</label>
            	<div class="input-item"><input style="color:#996633; width:300px;" type="text" readonly value="<?php echo $user['mult'] == 1 ? implode(',', $email) : $user['Email'];?>" name="email" class="input-element"></div>
            </div>
            <div class="input-group">
         	<label class="input-label" for="footer">邮件内容</label>
         	     <div class="input-item">
         	     <textarea class="cleditor" type="text" name="content" class="input-element"></textarea>
         	     </div>
         	</div>
         	<div class="button-group"><input type="submit" class="button-element" name="submit" value="发送">&nbsp;&nbsp;&nbsp;&nbsp;<input type="reset" class="button-element" name="rest" value="取消"></div>
            </fieldset>
        </form>
    </div>
</div>
<script>
$(function(){
    
    $(".cleditor").cleditor({
        width:        600, // width not including margins, borders or padding
        height:       300, // height not including margins, borders or padding
        controls:     // controls to add to the toolbar
                      "bold italic underline strikethrough subscript superscript | font size " +
                      "style | color highlight removeformat | bullets numbering | outdent " +
                      "indent | alignleft center alignright justify | undo redo | " +
                      "rule image link unlink | cut copy paste pastetext | print source",
        colors:       // colors in the color popup
                      "FFF FCC FC9 FF9 FFC 9F9 9FF CFF CCF FCF " +
                      "CCC F66 F96 FF6 FF3 6F9 3FF 6FF 99F F9F " +
                      "BBB F00 F90 FC6 FF0 3F3 6CC 3CF 66C C6C " +
                      "999 C00 F60 FC3 FC0 3C0 0CC 36F 63F C3C " +
                      "666 900 C60 C93 990 090 399 33F 60C 939 " +
                      "333 600 930 963 660 060 366 009 339 636 " +
                      "000 300 630 633 330 030 033 006 309 303",    
        fonts:        // font names in the font popup
                      "Arial,Arial Black,Comic Sans MS,Courier New,Narrow,Garamond," +
                      "Georgia,Impact,Sans Serif,Serif,Tahoma,Trebuchet MS,Verdana",
        sizes:        // sizes in the font size popup
                      "1,2,3,4,5,6,7",
        styles:       // styles in the style popup
                      [["Paragraph", "<p>"], ["Header 1", "<h1>"], ["Header 2", "<h2>"],
                      ["Header 3", "<h3>"],  ["Header 4","<h4>"],  ["Header 5","<h5>"],
                      ["Header 6","<h6>"]],
        useCSS:       false, // use CSS to style HTML when possible (not supported in ie)
        docType:      // Document type contained within the editor
                      '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">',
        docCSSFile:   // CSS file used to style the document contained within the editor
                      "", 
        bodyStyle:    // style to assign to document body contained within the editor
                      "margin:4px; font:10pt Arial,Verdana; cursor:text"
    });
})
</script>