<?php $msg = $this->flashMessages();?>
<div class="liuc"><img src="images/FrontEnd/liuc_1.jpg" width="905" height="39" /></div>
<form id="register" name="register" method="post" action="/register">
  <ul class="input_test">
 <li>
 <?php if(!empty($msg['error'])):?>
            <div class="alert alert-error fade in">
            <button class="close" data-dismiss="alert" type="button">×</button>
            <?php foreach($msg['error'] as $v):?>
            <p><?php echo $v;?></p>
            <?php endforeach;?>
            </div>
            <?php endif;?>
            
            <?php if(!empty($msg['success'])):?>
            <div class="alert alert-success fade in">
            <button class="close" data-dismiss="alert" type="button">×</button>
            <?php foreach($msg['success'] as $v):?>
            <p><?php echo $v;?></p>
            <?php endforeach;?>
            </div>
            <?php endif;?></li>
<li>
<label for="inp_name">会员名：</label>
  <p><input style="ime-mode: disabled" data-trim="true" data-required="true" data-pattern="^[a-zA-Z0-9_]{3,16}$" data-validate="un" data-describedby="for_username" data-description="UserName" name="UserName" type="text" class="input_out" id="in_name1" onfocus="this.className='input_on';this.onmouseout=''" onblur="this.className='input_off';this.onmouseout=function(){this.className='input_out'};" onmousemove="this.className='input_move'" onmouseout="this.className='input_out'" /></p>
 <span id="for_username">3到16个字符，允许包含"_"、数字、字母</span>
</li>
<li>
<label for="inp_name">登录密码：</label>
  <p><input data-required="true" data-pattern="^.{6,16}$" maxlength="16" data-describedby="for_password" data-description="password" name="password" type="password" class="input_out" id="in_name2" onfocus="this.className='input_on';this.onmouseout=''" onblur="this.className='input_off';this.onmouseout=function(){this.className='input_out'};" onmousemove="this.className='input_move'" onmouseout="this.className='input_out'" /></p>
 <span id="for_password">6到16位字符</span><!-- <h1>两次密码不一致</h1> -->

</li>
<li>
<label for="inp_name">确认密码：</label>
  <p><input  data-required="true" data-validate="pwd" data-pattern="^.{6,16}$" maxlength="16" data-describedby="for_repassword" data-description="repassword" name="repassword" type="password" class="input_out" id="in_name3" onfocus="this.className='input_on';this.onmouseout=''" onblur="this.className='input_off';this.onmouseout=function(){this.className='input_out'};" onmousemove="this.className='input_move'" onmouseout="this.className='input_out'" /></p>
 <span id="for_repassword">6到16位字符</span>

</li>
<li>
<label for="inp_name">验证码：</label>
<p><input data-required="true" data-describedby="for_reg_code" data-description="reg_code" name="reg_code" type="text" class="input_out1" id="in_email" onfocus="this.className='input_on1';this.onmouseout=''" onblur="this.className='input_off1';this.onmouseout=function(){this.className='input_out1'};" onmousemove="this.className='input_move1'" onmouseout="this.className='input_out1'" /></p>
<span><img src="/register-captcha" width="77" height="28"  class="register-captcha" style="cursor:pointer;" alt="看不清？点击图片更换验证码"/></span>
<span id="for_reg_code"></span>

</li>
<li class="btn"><img style="cursor:pointer;" src="/images/FrontEnd/btn_01.jpg" height="40" id="register_btn" /></li>
<li>
  <h2><a href="#">《服务协议》</a></h2></li>
 </ul>
</form>
<div class="reg_r">
  <div class="sj_pic"><img src="/images/FrontEnd/sj_pic.jpg" width="68" height="68" /></div>
  <div class="sj_txt">手机快速注册</div>
  <div class="sj_txt">编写短信<span class="cstxt"> “DH”</span> 发送到</div>
  <div class="sj_txt"><span class="cstxt">123456</span></div>
</div>
<script>
$('#register').validate({
	onBlur : true,
	sendForm : true,
	eachValidField : function() {
		if ($(this).attr('name') != 'reg_code') {
		$(this).parents('p').next('span').html('<img src="/images/FrontEnd/yes.jpg" width="25" height="26" />');
		}
	},
	description : {
		UserName : {
			required : '请输入用户名',
			pattern : '<img src="/images/FrontEnd/no.jpg" />格式不正确',
			conditional : '<img src="/images/FrontEnd/no.jpg" />该会员名已被注册'
		},
		password : {
			required : '请输入密码',
			pattern : '<img src="/images/FrontEnd/no.jpg" />格式不正确'
		},
		repassword : {
			required : '请输入确认密码',
			pattern : '<img src="/images/FrontEnd/no.jpg" />格式不正确',
			conditional : '<img src="/images/FrontEnd/no.jpg" />两次密码输入不一致'
		},
		reg_code : {
			required : '请输入验证码'
		}
	},
	valid:function() {
	}
});
jQuery.validateExtend({
    un : {
        required : true,
        pattern : /^[a-zA-Z0-9_]{3,16}$/,
        conditional : function(value) {
        	return isUniqueUserName(value);
        }
    },
    pwd : {
		required : true,
		pattern : /^.{6,16}$/,
		conditional : function(value) {
			return value == $("input[name='password']").val();
		}
    }
});
$(function(){
	
	$("#register_btn").click(function(){
		$("form[name='register']").submit();
	});
	$(".register-captcha").click(function(){
		$(this).attr('src', '/register-captcha?t'+Math.random());
	});
})
</script>