<?php $msg = $this->flashMessages();?>
<div class="liuc"><img src="/images/FrontEnd/liuc_2.jpg" width="905" height="38" /></div>


<div class="Land_bg">
    <p> <span class="dd_yse"><img src="/images/FrontEnd/cg_yes.jpg" width="35" height="37" /></span><span class="cheng"><?php echo $this->Email;?></span> ，恭喜您注册成功！</p>
    <p>　　　　您的邮箱                             <span class="cheng"><?php echo $this->Email;?></span> 可以作为登录名，<span class="lanse">用于登录</span>。</p>
</div>
