  <div class="right_txt">关于我们</div>
    <div class="right_con">
        <p>御订网，预订天下美好事物。御订网，是一家以预约、预订、预售、预购类网址导航和信息服务的专业化网站。我们以国宾馆、财政定点饭店、公务卡消费点、教育机构、金融机构、产业基础设施等预约预订为核心资源，逐步拓展到衣食住行、教育娱乐、健康财富类信息服务和商务预订，致力于打造服务社会高层次、高素质、高品位人士的专业化预订服务网站。同时提供多种搜索引擎入口、天气预报、万年日历、团购导航、地方导航、票务交换等特色服务。 </p>
      <p >御订网的理念是皇家典范、尊贵体验、远见卓识、拥享天下。御订网的使命是消除拥挤排队，消灭空号空位，预防生命浪费，构建秩序社会。御订网，幸福导航，尊贵人生。御订网刚刚启航，期待您的关注与关爱，更期待您的加盟与加油。让我们共挂云帆，追梦远航！</p>
    </div>
   <div class="right_txt">记住我们的logo和网址</div>
   <div class="right_con1">
      <span class="r_logo"><img src="/images/FrontEnd/reg_logo.png" width="117" height="76" /></span>
      <span class="r_diz">www.yudingvip.com</span>
   </div>
    
  <div class="right_txt"> 您可以御订  </div>
   <div class="right_con2">
     
    <div class="r1z">
      <div class="jy"><h1>锦衣</h1><p>婚纱、旗袍、时装 西服、休闲装、鞋帽</p></div>
      <div class="ms">
        <h1>美食</h1>
        <p>婚宴、国宴、西餐、快餐、咖啡、生日蛋糕 
</p></div>
      <div class="xz">
        <h1>享住</h1>
        <p>国宾馆、定点饭店、星级酒店、快捷酒店
</p></div>
      <div class="cx">
        <h1>成行</h1>
        <p>飞机票、火车票、邮轮票、旅行线路</p>
      </div>
    </div>
        <div class="r1z">
      <div class="jx">
        <h1>教育</h1>
        <p>英语、奥数、国学、精品课程、公开课</p></div>
      <div class="yl">
        <h1>娱乐</h1>
        <p>音乐会、演唱会、艺术节、电影、卡拉OK</p>
      </div>
      <div class="jk">
        <h1>健康</h1>
        <p>体育馆、健身房、教练服务、运动器材</p>
      </div>
      <div class="cf">
        <h1>财富</h1>
        <p>金融网点、理财产品、贵金属、房产预售</p>
      </div>
    </div>
   </div>
   <div class="right_txt">联系客服</div>
   
<div class="right_con1">
   <div class="jiany">
   <p>邮箱：yudingvip@126.com</p>
<p> 短信：</p>
   </div>
   <div class="jiany">
     <p>Q Q：yudingvip@qq.com</p>
   <p> 微信：</p>
   </div>
</div>
<div class="right_txt">关于商业诚信的约定与举报</div>
<div class="right_con"><a href="＃">
  点此举报员工涉嫌做出不道德或不合法行为的可疑事件>>
</a></div>
