<?php 
echo $this->headScript()->appendFile($this->basePath('js/jquery-validate.min.js'));
$form = $this->form;
$form->prepare();
$save = $this->save;
?>
<?php if ($save == 1):?>
<script>
alert('保存成功！');
</script>
<?php endif;?>
<div class="right_txt">合作原则</div>
    <div class="right_con">
      <p>1.不收录有反动、色情、赌博等不良内容或提供不良内容链接的网站，以及网站名称或内容违反国家有关法规的网站        </p>
      <p>2. 不收录无实用内容的网站，如您的网站正在建设中，尚无完整内容，请不必现在登录，欢迎您在网站建设完成后再来登录        </p>
      <p>3.不收录含有病毒、木马，弹出插件或恶意更改他人电脑设置的网站及有多个弹窗广告的网站        </p>
      <p>4.对挂靠别人的网站下的网站 ( 即没有自己单独域名的网站 ) ，本站将不予收录        </p>
      <p>5.不收录在正常情况下无法正常连接或浏览的网站        </p>
      <p>6.本站保留收录决定权以及在本站网址数据库中相关内容的编辑决定权 </p>
    </div>
    <div class="right_txt">广告投放提交信息</div>
   <div class="right_con1">
   <?php echo $this->form()->openTag($form);?>
     <table width="98%" border="0" cellspacing="0" cellpadding="0">
       <tr>
         <td width="15%">&nbsp;</td>
         <td width="85%">&nbsp;</td>
       </tr>
       <?php 
       $url = $form->get('url');
       ?>
       <tr>
         <td height="30" align="right"><?php echo $url->getOption('label');?>：</td>
         <td height="30"><label for="textfield"></label>
         <?php echo $this->formInput($url);
    echo $this->formElementErrors($url); ?>
    <span id="for_url">例如：http://www.baidu.com</span>
          </td>
       </tr>
       <?php $title = $form->get('title');?>
       <tr>
         <td height="30" align="right"><?php echo $title->getOption('label')?>：</td>
         <td height="30">
         <?php echo $this->formInput($title);
    echo $this->formElementErrors($title); ?>
    <span id="for_title"></span>
         </td>
       </tr>
       <?php $QQ = $form->get('QQ');?>
       <tr>
         <td height="30" align="right"><?php echo $QQ->getOption('label')?>：</td>
         <td height="30">
         <?php echo $this->formInput($QQ);
    echo $this->formElementErrors($QQ); ?>
    <span id="for_QQ"></span>
         </td>
       </tr>
       <?php $email = $form->get('email');?>
       <tr>
         <td height="30" align="right"><p ><?php echo $email->getOption('label')?>：</p></td>
         <td height="30">
         <?php echo $this->formInput($email);
    echo $this->formElementErrors($email); ?>
    <span id="for_email"></span>
         </td>
       </tr>
       <?php $tel = $form->get('tel');?>
       <tr>
         <td height="30" align="right"><p ><?php echo $tel->getOption('label')?>：</p></td>
         <td height="30">
         <?php echo $this->formInput($tel);
    echo $this->formElementErrors($tel); ?>
         </td>
       </tr>
       <?php $position = $form->get('position');?>
       <tr>
         <td height="30" align="right"><p ><?php echo $position->getOption('label')?>：</p></td>
         <td height="30">
         <?php echo $this->formInput($position);
    echo $this->formElementErrors($position); ?>
         </td>
       </tr>
       <?php $buildTime = $form->get('build_time');?>
       <tr>
         <td height="30" align="right"><p ><?php echo $buildTime->getOption('label')?>：</p></td>
         <td height="30">
         <?php echo $this->formInput($buildTime);
    echo $this->formElementErrors($buildTime); ?>
         </td>
       </tr>
       <?php $dailyView = $form->get('dailyView');?>
       <tr>
         <td height="30" align="right"><p ><?php echo $dailyView->getOption('label')?>：</p></td>
         <td height="30">
         <?php echo $this->formInput($dailyView);
    echo $this->formElementErrors($dailyView); ?>
         </td>
       </tr>
       <?php $summary = $form->get('summary');?>
       <tr>
         <td height="65" align="right"><?php echo $summary->getOption('label')?>：</td>
         <td height="75" align="left" valign="middle"><label for="textarea3"></label>
         <?php echo $this->formTextarea($summary);
         echo $this->formElementErrors($summary);
         ?>
          </td>
       </tr>
       <tr>
         <td align="right">&nbsp;</td>
         <td>&nbsp;</td>
       </tr>
       <?php $submit = $form->get('submit');?>
       <tr>
         <td align="right">&nbsp;</td>
         <td>
         <?php echo $this->formSubmit($submit);?>
         &nbsp;</td>
       </tr>
     </table>
     <?php echo $this->form()->closeTag(); ?>
   </div>
<script>
$(function(){
	$('#adv-Apply-form').validate({
		onBlur : true,
		sendForm : true,
		eachValidField : function() {
		},
		description : {
			url : {
				required : '请输入网址',
				pattern : '格式不正确'
			},
			title : {
				required : '请输入网站名称',
			},
			QQ : {
				pattern : '格式不正确',
			},
			email : {
				pattern : '格式不正确',
			}
		},
		valid:function() {
		}
	});
})
</script>