<?php
$this->headScript()->appendFile($this->basePath('js/jquery-ui-1.10.2.custom.min.js'))
->appendFile($this->basePath('js/jquery.cleditor.min.js'));
$this->headLink()->appendStylesheet($this->basePath('styles/jquery-ui-1.10.2.custom.min.css'))
->appendStylesheet($this->basePath('styles/jquery.cleditor.css'));
$form = $this->form;
$msg = $this->flashMessages();
$checkAddLinks = $this->links;
$category = $this->category;
$html = $this->defaultHtml;
?>
<div class="box">
    <div class="box-header">
        <h2><i class="icon-box"></i>加入常用</span></h2>
    	<div class="t_top">
        <p class='t_right'>
        <a class="btn btn-return" href="/nav/items?cid=<?php echo $this->cid?>">
        <i class="icon-plus"></i>返回</a>
        </div>
    </div>
    <div class="box-content">
	   <?php if(!empty($msg['error'])):?>
            <div class="alert alert-error fade in">
            <button class="close" data-dismiss="alert" type="button">×</button>
            <?php foreach($msg['error'] as $v):?>
            <p><?php echo $v;?></p>
            <?php endforeach;?>
            </div>
            <?php endif;?>
            
            <?php if(!empty($msg['success'])):?>
            <div class="alert alert-success fade in">
            <button class="close" data-dismiss="alert" type="button">×</button>
            <?php foreach($msg['success'] as $v):?>
            <p><?php echo $v;?></p>
            <?php endforeach;?>
            </div>
            <?php endif;?>
            <?php if ($checkAddLinks):?>
            <div style="text-align: left;">
            <h6>您将要加入的网址：</h6>
            <div>
            <?php foreach($checkAddLinks as $k=>$v):?>
            <input type="hidden" name="links" value="<?php echo $v['id'];?>" />
            <a href="<?php echo $v['url'];?>"><?php echo $v['title'];?></a>
            <?php endforeach;?>
            </div>
            <div>
                请选择分类：
                <select name="recommendCategory">
<!--                     <option value="2">宅男福利</option> -->
<!--                     <option value="3">生活更方便</option> -->
<!--                     <option value="4">腐女必备</option> -->
<!--                     <option value="5">小清新</option> -->
<!--                     <option value="6">热门微博</option> -->
<!--                     <option value="7">上班族定制</option> -->
                </select>
                <input type="button" name="checkbutton"  value="确定"/>
            </div>
            </div>
            <?php endif;?>
            <br />
            <div class="input-group">
                请选择分类：
                <select  class="input-element select-element" name="recommendCategory">
                    <?php foreach($category as $k=>$v):?>
                    <option value="<?php echo $k;?>" <?php echo $this->cid == $k ? 'selected' : '';?>><?php echo $v;?></option>
               <?php endforeach;?>
                </select>
<!--                 <div class="button-group"><input type="button" name="checkbutton"  value="确定"/></div> -->
            </div>
            <div>
            <textarea class="cleditor" type="text" name="linkHtml" class="input-element"><?php echo $html['html'];?></textarea>
            </div>
            <div class="button-group"><input type="button" value="保存" name="submit" class="button-element"></div>
    </div>
</div>
<script>
$(function() {
	$("input[name='checkbutton']").click(function(){
	    var links = '';
	    $("input[name='links']").each(function(){
	    	links += ','+$(this).val();
		});
		alert(links);
	});
	$("select[name='recommendCategory']").change(function(){
	    var cate = $(this).val();
	    location.href='/nav/addRecommend?cid='+cate;
	});
	$("input[type='button'][name='submit']").click(function(){
	    var cate = $("select[name='recommendCategory']").val();
	    var html = $("textarea[name='linkHtml']").val();
	    $.ajax({
			type:'POST',
			url:'/ajax/saveCommonLinks',
			data:{cate:cate,html:html},
			dataType:'json',
			cache:false,
			async:false,
			success:function(s) {
				if (s.code == 0) {
					alert('保存成功！');
					location.reload;
				}
			}
		});
	});
	$(".cleditor").cleditor({
        width:        600, // width not including margins, borders or padding
        height:       300, // height not including margins, borders or padding
        controls:     // controls to add to the toolbar
                      "bold italic underline strikethrough subscript superscript | font size " +
                      "style | color highlight removeformat | bullets numbering | outdent " +
                      "indent | alignleft center alignright justify | undo redo | " +
                      "rule image link unlink | cut copy paste pastetext | print source",
        colors:       // colors in the color popup
                      "FFF FCC FC9 FF9 FFC 9F9 9FF CFF CCF FCF " +
                      "CCC F66 F96 FF6 FF3 6F9 3FF 6FF 99F F9F " +
                      "BBB F00 F90 FC6 FF0 3F3 6CC 3CF 66C C6C " +
                      "999 C00 F60 FC3 FC0 3C0 0CC 36F 63F C3C " +
                      "666 900 C60 C93 990 090 399 33F 60C 939 " +
                      "333 600 930 963 660 060 366 009 339 636 " +
                      "000 300 630 633 330 030 033 006 309 303",    
        fonts:        // font names in the font popup
                      "Arial,Arial Black,Comic Sans MS,Courier New,Narrow,Garamond," +
                      "Georgia,Impact,Sans Serif,Serif,Tahoma,Trebuchet MS,Verdana",
        sizes:        // sizes in the font size popup
                      "1,2,3,4,5,6,7",
        styles:       // styles in the style popup
                      [["Paragraph", "<p>"], ["Header 1", "<h1>"], ["Header 2", "<h2>"],
                      ["Header 3", "<h3>"],  ["Header 4","<h4>"],  ["Header 5","<h5>"],
                      ["Header 6","<h6>"]],
        useCSS:       false, // use CSS to style HTML when possible (not supported in ie)
        docType:      // Document type contained within the editor
                      '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">',
        docCSSFile:   // CSS file used to style the document contained within the editor
                      "", 
        bodyStyle:    // style to assign to document body contained within the editor
                      "margin:4px; font:10pt Arial,Verdana; cursor:text"
    });
})
</script>