<?php
$this->headScript()->appendFile($this->basePath('js/jquery-ui-1.10.2.custom.min.js'))
->appendFile($this->basePath('js/jquery.cleditor.min.js'));
$this->headLink()->appendStylesheet($this->basePath('styles/jquery-ui-1.10.2.custom.min.css'))
->appendStylesheet($this->basePath('styles/jquery.cleditor.css'));
$form = $this->form;
$msg = $this->flashMessages();
?>
<div class="box">
    <div class="box-header">
        <h2><i class="icon-box"></i>导航分类<span style="float: right;"><a href="/nav/items?cid=<?php echo $this->cid?>">返回</a></span></h2>
    </div>
    <div class="box-content">
	   <?php if(!empty($msg['error'])):?>
            <div class="alert alert-error fade in">
            <button class="close" data-dismiss="alert" type="button">×</button>
            <?php foreach($msg['error'] as $v):?>
            <p><?php echo $v;?></p>
            <?php endforeach;?>
            </div>
            <?php endif;?>
            
            <?php if(!empty($msg['success'])):?>
            <div class="alert alert-success fade in">
            <button class="close" data-dismiss="alert" type="button">×</button>
            <?php foreach($msg['success'] as $v):?>
            <p><?php echo $v;?></p>
            <?php endforeach;?>
            </div>
            <?php endif;?>
        <form class="box-form" action="<?php echo $this->url('backend' , array('controller' => 'nav' , 'action' => 'addItem'))?>"
              method="post" enctype="multipart/form-data">
            <fieldset>
            	<?php echo $this->formHidden($form->get('id'))?>
                <?php echo $this->formText($form->get('title'))?>
                <?php echo $this->formText($form->get('url'))?>
                <?php echo $this->formSelect($form->get('target'))?>
                <?php echo $this->formSelect($form->get('category'))?>
                <?php echo $this->formSelect($form->get('province'))?>
                <?php echo $this->formSelect($form->get('city'))?>
                <?php echo $this->formSelect($form->get('isShow'))?>
                <?php echo $this->formText($form->get('order'))?>
                
                <?php echo $this->formSubmit($form->get('submit') , '提交')?>
            </fieldset>
        </form>
    </div>
</div>
<script>
$(function() {
	$("input[name='url']").focusout(function() {
		var url = $.trim($(this).val());
		if (url != '' && url.indexOf('http://') == -1) {
			$(this).val('http://'+url);
		}
	});
	$("select[name='province']").change(function() {
		$v = $(this).val();
		if ($v == 0) {
			$("select[name='city']").html('');
		} else {
			$.ajax({
				type: "POST",
				url : "/ajax/region?p="+$v,
				dataType :"json",
				success: function(s){
					var html = '<option value="0" >===请选择城市===</option>';
					for(var o in s) {
						html += "<option value='"+s[o].region_id+"'>"+s[o].region_name+"</option>";
					}
					$("select[name='city']").html(html);
				}
			});
		}
	});
})
</script>