<?php
$this->headScript()->appendFile($this->basePath('js/jquery-ui-1.10.2.custom.min.js'));
$this->headLink()->appendStylesheet($this->basePath('styles/jquery-ui-1.10.2.custom.min.css'));
$msg = $this->flashMessages();?>
<div class="box">
    <div class="box-header">
        <h2><i class="icon-box"></i><?php echo isset($this->cateInfo->name) ? $this->cateInfo->name : '所有';?>分类导航列表<span style="float: right;"><a href="/nav/category">返回</a></span>
        </h2>
    </div>
    <div class="box-content">
    <?php if(!empty($msg['error'])):?>
            <div class="alert alert-error fade in">
            <button class="close" data-dismiss="alert" type="button">×</button>
            <?php foreach($msg['error'] as $v):?>
            <p><?php echo $v;?></p>
            <?php endforeach;?>
            </div>
            <?php endif;?>
            
            <?php if(!empty($msg['success'])):?>
            <div class="alert alert-success fade in">
            <button class="close" data-dismiss="alert" type="button">×</button>
            <?php foreach($msg['success'] as $v):?>
            <p><?php echo $v;?></p>
            <?php endforeach;?>
            </div>
            <?php endif;?>
        <p><a class="btn btn-success" href="<?php echo $this->url('backend' 
            , array('controller' => 'nav' , 'action' => 'addItem'));?>">
        <i class="icon-plus"></i>新增地址</a></p>
         <div class="t_top">
        	<div class="t_inline">
        <form class="form-inline" action="<?php echo $this->url('backend', array('controller' 
            => 'nav', 'action' => 'items')); ?>" method="get">
                <div class="input-group">
                    <label>搜索标题</label>
                    <input class="input-element span3" name="title" type="text">
                    <label>搜索分类</label>
                    <select name="cid">
                    <?php foreach ($this->category as $k=>$v):?>
                    	<option value="<?php echo $k;?>" <?php echo $this->cid==$k ? 'selected=selected' : '';?>><?php echo $v;?></option>
                    <?php endforeach;?>
                    </select>
                    <!-- <input type="hidden" name="cid" value="<?php echo $this->cateInfo->id;?>" /> -->
                <button class="button-element" type="submit">搜索</button>
                </div>
        </form>
        	</div>
        	<div class="t_right">
        	<a class="btn btn-edit" href="javascript:;" _href="<?php echo $this->url('backend', array('controller' 
                                => 'nav', 'action' => 'addItem')) ?>?cid=<?php echo $this->cid;?>&id=">
                                <i class="icon-edit"></i>编辑
                            </a>&nbsp;&nbsp;
                            <a class="btn btn-delete" href="javascript:;" _href="<?php echo $this->url('backend', array('controller' 
                                => 'nav', 'action' => 'deleteItem')) ?>?cid=<?php echo $this->cid;?>&id=" onClick="diyConfirm('删除' , $(this).attr('href'), this);return false;"><i class="icon-delete"></i>删除
                            </a>
        	</div>
        </div>
        <table class="table">
            <thead>
                <tr class="row">
                	<th>选择</th>
                    <th>编号</th>
                    <th>
                    <?php if (isset($this->order['title'])):?>
                    <?php $name = $this->order['title'];?>
                    <a href="<?php echo $name['href'];?>">链接标题<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	链接标题
                    <?php endif;?>
                    	</th>
                    <th>链接地址</th>
                    <th>分类</th>
                    <th>
                    <?php if (isset($this->order['isShow'])):?>
                    <?php $name = $this->order['isShow'];?>
                    <a href="<?php echo $name['href'];?>">是否显示<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	是否显示
                    <?php endif;?>
                    </th>
                    <th>
                    <?php if (isset($this->order['order'])):?>
                    <?php $name = $this->order['order'];?>
                    <a href="<?php echo $name['href'];?>">排序<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	排序
                    <?php endif;?>
                    </th>
                    <th>
                    <?php if (isset($this->order['addTime'])):?>
                    <?php $name = $this->order['addTime'];?>
                    <a href="<?php echo $name['href'];?>">添加时间<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	添加时间
                    <?php endif;?>
                    </th>
                </tr>
            </thead>
            <tbody>
                <?php $startNumber = $this->startNumber;foreach ($this->lists as $nav): ?>
                    <tr class="row">
                    	<td><input type="radio" name="select" value="<?php echo $nav['id']; ?>" /></td>
                        <td><?php echo $startNumber++;?></td>
                        <td><?php echo $nav['title']; ?></td>
                        <td><a href="<?php echo $nav['url']; ?>" target="_blank" title="<?php echo $nav['title'];?>"><?php echo $nav['url']; ?></a></td>
                        <td><?php echo $nav['categoryName']; ?></td>
                        <td><?php echo $nav['isShow'] ? '显示' : '不显示'; ?></td>
                        <td><?php echo $nav['order']; ?></td>
                        <td><?php echo $nav['addTime']; ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
        <?php echo $this->paginationControl($this->paginaction,'Sliding','layout/pagination' , array('link' 
            => $this->url('backend' , array('controller' => 'nav' , 'action' => 'items')).'?'.$this->query));?>
    </div>
</div>