<?php
$this->headScript()->appendFile($this->basePath('js/jquery-ui-1.10.2.custom.min.js'));
$this->headLink()->appendStylesheet($this->basePath('styles/jquery-ui-1.10.2.custom.min.css'));
$msg = $this->flashMessages();?>
<div class="box">
    <div class="box-header">
        <h2><i class="icon-box"></i><?php echo $this->cateInfo->name;?>分类导航列表<span style="float: right;"><a href="/nav/category">返回</a></span>
        </h2>
    </div>
    <div class="box-content">
    <?php if(!empty($msg['error'])):?>
            <div class="alert alert-error fade in">
            <button class="close" data-dismiss="alert" type="button">×</button>
            <?php foreach($msg['error'] as $v):?>
            <p><?php echo $v;?></p>
            <?php endforeach;?>
            </div>
            <?php endif;?>
            
            <?php if(!empty($msg['success'])):?>
            <div class="alert alert-success fade in">
            <button class="close" data-dismiss="alert" type="button">×</button>
            <?php foreach($msg['success'] as $v):?>
            <p><?php echo $v;?></p>
            <?php endforeach;?>
            </div>
            <?php endif;?>
        <p><a class="btn btn-success" href="<?php echo $this->url('backend' 
            , array('controller' => 'nav' , 'action' => 'addItem')).'?cid='.$this->cateInfo->id;?>">
        <i class="icon-plus"></i>新增地址</a></p>
        <form class="form-inline" action="<?php echo $this->url('backend', array('controller' 
            => 'nav', 'action' => 'items')); ?>" method="get">
                <div class="input-group">
                    <label>搜索标题</label>
                    <input class="input-element span3" name="title" type="text">
                    <input type="hidden" name="cid" value="<?php echo $this->cateInfo->id;?>" />
                <button class="button-element" type="submit">搜索</button>
                </div>
        </form>
        <table class="table">
            <thead>
                <tr class="row">
                    <th>ID</th>
                    <th>链接标题</th>
                    <th>链接地址</th>
                    <th>分类</th>
                    <th>是否显示</th>
                    <th>排序</th>
                    <th>添加时间</th>
                    <th>操作</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->lists as $nav): ?>
                    <tr class="row">
                        <td><?php echo $nav['id']; ?></td>
                        <td><?php echo $nav['title']; ?></td>
                        <td><?php echo $nav['url']; ?></td>
                        <td><?php echo $nav['categoryName']; ?></td>
                        <td><?php echo $nav['isShow'] ? '显示' : '不显示'; ?></td>
                        <td><?php echo $nav['order']; ?></td>
                        <td><?php echo $nav['addTime']; ?></td>
                        <td>
                            <a class="btn btn-edit" href="<?php echo $this->url('backend', array('controller' 
                                => 'nav', 'action' => 'addItem')) ?>?cid=<?php echo $nav['category'];?>&id=<?php echo $nav['id']; ?>">
                                <i class="icon-edit"></i>编辑
                            </a>&nbsp;&nbsp;
                            <a class="btn btn-delete" href="<?php echo $this->url('backend', array('controller' 
                                => 'nav', 'action' => 'deleteItem')) ?>?cid=<?php echo $nav['category'];?>&id=<?php echo $nav['id']; ?>" onClick="diyConfirm('删除' , $(this).attr('href'));return false;"><i class="icon-delete"></i>删除
                            </a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
        <?php echo $this->paginationControl($this->paginaction,'Sliding','layout/pagination' , array('link' 
            => $this->url('backend' , array('controller' => 'nav' , 'action' => 'items')).'?cid='.$this->cateInfo->id));?>
    </div>
</div>