<?php
$this->headScript()->appendFile($this->basePath('js/jquery-ui-1.10.2.custom.min.js'))
					->appendFile($this->basePath('js/jquery.ajaxfileupload.js'));
$this->headLink()->appendStylesheet($this->basePath('styles/jquery-ui-1.10.2.custom.min.css'));
$msg = $this->flashMessages();?>
<div class="box">
    <div class="box-header">
        <!-- <h2><i class="icon-box"></i><?php echo isset($this->cateInfo->name) ? $this->cateInfo->name : '所有';?>分类导航列表</span> -->
        </h2>
        <div class="t_top">
        	<div class="t_inline">
        <form class="form-inline" action="<?php echo $this->url('backend', array('controller' 
            => 'nav', 'action' => 'items')); ?>" method="get">
                <div class="input-group">
                	<label>分类</label>
                    <select name="cid">
                    <?php foreach ($this->category as $k=>$v):?>
                    	<option value="<?php echo $k;?>" <?php echo $this->cid==$k ? 'selected=selected' : '';?>><?php echo $v;?></option>
                    <?php endforeach;?>
                    </select>
                    <input autocomplete="off" class="input-element span3" name="title" type="text">
                    <!-- <input type="hidden" name="cid" value="<?php echo $this->cateInfo->id;?>" /> -->
                <button class="button-element" type="submit">搜索</button>
                </div>
        </form>
        	</div>
        	<div class="t_import input-group">
        		<button class="button-element" type="button" name="export_button" value="导出" q="<?php echo $this->url('backend' , array('controller' => 'nav' , 'action' => 'items')).'?'.$this->query;?>" >导出</button>
        	</div>
        	<div class="t_import" style="padding-left:6px;">
        	<a href="/templates/navigation_templates.xlsx" >模板</a>
        		<input type="file" name="srcFile" value="" id="srcFile" style="width:140px;"/>
        		<button class="button-element" type="button" name="import_button" value="导入">导入</button>
        	</div>
        	<p class='t_right'>
        	<!-- <a class="btn btn-return" href="<?php echo $this->url('backend' 
            , array('controller' => 'nav' , 'action' => 'category'))?>">
        <i class="icon-plus"></i>返回</a> -->
        	<a class="btn btn-success" href="<?php echo $this->url('backend' 
            , array('controller' => 'nav' , 'action' => 'addItem'));?>">
        <i class="icon-plus"></i>新增</a>
        <a class="btn btn-edit" href="javascript:;" _href="<?php echo $this->url('backend', array('controller' 
                                => 'nav', 'action' => 'addItem')) ?>?cid=<?php echo $this->cid;?>&id=">
                                <i class="icon-edit"></i>编辑
                            </a>
                            <a class="btn btn-delete" href="javascript:;" _href="<?php echo $this->url('backend', array('controller' 
                                => 'nav', 'action' => 'deleteItem')) ?>?cid=<?php echo $this->cid;?>&id=" onClick="diyConfirm('删除' , $(this).attr('href'), this);return false;"><i class="icon-delete"></i>删除
                            </a>
        </p>
        </div>
    </div>
    <div class="box-content">
    <?php if(!empty($msg['error'])):?>
            <div class="alert alert-error fade in">
            <button class="close" data-dismiss="alert" type="button">×</button>
            <?php foreach($msg['error'] as $v):?>
            <p><?php echo $v;?></p>
            <?php endforeach;?>
            </div>
            <?php endif;?>
            
            <?php if(!empty($msg['success'])):?>
            <div class="alert alert-success fade in">
            <button class="close" data-dismiss="alert" type="button">×</button>
            <?php foreach($msg['success'] as $v):?>
            <p><?php echo $v;?></p>
            <?php endforeach;?>
            </div>
            <?php endif;?>
        <table class="table" id="table1">
            <thead>
                <tr class="row">
                	<th>全选<input type="checkbox" name="select_all" value="all"/></th>
                    <th>编号</th>
                    <th key="title" editable="true">
                    <?php if (isset($this->order['title'])):?>
                    <?php $name = $this->order['title'];?>
                    <a href="<?php echo $name['href'];?>">标题<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	标题
                    <?php endif;?>
                    	</th>
                    <th  key="url" editable="true">
                    <?php if (isset($this->order['url'])):?>
                    <?php $name = $this->order['url'];?>
                    <a href="<?php echo $name['href'];?>">地址<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	地址
                    <?php endif;?>
                    </th>
                    <th>分类</th>
                    <th key="isShow" editable="true">
                    <?php if (isset($this->order['isShow'])):?>
                    <?php $name = $this->order['isShow'];?>
                    <a href="<?php echo $name['href'];?>">是否显示<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	是否显示
                    <?php endif;?>
                    </th>
                    <th  key="order" editable="true">
                    <?php if (isset($this->order['order'])):?>
                    <?php $name = $this->order['order'];?>
                    <a href="<?php echo $name['href'];?>">排序<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	排序
                    <?php endif;?>
                    </th>
                    <th>区域</th>
                    <th>
                    <?php if (isset($this->order['user_name'])):?>
                    <?php $name = $this->order['updateTime'];?>
                    <a href="<?php echo $name['href'];?>">推荐人<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	推荐人
                    <?php endif;?>
                    </th>
                    <th>
                    <?php if (isset($this->order['email'])):?>
                    <?php $name = $this->order['email'];?>
                    <a href="<?php echo $name['href'];?>">邮箱<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	邮箱
                    <?php endif;?>
                    </th>
                    <th>
                    <?php if (isset($this->order['mobile'])):?>
                    <?php $name = $this->order['mobile'];?>
                    <a href="<?php echo $name['href'];?>">手机<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	手机
                    <?php endif;?>
                    </th>
                    <th>
                    <?php if (isset($this->order['updateTime'])):?>
                    <?php $name = $this->order['updateTime'];?>
                    <a href="<?php echo $name['href'];?>">更新时间<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	更新时间
                    <?php endif;?>
                    </th>
                    <th>
                    <?php if (isset($this->order['updateUser'])):?>
                    <?php $name = $this->order['updateUser'];?>
                    <a href="<?php echo $name['href'];?>">更新人<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	更新人
                    <?php endif;?>
                    </th>
                </tr>
            </thead>
            <tbody>
                <?php $startNumber = $this->startNumber;foreach ($this->lists as $nav): ?>
                    <tr class="row" key="id" primary_value="<?php echo $nav['id']; ?>">
                    	<td width="60"><input type="checkbox" name="select" value="<?php echo $nav['id']; ?>" data-key="链接标题" data-value="<?php echo $nav['title']; ?>" /></td>
                        <td><?php echo $startNumber++;?></td>
                        <td key="title" editable="true"><?php echo $nav['title']; ?></td>
                        <td key="url" editable="true"><a href="<?php echo $nav['url']; ?>" target="_blank" title="<?php echo $nav['title'];?>"><?php echo $nav['url']; ?></a></td>
                        <td><?php echo $nav['categoryName']; ?></td>
                        <td key="isShow" editable="true"><?php echo $nav['isShow'] ? '显示' : '不显示'; ?></td>
                        <td key="order" editable="true"><?php echo $nav['order']; ?></td>
                        <td><?php echo $nav['area'];?></td>
                        <td><?php echo $nav['user_name']; ?></td>
                        <td><?php echo $nav['email']; ?></td>
                        <td><?php echo $nav['mobile']; ?></td>
                        <td><?php echo $nav['updateTime']; ?></td>
                        <td><?php echo $nav['updateUser']; ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
        <?php echo $this->paginationControl($this->paginaction,'Sliding','layout/pagination' , array('link' 
            => $this->url('backend' , array('controller' => 'nav' , 'action' => 'items')).'?'.$this->query));?>
    </div>
</div>
<script type="text/javascript">
<!--
var productEditableParam={
		'postUrl':'/index/updateColumn',
		'primary_key':'id',
		'table':'LinkTable',
		'isShow':{
			type:'radio',
	        group:{
	            1:'显示',
	            0:'不显示'
	        }
		},
		'order':{
			type:'text',
			reg: /^\d+$/,
			tip:'只能为数字!'
		},
		'title':{
			type:'text'
		},
		'url':{
			type:'text'
		}
	};
var options={
		tableID:'table1',
		editableParam:productEditableParam
}
new Editable(options,$("#table1"));
$(function() {
	$("button[name='export_button']").click(function() {
		var q = $(this).attr('q');
		location.href=q+'&act=down';
	});
	$("button[name='import_button']").click(function() {
		var img_value = $("#srcFile").val();
		if (img_value == '') {
			alert('请选择文件');
		} else {
			var url = "/nav/upload";
			$.ajaxFileUpload
			(
				{
					url:url,
					secureuri:false,
					fileElementId:'srcFile',
					dataType: 'json',
					success: function (data, status)
					{
						if (data.code == 0) {
							alert('已成功上传'+data.msg+'条记录');
						}
					},
					error: function (data, status, e)
					{
						alert('上传时发生错误');
					}
				}
			)
		}
	});
	$("select[name='cid']").change(function(){
		$("button.button-element[type='submit']").click();
	});
})
//-->
</script>