<div class="box">
    <div class="box-header">
        <h2><i class="icon-box"></i>用户列表</h2>
    </div>
    <div class="box-content">
        <p><a class="btn btn-success" href="<?php echo $this->url('backend' 
            , array('controller' => 'user' , 'action' => 'save'))?>">
        <i class="icon-plus"></i>新增用户</a>
         <a class="btn btn-edit" href="javascript:;" _href="<?php echo $this->url('backend', array('controller' 
                                => 'user', 'action' => 'save')) ?>?id=">
                                <i class="icon-edit"></i>编辑
                            </a>
                            <a class="btn btn-delete" href="javascript:;" _href="<?php echo $this->url('backend', array('controller' 
                                => 'user', 'action' => 'delete')) ?>?id=" onClick="diyConfirm('删除' , $(this).attr('href'), this);return false;"><i class="icon-delete"></i>删除
                            </a></p>
        <div class="t_top">
        <div class="t_inline">
        <form class="form-inline" action="<?php echo $this->url('backend', array('controller' 
            => 'user', 'action' => 'index')); ?>" method="get">
                <div class="input-group">
                    <label>搜索用户</label>
                    <input class="input-element span3" name="username" type="text">
                    
                <button class="button-element" type="submit">搜索</button>
                </div>
        </form>
        </div>
    	<div class="t_right">
        	
        	</div>
    </div>
        <table class="table">
            <thead>
                <tr class="row">
                	<th>选择</th>
                    <th>用户名</th>
                    <th>角色</th>
                    <th>最后修改时间</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->paginaction as $user): ?>
                    <tr class="row">
                    	<td><input type="checkbox" name="select" value="<?php echo $user->ID; ?>"/></td>
                        <td><?php echo $user->UserName; ?></td>
                        <td><?php echo $user->Role; ?></td>
                        <td><?php echo $user->LastUpdate; ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
        <?php echo $this->paginationControl($this->paginaction,'Sliding','layout/pagination' , array('link' 
            => $this->url('backend' , array('controller' => 'user' , 'action' => 'index'))));?>
    </div>
</div>