<?php 
$this->headScript()->appendFile($this->basePath('js/jquery-validate.min.js'));
$user = $this->user;
$msg = $this->flashMessages();
?>
<div class="right">
    <div class="r_t">
    <h1>收货地址</h1>
    <h2><span class="red">* </span>表示该项必填</h2></div>
    <div class="r_c">
       <div class="shouhuodizhi">
       <?php if(!empty($msg['error'])):?>
            <div class="alert alert-error fade in">
            <button class="close" data-dismiss="alert" type="button">×</button>
            <?php foreach($msg['error'] as $v):?>
            <p><?php echo $v;?></p>
            <?php endforeach;?>
            </div>
            <?php endif;?>
            
            <?php if(!empty($msg['success'])):?>
            <div class="alert alert-success fade in">
            <button class="close" data-dismiss="alert" type="button">×</button>
            <?php foreach($msg['success'] as $v):?>
            <p><?php echo $v;?></p>
            <?php endforeach;?>
            </div>
            <?php endif;?>
      	<span id="show_addr" style="height:513px; display:block;">
      	
      	</span>
      <div class="sh_t">已保存的有效地址</div>
      <span id="hasAddr">
      &nbsp;
      </span>
<div class="sh_f">最多保存20个有效地址</div>
      </div>
    </div>
 </div>
 <script>
$(function(){
	var url = "/member/showAddress";
	Ajax.call(url, '', function(s){
		$("#show_addr").html(s);
	}, 'POST', '');
	var hasUrl = '/member/addressList';
	Ajax.call(hasUrl, '', function(s){
		$("#hasAddr").html(s);
	}, 'POST', '');
})
 </script>