<?php $msg = $this->flashMessages();$user = $this->user;?>
<div class="pas_warp" id="pas_warp_content">
<div class="con" style="padding-left:0;"><br />
    <p> <span class="dd_yse"><img src="/images/FrontEnd/cg_yes.jpg" width="35" height="37" /></span><span class="cheng">恭喜！</span> ，邮箱<?php echo $user->Email;?>验证成功！</p>
    <p>　　　　您的邮箱                             <span class="cheng"><?php echo $user->Email;?></span> 可以作为登录名，<span class="lanse">用于<a href="/login">登录</a></span>。</p>
</div>
</div>  
  