<?php
$msg = $this->flashMessages();
?>
<?php if (isset($this->user)):?>
<?php $user = $this->user;?>
<div class="pas_warp">
<div class="weiz">找回密码</div>

<div class="liuc"><img src="/images/FrontEnd/psd_lc3.jpg" width="905" height="86" /></div>

<div class="pas_con">
<form name="reset_form" id="reset_form" action="" method="post">
<ul class="input_test1">
<li>
<label for="inp_name">账户名：</label>
  <h2><?php $str = explode('@', $user->Email); echo substr($str[0], 0, 2),'***','@',$str[1];?></h2>
</li>
<li>
<label for="inp_name">新的登录密码：</label>
  <p><input name="password"  data-trim="true" data-pattern="^.{6,16}$" maxlength="16" data-validate="pwd" data-describedby="for_password" data-description="password" data-required="true" type="password" class="input_out" id="in_name1" onfocus="this.className='input_on';this.onmouseout=''" onblur="this.className='input_off';this.onmouseout=function(){this.className='input_out'};" onmousemove="this.className='input_move'" onmouseout="this.className='input_out'" /></p>
  <span id="for_password"><h1><a href="#">如何设置安全密码？</a></h1></span>
</li>
<li class="suoj">必须是6-20个英文字母.数字或符号，不能是纯数字或字母</li>
<li>
<label for="inp_name">确认新的登录密码：</label>
  <p><input name="repassword"  data-trim="true" data-pattern="^.{6,16}$" maxlength="16"  data-conditional="confirm same" data-describedby="for_repassword" data-description="repassword" data-required="true" type="password" class="input_out" id="in_name2" onfocus="this.className='input_on';this.onmouseout=''" onblur="this.className='input_off';this.onmouseout=function(){this.className='input_out'};" onmousemove="this.className='input_move'" onmouseout="this.className='input_out'" /></p>
<span id="for_repassword"></span>
</li>
<li class="btn"><a href="javascript:;"><img src="/images/FrontEnd/btn_qd.jpg" height="42" id="submit_btn" style="cursor:pointer;"/></a></li>
</ul>
</form>
</div>
</div>
<script type="text/javascript">
$('#reset_form').validate({
	onBlur : true,
	sendForm : true,
	eachValidField : function() {
		if ($(this).attr('name') != 'validCode') {
			$(this).parents('p').next('span').html('<img src="/images/FrontEnd/yes.jpg" width="25" height="26" />');
		}
	},
	eachInvalidField : function() {
// 		if ($(this).attr('name') = 'repassword') {
// 			if (!(/^[a-zA-Z]+$/.test($(this).val()) || /^[0-9]+$/.test($(this).val()))) {
// 				$("for_repassword").html('<span><img src="/images/FrontEnd/no.jpg" width="24" height="24" /></span><h1>两次密码输入不一致</h1>');
// 			}
// 		}
	},
	description : {
		password : {
			required : '<span><img src="/images/FrontEnd/no.jpg" width="24" height="24" /></span><h1>不能为空</h1>',
			pattern : '<span><img src="/images/FrontEnd/no.jpg" width="24" height="24" /></span><h1>请输入6到16位密码</h1>',
			conditional : '<span><img src="/images/FrontEnd/no.jpg" width="24" height="24" /></span><h1>不能是纯数字或字母</h1>'
		},
		repassword : {
			required : '<span><img src="/images/FrontEnd/no.jpg" width="24" height="24" /></span><h1>不能为空</h1>',
			pattern : '<span><img src="/images/FrontEnd/no.jpg" width="24" height="24" /></span><h1>请输入6到16位密码</h1>',
			conditional : {
				confirm : '<span><img src="/images/FrontEnd/no.jpg" width="24" height="24" /></span><h1>不能是纯数字或字母</h1>',
				same : '<span><img src="/images/FrontEnd/no.jpg" width="24" height="24" /></span><h1>两次输入的密码不一致</h1>'
			}
		}
	},
	conditional : {
		confirm : function() {
			var reg1 = /^[a-zA-Z]+$/;
        	var reg2 = /^[0-9]+$/;
        	var value = $(this).val();
        	if (reg1.test(value)) {
				return false;
            }
            if (reg2.test(value)) {
				return false;
            }
            return true;
		},
		same : function() {
			return $(this).val() == $('input[name="password"]').val();
		}
	},
	valid:function() {
	}
});
jQuery.validateExtend({
    pwd : {
        required : true,
        conditional : function(value) {
        	var reg1 = /^[a-zA-Z]+$/;
        	var reg2 = /^[0-9]+$/;
        	if (reg1.test(value)) {
				return false;
            }
            if (reg2.test(value)) {
				return false;
            }
            return true;
        }
    }
//     ,
//     pwd : {
// 		required : true,
// 		pattern : /^.{6,16}$/,
// 		conditional : function(value) {
// 			return value == $("input[name='password']").val();
// 		}
//     }
});
$(function(){
	$("#submit_btn").click(function(){
		$("#reset_form").submit();
	});
})
</script>
<?php else:?>
<div class="cg">
<div class="pas_warp">
 <div class="cg_1">
 <span class="cgimg"><img src="/images/FrontEnd/yes_1.jpg" width="46" height="48" /></span>邮箱验证成功，请继续操作 </div>
 </div>
</div>
<div class="fanh"><div class="pas_warp">
  <div class="fanh_t"><a href="<?php echo $this->url,'&s=next';?>">继续重置登录密码</a></div></div></div>
<?php endif;?>