<?php 
$this->headScript()->appendFile($this->basePath('js/jquery-validate.min.js'));
$user = $this->user;
$msg = $this->flashMessages();
?>
<div class="right">
    <div class="r_t">
    <h1>邮箱认证</h1>
    <h2>&nbsp;</h2></div>
    <div class="r_c">
       <div class="shouhuodizhi">
       <?php if(!empty($msg['error'])):?>
            <div class="alert alert-error fade in">
            <button class="close" data-dismiss="alert" type="button">×</button>
            <?php foreach($msg['error'] as $v):?>
            <p><?php echo $v;?></p>
            <?php endforeach;?>
            </div>
            <?php endif;?>
            
            <?php if(!empty($msg['success'])):?>
            <div class="alert alert-success fade in">
            <button class="close" data-dismiss="alert" type="button">×</button>
            <?php foreach($msg['success'] as $v):?>
            <p><?php echo $v;?></p>
            <?php endforeach;?>
            </div>
            <?php endif;?>
        <form id="chkEmailForm" method="post" action="">
       <div class="mail_ts">
       <h1>温馨提示;</h1>
       <p>1.输入新邮箱地址和验证码后，请点击"提交"。
         </p>
       <p>2.系统会发送确认邮件到您填写的邮箱中，您必须在24小时之内登陆邮箱完成后续认证步骤。         </p>
       <p>3.新邮箱地址认证成功后，原认证邮箱地址将会被撤销。</p>
       <p> 4.通过已认证的邮箱可找回登陆密码，进一步提高帐户安全性。 </p>
       </div>
       <form id="chkEmailForm" method="post" action="">
       <div class="mail_table"><table width="100%" border="0" cellspacing="0" cellpadding="0">
        <tr>
          <td width="88" height="38">&nbsp;</td>
          <td width="100" height="38" align="right">当前邮箱地址：</td>
          <td height="30" colspan="3"><label for="textfield3"></label>
            <?php echo $this->user->Email;?></td>
        </tr>
        <tr>
          <td height="38">&nbsp;</td>
          <td height="38" align="right">新邮箱地址：</td>
          <td height="38" colspan="3"><input data-required='true' data-pattern='^[_a-z0-9-]+(\.[_a-z0-9-]+)*@[a-z0-9-]+(\.[a-z0-9-]+)*$' data-describedby='for_toEmail' data-description='toEmail' type="text" name="toEmail" id="textfield3" />
          <span class='red' id='for_toEmail'></span>
          </td>
        </tr>
        <tr>
          <td height="30">&nbsp;</td>
          <td height="30" align="right">&nbsp;</td>
          <td height="30" colspan="3" id="huise">（填写正确邮箱地址）</td>
        </tr>
        <tr>
          <td height="38">&nbsp;</td>
          <td height="38" align="right">验证码：</td>
          <td width="115" height="38"><input data-required='true' data-describedby='for_valicate_code' data-description='valicate_code' name="valicate_code" type="text" id="textfield4" size="15" /><span class='red' id='for_valicate_code'></span></td>
          <td width="69"><img id="pass-captcha" src="/member/chkCaptcha?k=chk-email-captcha" alt="" width="55" height="21" /></td>
          <td width="356" class="chengse"><a href="javascript:;" id="refresh_captcha">看不清，换一个</a></td>
          </tr>
        <tr>
          <td height="38">&nbsp;</td>
          <td height="38" align="right">&nbsp;</td>
          <td height="38" colspan="3"><input name="btn5" type="submit" id="btn5" value="提交" /></td>
        </tr>
        </table></div>
        </form>
      </div>
    </div>
 </div>
  <script>
$("#chkEmailForm").validate({
	onBlur : true,
	description:{
		toEmail:{
			required:'请输入新邮箱地址',
			pattern:'邮箱格式不正确'
		},
		valicate_code:{
			required:'请输入验证码'
		}
	}
});
$(function(){
	$("#refresh_captcha").click(function(){
		$("#pass-captcha").attr('src', '/member/chkCaptcha?k=chk-email-captcha&t='+Math.random());
	});
})
 </script>