<div class="right">
    <div class="r_t">
    <h1>邮箱认证</h1>
    <h2>&nbsp;</h2></div>
    <div class="r_c">
       <div class="shouhuodizhi">
       <div class="mail_ts">
       <h1>温馨提示;</h1>
       <p>1.输入新邮箱地址和验证码后，请点击"提交"。
         </p>
       <p>2.系统会发送确认邮件到您填写的邮箱中，您必须在24小时之内登陆邮箱完成后续认证步骤。         </p>
       <p>3.新邮箱地址认证成功后，原认证邮箱地址将会被撤销。</p>
       <p> 4.通过已认证的邮箱可找回登陆密码，进一步提高帐户安全性。 </p>
       </div>
       <div class="mail_table"><table width="100%" border="0" cellspacing="0" cellpadding="0">
        <tr>
          <td width="88" height="38">&nbsp;</td>
          <td width="100" height="38" align="right">当前邮箱地址：</td>
          <td height="30" colspan="3"><label for="textfield3"></label>
            quke911@126.com</td>
        </tr>
        <tr>
          <td height="38">&nbsp;</td>
          <td height="38" align="right">新邮箱地址：</td>
          <td height="38" colspan="3"><input type="text" name="textfield2" id="textfield3" /></td>
        </tr>
        <tr>
          <td height="30">&nbsp;</td>
          <td height="30" align="right">&nbsp;</td>
          <td height="30" colspan="3" id="huise">（填写正确邮箱地址）</td>
        </tr>
        <tr>
          <td height="38">&nbsp;</td>
          <td height="38" align="right">验证码：</td>
          <td width="115" height="38"><input name="textfield4" type="text" id="textfield4" size="15" /></td>
          <td width="69"><img src="images/yzm.jpg" alt="" width="55" height="21" /></td>
          <td width="356" class="chengse"><a href="#">看不清，换一个</a></td>
          </tr>
        <tr>
          <td height="38">&nbsp;</td>
          <td height="38" align="right">&nbsp;</td>
          <td height="38" colspan="3"><input name="btn5" type="submit" id="btn5" value="提交" /></td>
        </tr>
        </table></div>
      </div>
    </div>
 </div>