<?php
$form = $this->form;
$msg = $this->flashMessages();
?>
<div class="pas_warp" id="pas_warp_content">
<?php if (isset($this->memberInfo)):?>
<?php $member = $this->memberInfo;?>
<?php if (!empty($member)):?>
<div class="weiz_1">您正在为<span class="cheng"><?php echo $member->UserName?><?php if ($member->Email):?>（<?php $str = explode('@', $member->Email); echo substr($str[0], 0, 2),'***','@',$str[1];?>）<?php endif;?></span>帐户重置登录密码，请选择找回方式：</div>
<?php if ($member->Email):?>
<div class="con_1"><span class="c_1"><img src="/images/FrontEnd/paspic1.jpg" width="51" height="38" /></span><span class="tit">通过电子邮箱</span><span class="c_2"><img src="/images/FrontEnd/paspic2.jpg" width="47" height="22" /></span><span class="c_3"><img src="/images/FrontEnd/btn_lk.jpg" width="129" height="42" id="getByEmailBtn" style="cursor:pointer;"/></span></div>
<?php endif;?>
<div class="con_2">
  <span class="c_1"><img src="/images/FrontEnd/paspic3.jpg" width="33" height="63" /></span><span class="tit">通过人工服务<br /><span class="tit12">填写申请单，上传身份证件图片，等待审核结果</span></span>
  <span class="c_3"><img src="/images/FrontEnd/btn_lk.jpg" width="129" height="42" /></span>
</div>
<script type="text/javascript">
var int;
var userId = <?php echo $member->UserID;?>;
$(function(){
	$("#getByEmailBtn").click(function(){
			sendValidEmail(0);
	});
})
var seconds = 50;
function showtime() {
	if (seconds < 0) {
		clearInterval(int);
		$("#reSE").html("<a href='javascript:;' onclick='sendValidEmail(1)'>重新发送</a>");
	} else {
		$("#limitSecond").html(seconds);
	}
	seconds --;
}
function sendValidEmail(repeat) {
	var btn_html = '';
	if (repeat > 0) {
		btn_html = $('#reSE').html();
		$("#reSE").html("正在发送中……");
	} else {
		var obj = $("#getByEmailBtn").parents('span');
		var objHtml = obj.html();
		obj.html('<font color=#ff0000>正在处理中……</font>');
	}
	$.ajax({
		type:'POST',
		url:'/ajax?s=forg',
		data:'id='+userId,
		dataType:'json',
		cache:false,
		success:function(s) {
			if (repeat == 0) {
				if (s.code == 0) {
					var confirm_rs = $("#confirm_rs").html();
					$("#confirm_rs").remove();
					$('#pas_warp_content').html(confirm_rs);
				}
				obj.html(objHtml);
				int = setInterval('showtime()', 1000);
			} else {
				$("#reSE").html("已发送成功！");
			}
			
		}
	});
}
</script>
  <span style="display:none;" id="confirm_rs">
  <div class="weiz">找回密码</div>

<div class="liuc"><img src="/images/FrontEnd/psd_lc2.jpg" width="905" height="86" /></div>

<div class="pas_con">
  <div class="mai_yz"> <span class="yxb"><img src="/images/FrontEnd/yx_b.jpg" width="30" height="32" /></span>你正在使用"<span class="cheng">电子邮箱</span> "验证身份，请完成一下操作：</div>

  <div class="mai_yz2"> <span class="yxb"><img src="/images/FrontEnd/yx_b2.jpg" width="83" height="55" /></span>邮件已发送到您邮箱"<span class="cheng"><?php echo $memberInfo->Email;?></span> "请按照邮箱提示操作，完成身份验证</div>
  
  <div class="mai_yz3">
  <p class="yztext1">一直没有收到邮件</p>
  <p>请先检查是否在垃圾邮件中，如果还未找到，请<span class="yszt" id="reSE">(<span id="limitSecond">50</span>秒后)重新发送邮件</span></p>
  <p>还是收不到？请<span class="yztext2"><a href="/forget_password/">选择其他验证方式</a></span></p></div>
  
</div>
  </span>
  <?php else:?>
  <div class="weiz_1">抱歉，没找到相关帐号信息&nbsp;<a href="/forget_password/" style="color:#cc0000;">返回</a></div>
  <?php endif;?>
<?php else:?>
<div class="weiz">找回密码</div>

<div class="liuc"><img src="/images/FrontEnd/psd_lc1.jpg" width="905" height="86" /></div>



<div class="con">
<form method="post" action="" name="forgetForm" id="forgetForm">
  <ul class="input_test">
    <li>
  <label for="inp_name">账户名：</label>
      <p><input name="UserName" data-trim="true" data-describedby="for_username" data-description="UserName" data-required="true" type="text" class="input_out" id="in_name6" onfocus="this.className='input_on';this.onmouseout=''" onblur="this.className='input_off';this.onmouseout=function(){this.className='input_out'};" onmousemove="this.className='input_move'" onmouseout="this.className='input_out'" /></p>
      <span id="for_username"><span><img src="/images/FrontEnd/pic_3.jpg" width="13" height="24" /></span><h1>忘记用户名请使用手机或邮箱找回</h1></span>
      
</li>
<li>
<label for="inp_name">验证码：</label>
<p><input name="validCode" data-trim="true" data-describedby="for_validCode" data-description="validCode"  data-required="true" type="text" class="input_out1" id="in_email2" onfocus="this.className='input_on1';this.onmouseout=''" onblur="this.className='input_off1';this.onmouseout=function(){this.className='input_out1'};" onmousemove="this.className='input_move1'" onmouseout="this.className='input_out1'" /></p>
<span><img src="/forget-captcha" width="77" height="28" id="validCodeImg" /></span>
<h1><a href="javascript:;" id="refreshCode">看不清换一个</a><span id="for_validCode"></span></h1>

</li>
<li class="btn"><img src="/images/FrontEnd/next.jpg" height="42" id="next_btn"  style="cursor:pointer;"/></li>
  </ul>
  </form>
  </div>
<script>
$('#forgetForm').validate({
	onBlur : true,
	sendForm : true,
	eachValidField : function() {
		if ($(this).attr('name') != 'validCode') {
			$(this).parents('p').next('span').html('<img src="/images/FrontEnd/yes.jpg" width="25" height="26" />');
		}
	},
	description : {
		UserName : {
			required : '<span><img src="/images/FrontEnd/no.jpg" width="24" height="24" /></span><h1>不能为空</h1>'
		},
		validCode : {
			required : '<span class="kong"><img src="/images/FrontEnd/no.jpg" width="24" height="24" /></span>不能为空'
		}
	},
	valid:function() {
	}
});
$(function(){
	
	$("#next_btn").click(function(){
		$("#forgetForm").submit();
	});
	$("#refreshCode").click(function(){
		$("#validCodeImg").attr('src', '/forget-captcha?t'+Math.random());
	});
})
</script>
 <?php endif;?>
</div>
