<div class="right">
    <div class="r_t">
    <h1>身份认证</h1>
    <h2><span class="red">* </span>表示该项必填</h2></div>
    <div class="r_c">
       <div class="shouhuodizhi">
       <div class="mail_ts">
       <h1>温馨提示;</h1>
       <p>1.请务必准确填写本人正式身份信息。
         </p>
       <p>2.身份信息一经录用，不可随意更改。         </p>
       <p>3.未经本人许可，隐私信息会严格保密。</p>
       <p> 4.通过身份认证，可以更好的享受会员保障服务。 </p>
       </div>
       <div class="hy">
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td width="32" height="35">&nbsp;</td>
                <td width="91" height="35" align="right">会员名：</td>
                <td width="605" height="35" colspan="7">1388888888</td>
              </tr>
              <tr>
                <td height="35">&nbsp;</td>
                <td height="35" align="right">登录邮箱：</td>
                <td height="35" colspan="7">1388888888</td>
              </tr>
            </table>
       
         </div>
       <div class="hy_table"><table width="100%" border="0" cellspacing="0" cellpadding="0">
         
        <tr>
          <td height="38"></td>
          <td height="38" align="right">会员类型：</td>
          <td width="66" height="38" align="center" ><span class="ger">个人会员</span></td>
          <td width="14" class="lanse">&nbsp;</td>
          <td width="66" align="center"><span class="lanse">企业会员</span></td>
          <td width="454"></td>
        </tr>
        <tr>
          <td width="41" height="35">&nbsp;</td>
          <td width="87" height="35" align="right">真实姓名：</td>
          <td height="38" colspan="4"><input type="text" name="textfield2" id="textfield3" />
            <span class="red">            *</span></td>
        </tr>
        <tr>
          <td height="3">&nbsp;</td>
          <td height="35" align="right">身份证号码：</td>
          <td height="35" colspan="4"><input name="textfield4" type="text" id="textfield4" /> 
            <span class="red">*</span></td>
          </tr>
        <tr>
          <td height="30">&nbsp;</td>
          <td height="30" align="right">&nbsp;</td>
          <td height="30" colspan="4" id="huise"><input type="checkbox" name="checkbox" id="checkbox" />
            <label for="checkbox"> 我同意 <a href="#">服务协议</a></label></td>
        </tr>
        <tr>
          <td height="38">&nbsp;</td>
          <td height="38" align="right">&nbsp;</td>
          <td height="38" colspan="4"><input name="btn7" type="submit" id="btn7" value="确定" /></td>
        </tr>
        </table></div>
      </div>
    </div>
 </div>