<?php 
$this->headScript()->appendFile($this->basePath('js/jquery-validate.min.js'));
$user = $this->user;
$identityInfo = $this->identityInfo;
$msg = $this->flashMessages();
?>
<div class="right">
	<?php if (isset($this->applied) && $this->applied == 1):?>
    <div class="r_t">
    <h1>身份认证</h1>
    <h2>&nbsp;</h2></div>
    <div class="r_c">
        <div class="mimaxiugai">
       <div class="mimaxiugai_gongxi">恭喜你，身份认证成功</div>
       <div class="shenfen_qd">
         <table width="642" border="0" cellspacing="1" cellpadding="0" bgcolor="#CCCCCC">
  <tr>
    <td width="191" align="center" bgcolor="#FFFFFF">认证时间</td>
    <td width="172" align="center" bgcolor="#FFFFFF">企业名称</td>
    <td width="137" align="center" bgcolor="#FFFFFF">组织结构代码</td>
    <td width="137" align="center" bgcolor="#FFFFFF">认证状态</td>
  </tr>
  <tr>
    <td align="center" bgcolor="#FFFFFF"><?php echo date('Y年m月d日', strtotime($identityInfo->addTime));?></td>
    <td align="center" bgcolor="#FFFFFF"><p><?php echo $identityInfo->name;?></p></td>
    <td align="center" bgcolor="#FFFFFF"><?php echo $identityInfo->code;?></td>
    <td align="center" bgcolor="#FFFFFF"><p><?php echo $identityInfo->status == 0 ? '审核中' : (($identityInfo->status == 1) ? '已通过审核' : '未通过审核')?></p>
<!--       <p class="lanse"><a href="#">尚未认证</a></p></td> -->
  </tr>
         </table>
</div>
      </div>
    </div>
    <?php else:?>
    <div class="r_t">
    <h1>身份认证</h1>
    <h2><span class="red">* </span>表示该项必填</h2></div>
    <div class="r_c">
       <div class="shouhuodizhi">
       <div class="mail_ts">
       <h1>温馨提示;</h1>
       <p>1.请务必准确填写本人正式身份信息。
         </p>
       <p>2.身份信息一经录用，不可随意更改。         </p>
       <p>3.未经本人许可，隐私信息会严格保密。</p>
       <p> 4.通过身份认证，可以更好的享受会员保障服务。 </p>
       </div>
       <div class="hy">
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td width="32" height="35">&nbsp;</td>
                <td width="91" height="35" align="right">会员名：</td>
                <td width="605" height="35" colspan="7"><?php echo $user->UserName;?></td>
              </tr>
              <tr>
                <td height="35">&nbsp;</td>
                <td height="35" align="right">登录邮箱：</td>
                <td height="35" colspan="7"><?php echo $user->Email;?></td>
              </tr>
            </table>
       
         </div>
       <div class="hy_table">
       <div class="tc_i none">
         <p>使用充值。体现。转账功能时，需要您的真实姓名</p>
         <p class="chengse">注册完成后不可修改</p>
       </div>
       <div class="tc_ii none">
         <p>使用充值。体现。转账功能时，需要您的真实姓名</p>
         <p class="chengse">注册完成后不可修改</p>
       </div>
       <form method='post' action='' id="identityForm">
       <table width="100%" border="0" cellspacing="0" cellpadding="0">
         
        <tr>
          <td height="38"></td>
          <td height="38" align="right">会员类型：</td>
          <input type="hidden" name='type' value="1" />
          <td width="66" height="38" align="center" ><span class="ger" data-userType="1" style="cursor:pointer;">个人会员</span></td>
          <td width="14" class="lanse">&nbsp;</td>
          <td width="66" align="center"><span class="lanse" data-userType="2" style="cursor:pointer;">企业会员</span></td>
          <td width="454"></td>
        </tr>
        <tr>
          <td width="28" height="35">&nbsp;</td>
          <td width="100" height="35" align="right" id="field1">真实姓名：</td>
          <td height="38" colspan="4"><input type="text" name="textfield2" id="textfield3" />
            <span class="red">            *</span></td>
        </tr>
        <tr>
          <td height="3">&nbsp;</td>
          <td height="35" align="right" id="field2">身份证号码：</td>
          <td height="35" colspan="4"><input name="textfield4" type="text" id="textfield4" /> 
            <span class="red">*</span></td>
          </tr>
        <tr>
          <td height="30">&nbsp;</td>
          <td height="30" align="right">&nbsp;</td>
          <td height="30" colspan="4" id="huise"><input type="checkbox" checked='checked' name="checkbox" id="checkbox" />
            <label for="checkbox"> 我同意 <a href="#">服务协议</a></label></td>
        </tr>
        <tr>
          <td height="38">&nbsp;</td>
          <td height="38" align="right">&nbsp;</td>
          <td height="38" colspan="4"><input name="btn7" type="submit" id="btn7" value="确定" /></td>
        </tr>
        </table></form>
        <?php if (!empty($identityInfo)):?>
        <div class="shenfen_qd">
         <table width="642" border="0" cellspacing="1" cellpadding="0" bgcolor="#CCCCCC">
  <tr>
    <td width="191" align="center" bgcolor="#FFFFFF">认证时间</td>
    <td width="172" align="center" bgcolor="#FFFFFF">企业名称</td>
    <td width="137" align="center" bgcolor="#FFFFFF">组织结构代码</td>
    <td width="137" align="center" bgcolor="#FFFFFF">认证状态</td>
  </tr>
  <tr>
    <td align="center" bgcolor="#FFFFFF"><?php echo date('Y年m月d日', strtotime($identityInfo->addTime));?></td>
    <td align="center" bgcolor="#FFFFFF"><p><?php echo $identityInfo->name;?></p></td>
    <td align="center" bgcolor="#FFFFFF"><?php echo $identityInfo->code;?></td>
    <td align="center" bgcolor="#FFFFFF"><p><?php echo $identityInfo->status == 0 ? '审核中' : (($identityInfo->status == 1) ? '已通过审核' : '未通过审核')?></p>
<!--       <p class="lanse"><a href="#">尚未认证</a></p></td> -->
  </tr>
         </table>
</div><?php endif;?>
        </div>
      </div>
    </div>
    <?php endif;?>
 </div>
 <script>
$(function(){
	$("[data-userType]").click(
		function(){
			var t = $(this).attr('data-userType');
			$("[data-userType]").not($(this)).removeClass('ger').addClass('lanse');
			$(this).removeClass('lanse').addClass('ger');
			$("input[name='type']").val(t);
			switch(t) {
			case '1':
				$("#field1").html('真实姓名：');
				$("#field2").html('身份证号码：');
				break;
			case '2':
				$("#field1").html('公司名称：');
				$("#field2").html('组织代码机构：');
				break;
			default:
				break;
			}
		}
	);
	$("#textfield3").focusin(function(){
		$(".hy_table .tc_i").removeClass('none');
	}).focusout(function(){
		$(".hy_table .tc_i").addClass('none');
	});
	$("#textfield4").focusin(function(){
		$(".hy_table .tc_ii").removeClass('none');
	}).focusout(function(){
		$(".hy_table .tc_ii").addClass('none');
	});
})
 </script>