<?php 
$this->headScript()->appendFile($this->basePath('js/jquery-validate.min.js'));
$user = $this->user;
$msg = $this->flashMessages();
?>
<div class="right">
    <div class="r_t"><h1>基本信息</h1>
    <h2><span class="red">* </span>表示该项必填</h2></div>
    <div class="r_c">
       <div class="jibenxinxi">
       <?php if(!empty($msg['error'])):?>
            <div class="alert alert-error fade in">
            <button class="close" data-dismiss="alert" type="button">×</button>
            <?php foreach($msg['error'] as $v):?>
            <p><?php echo $v;?></p>
            <?php endforeach;?>
            </div>
            <?php endif;?>
            
            <?php if(!empty($msg['success'])):?>
            <div class="alert alert-success fade in">
            <button class="close" data-dismiss="alert" type="button">×</button>
            <?php foreach($msg['success'] as $v):?>
            <p><?php echo $v;?></p>
            <?php endforeach;?>
            </div>
            <?php endif;?>
       <form method='post' action='' id="userInfo">
      <table width="100%" border="0" cellspacing="0" cellpadding="0">
        <tr>
          <td width="135" height="38">&nbsp;</td>
          <td width="131" height="38" align="right">会员名：</td>
          <td width="484" height="38"><?php echo $user['UserName'];?></td>
        </tr>
        <tr>
          <td height="38">&nbsp;</td>
          <td height="38" align="right">登录邮箱：</td>
          <td height="38"><?php echo $user['Email'];?></td>
        </tr>
        <tr>
          <td height="38">&nbsp;</td>
          <td height="38" align="right">真实姓名：</td>
          <td height="38"><input data-trim="true" data-pattern="^[\w]{2,16}$" data-describedby="for_truename" data-description="TrueName" type="text" name="TrueName" id="textfield" value="<?php echo $user['TrueName'];?>" /><span id="for_truename"></span></td>
        </tr>
        <tr>
          <td height="38">&nbsp;</td>
          <td height="38" align="right">性别：</td>
          <td height="38"><input type="radio" name="radio" id="radio" value="1" <?php echo $user['Gender'] == 1 ? 'checked' : ''?> />
            男
              <input type="radio" name="radio" id="radio2" value="2" <?php echo $user['Gender'] == 2 ? 'checked' : ''?> />
            女
            <input type="radio" name="radio" id="radio3" value="0" <?php echo $user['Gender'] == 0 ? 'checked' : ''?> />
            保密<span class="red"> *</span></td>
        </tr>
        <tr>
          <td height="38">&nbsp;</td>
          <td height="38" align="right">生日：</td>
          <?php $birth = explode('-', $user['Birthday']);?>
          <td width="484" height="38"><label for="textfield2"></label>
          <select name="birth1">
          	<option value=''>年</option>
          <?php $curYear = date('Y');for($i = $curYear; $i >= $curYear-70; $i --) { ?>
          	<option value="<?php echo $i;?>" <?php echo $i== (isset($birth[0]) ? $birth[0] : '') ? 'selected' : '';?>><?php echo $i;?></option>
          	<?php }?>
          </select>
		  <select name="birth2">
          	<option value=''>月</option>
          <?php for($i = 1; $i <= 12; $i ++) { ?>
          	<option value="<?php echo $i;?>" <?php echo $i== (isset($birth[1]) ? $birth[1] : '') ? 'selected' : '';?>><?php echo $i;?></option>
          	<?php }?>
          </select>
          <select name="birth3">
          	<option value=''>日</option>
          <?php for($i = 1; $i <= 31; $i ++) { ?>
          	<option value="<?php echo $i;?>" <?php echo $i== (isset($birth[2]) ? $birth[2] : '') ? 'selected' : '';?>><?php echo $i;?></option>
          	<?php }?>
          </select>
         </td>
        </tr>
        <tr>
          <td height="38">&nbsp;</td>
          <td height="38" align="right">所在地区：</td>
          <td height="38"><select name="Province" id="select">
          <?php foreach ($this->prov as $k=>$v):?>
            <option value="<?php echo $k;?>" <?php echo $k==$user['Province'] ? 'selected' : '';?>><?php echo $v;?></option>
           <?php endforeach;?>
          </select>
            <select name="City" id="select2">
              <?php foreach ($this->cityList as $k=>$v):?>
            <option value="<?php echo $k;?>" <?php echo $k==$user['City'] ? 'selected' : '';?>><?php echo $v;?></option>
           <?php endforeach;?>
          </select>
            <select name="District" id="select3">
              <?php foreach ($this->districtList as $k=>$v):?>
            <option value="<?php echo $k;?>" <?php echo $k==$user['District'] ? 'selected' : '';?>><?php echo $v;?></option>
           <?php endforeach;?>
          </select></td>
        </tr>
        <tr>
          <td height="38">&nbsp;</td>
          <td height="38" align="right">详细地址：</td>
          <td height="38"><input autocomplete='off' data-trim="true" data-required='true' data-describedby="for_address" data-description="Address" name="Address" type="text" id="textfield5" size="35" value="<?php echo $user['Address'];?>" />
            <span id="for_address" class="red"><span class="huise">请填写真实的有效地址</span></span> <span class="red">*</span></td>
        </tr>
<!--         <tr> -->
<!--           <td height="38">&nbsp;</td> -->
<!--           <td height="38" align="right">邮政编码：</td> -->
<!--           <td height="38"><input name="textfield6" type="text" id="textfield6" size="15" /></td> -->
<!--         </tr> -->
        <tr>
          <td height="38">&nbsp;</td>
          <td height="38" align="right">移动电话：</td>
          <td height="38"><input data-trim="true" data-pattern="^((\+86)|(86))?(1(3|5|8))\d{9}$" data-required="true" data-describedby="for_mobile" data-description="Mobile" name="Mobile" type="text" id="textfield7" maxlength="14" size="20" value="<?php echo $user['Mobile'];?>"/>
            <span class="red" id="for_mobile">*</span></td>
        </tr>
        <tr>
          <td height="38">&nbsp;</td><?php $tel = explode('-', $user['Tel']);?>
          <td height="38" align="right">固定电话：</td>
          <td height="38"><input style="IME-MODE: disabled;" onkeyup="value=value.replace(/[^\d]/g,'')" name="tel1" type="text" id="textfield8" size="8" value="<?php echo isset($tel[0]) ? $tel[0] : '';?>" />
-
  <input style="IME-MODE: disabled;" onkeyup="value=value.replace(/[^\d]/g,'')" name="tel2" type="text" id="textfield9" size="8" value="<?php echo isset($tel[1]) ? $tel[1] : '';?>"/>
-
<input style="IME-MODE: disabled;" onkeyup="value=value.replace(/[^\d]/g,'')" name="tel3" type="text" id="textfield10" size="8" value="<?php echo isset($tel[2]) ? $tel[2] : '';?>"/> 
-
<span class="huise">区号-电话-分机</span></td>
        </tr>
        <tr>
          <td height="45" colspan="3" align="center"><input name="btn1" type="submit" id="btn1" value="确定" />             <input name="btn2" type="reset" id="btn2" value="取消" /></td>
        </tr>
      </table>
      </form></div>
    </div>
 </div>
 <script>
 $('#userInfo').validate({
		onBlur : true,
		sendForm : true,
		eachValidField : function() {
		},
		eachInvalidField : function() {
		},
		description : {
			TrueName : {
				pattern : '格式不正确'
			},
			Address : {
				required : '请输入详细地址'
			},
			Mobile : {
				required : '请输入手机号',
				pattern : '格式不正确'
			}
// 			repassword : {
// 				required : '<span><img src="/images/FrontEnd/no.jpg" width="24" height="24" /></span><h1>不能为空</h1>',
// 				pattern : '<span><img src="/images/FrontEnd/no.jpg" width="24" height="24" /></span><h1>请输入6到16位密码</h1>',
// 				conditional : {
// 					confirm : '<span><img src="/images/FrontEnd/no.jpg" width="24" height="24" /></span><h1>不能是纯数字或字母</h1>',
// 					same : '<span><img src="/images/FrontEnd/no.jpg" width="24" height="24" /></span><h1>两次输入的密码不一致</h1>'
// 				}
// 			}
		},
		conditional : {
			confirm : function() {
				var reg1 = /^[a-zA-Z]+$/;
	        	var reg2 = /^[0-9]+$/;
	        	var value = $(this).val();
	        	if (reg1.test(value)) {
					return false;
	            }
	            if (reg2.test(value)) {
					return false;
	            }
	            return true;
			},
			same : function() {
				return $(this).val() == $('input[name="password"]').val();
			}
		},
		valid:function() {
		}
	});
$(function(){
	$("select[name='Province']").change(function() {
		$v = $(this).val();
		if ($v == 0) return false;
		$.ajax({
			type: "POST",
			url : "/ajax?s=region&p="+$v,
			dataType :"json",
			success: function(s){
				var html = '<option >请选择城市</option>';
				for(var o in s) {
					html += "<option value='"+s[o].region_id+"'>"+s[o].region_name+"</option>";
				}
				$("select[name='City']").html(html);
			}
		});
	});
	$("select[name='City']").change(function() {
		$v = $(this).val();
		$.ajax({
			type: "POST",
			url : "/ajax?s=region&p="+$v,
			dataType :"json",
			success: function(s){
				var html = '<option >请选择区域</option>';
				for(var o in s) {
					html += "<option value='"+s[o].region_id+"'>"+s[o].region_name+"</option>";
				}
				$("select[name='District']").html(html);
			}
		});
	});
	$("ul>li", $(".birthSelect")).click(function(){
		$(this).parents('ul').prev("input[type='text']").val($(this).attr('data-val'));
		$(this).parents('ul').slideUp('fast');
	});
	$("input[name='birth1'],input[name='birth2'],input[name='birth3']").focusin(function() {
		$(this).next('ul').slideDown('fast');
	});
	$("input[name='birth1'],input[name='birth2'],input[name='birth3']").focusout(function(e) {
		e = window.event || e;
		var obj = e.srcElement || e.target;
		if (!$(obj).is('.birthSelect *')) {
			$(this).next('ul').slideUp('fast');
		}
	});
	$("select[name='birth1']").change(function(){
		var year = $(this).val();
		var curMonth = $("select[name='birth2']").val();
		if (curMonth == 2) {
			getFebruary(year);
		}
	});
	$("select[name='birth2']").change(function(){
		var year = $("select[name='birth1']").val();
		var curMonth = $("select[name='birth2']").val();
		if (curMonth == 2) {
			getFebruary(year);
		} else {
			var dayCount = 30;
			var dayOptions = "<option value=\"\">日</option>";
			switch (curMonth) {
				case '1':
				case '3':
				case '5':
				case '7':
				case '8':
				case '10':
				case '12':
					dayCount = 31;
				break;
			}
			for(var i=1; i <= dayCount; i ++) {
				dayOptions += "<option value=\""+i+"\">"+i+"</option>";
			}
			$("select[name='birth3']").html(dayOptions);
		}
	});
	var curMonth = $("select[name='birth2']").val();
	var defDay = '<?php echo (isset($birth[2]) ? $birth[2] : '');?>';
	if (curMonth == 2) {
		var year = $("select[name='birth1']").val();
		if (year) {
			getFebruary(year);
		}
	}
	function getFebruary(year) {
		var dayCount = 29;
		var dayOptions = "<option value=\"\">日</option>";
		if (year%4 != 0) {
			dayCount = 28;
		}
		for(var i=1; i <= dayCount; i ++) {
			if (defDay == i) {
				dayOptions += "<option value=\""+i+"\" selected>"+i+"</option>";
			} else {
				dayOptions += "<option value=\""+i+"\">"+i+"</option>";
			}
		}
		$("select[name='birth3']").html(dayOptions);
	}
})
 </script>