<div class="right">
    <div class="r_t">
    <h1>密码修改</h1>
    <h2>温馨提示：密码修改成功后请牢记您的密码</h2></div>
    <div class="r_c">
       <div class="shouhuodizhi">
      <table width="728" border="0" cellspacing="0" cellpadding="0">
        <tr>
          <td width="88" height="38">&nbsp;</td>
          <td width="100" height="38" align="right">当前密码：</td>
          <td height="38" colspan="3"><label for="textfield3"></label>
            <input type="text" name="textfield2" id="textfield3" />
            <span class="huise">            填写登录时的密码</span></td>
        </tr>
        <tr>
          <td height="38">&nbsp;</td>
          <td height="38" align="right">新密码：</td>
          <td height="38" colspan="3"><input type="text" name="textfield" id="textfield" /></td>
        </tr>
        <tr>
          <td height="38">&nbsp;</td>
          <td height="38" align="right">&nbsp;</td>
          <td height="40" colspan="3"><p class="chengse">注：不能使用6位数字做密码</p>
            <p class="huise">(新密码由6-30位组成，请使用英文字母加数字或符号的组合密码，</p>
            <p class="huise">建议不要单独使用英文字母，数字或符号作为您的密码)</p></td>
        </tr>
        <tr>
          <td height="38">&nbsp;</td>
          <td height="38" align="right">确认新密码：</td>
          <td height="38" colspan="3"><p>
            <input type="text" name="textfield323" id="textfield223" />
          </p></td>
        </tr>
        <tr>
          <td height="35">&nbsp;</td>
          <td height="35" align="right">&nbsp;</td>
          <td height="35" colspan="3" class="huise"><a href="#">（请再输入一边您上面输入的密码）</a></td>
        </tr>
        <tr>
          <td height="38">&nbsp;</td>
          <td height="38" align="right">验证码：</td>
          <td width="114" height="38"><input name="textfield4" type="text" id="textfield4" size="15" /> </td>
          <td width="70"><img src="images/yzm.jpg" width="55" height="21" /></td>
          <td width="356" class="chengse"><a href="#">看不清，换一个</a></td>
        </tr>
        <tr>
          <td height="38">&nbsp;</td>
          <td height="38" align="right">&nbsp;</td>
          <td height="38" colspan="3"><input name="btn4" type="submit" id="btn4" value="设置" /></td>
        </tr>
        </table>
      </div>
    </div>
 </div>