<?php 
$msg = $this->flashMessages();
?>
<div class="right">
    <div class="r_t">
    <h1>积分兑换</h1>
    <h2>&nbsp;</h2></div>
    <div class="r_c">
      <div class="jfd">服饰</div>
      <div class="jfdk">
          <div class="k"><img src="images/ttutu.jpg" width="174" height="144" /><h1>名称名称</h1><h2>三月最低价￥59元</h2><h3>现价￥<span class="reddz">9.4</span>+<span class="lvdz">50</span>积分</h3></div>
<div class="k"><img src="images/ttutu.jpg" width="174" height="144" /><h1>名称名称</h1><h2>三月最低价￥59元</h2><h3>现价￥<span class="reddz">9.4</span>+<span class="lvdz">50</span>积分</h3></div>        
<div class="k"><img src="images/ttutu.jpg" width="174" height="144" /><h1>名称名称</h1><h2>三月最低价￥59元</h2><h3>现价￥<span class="reddz">9.4</span>+<span class="lvdz">50</span>积分</h3></div>
<div class="k"><img src="images/ttutu.jpg" width="174" height="144" /><h1>名称名称</h1><h2>三月最低价￥59元</h2><h3>现价￥<span class="reddz">9.4</span>+<span class="lvdz">50</span>积分</h3></div>      
      </div>
      
      
            <div class="jfd">母婴</div>
      <div class="jfdk">
          <div class="k"><img src="images/ttutu.jpg" width="174" height="144" /><h1>名称名称</h1><h2>三月最低价￥59元</h2><h3>现价￥<span class="reddz">9.4</span>+<span class="lvdz">50</span>积分</h3></div>
<div class="k"><img src="images/ttutu.jpg" width="174" height="144" /><h1>名称名称</h1><h2>三月最低价￥59元</h2><h3>现价￥<span class="reddz">9.4</span>+<span class="lvdz">50</span>积分</h3></div>        
<div class="k"><img src="images/ttutu.jpg" width="174" height="144" /><h1>名称名称</h1><h2>三月最低价￥59元</h2><h3>现价￥<span class="reddz">9.4</span>+<span class="lvdz">50</span>积分</h3></div>
<div class="k"><img src="images/ttutu.jpg" width="174" height="144" /><h1>名称名称</h1><h2>三月最低价￥59元</h2><h3>现价￥<span class="reddz">9.4</span>+<span class="lvdz">50</span>积分</h3></div>      
      </div>
    
    </div>
 </div>
 <script>
$(function(){
	$("input[_href]").click(function(){
		var href = $(this).attr('_href');
		location.href=href;
	});
})
 </script>