<?php 
$msg = $this->flashMessages();
$member = $this->member;
?>
<div class="right">
    <div class="r_t">
    <h1>积分明细</h1>
    <h2>&nbsp;</h2></div>
    <div class="r_c">
       <div class="jif">
         <table width="728" border="0" cellspacing="0" cellpadding="0">
           <tr>
             <td width="150" height="30" align="center" class="red">可用积分</td>
             <td width="159" height="30" align="left">将要过期的积分</td>
             <td width="187" height="30" align="center">节省金额</td>
             <td width="232" height="30" align="center">&nbsp;</td>
           </tr>
           <tr>
             <td height="30" align="center" class="heidz"><?php echo $member['Points'];?></td>
             <td height="30" align="left" class="heidz">0</td>
             <td height="30" align="center"><span class="lvs">￥</span><span class="lanse">节省更多</span></td>
             <td height="30" align="center">&nbsp;</td>
           </tr>
           <tr>
             <td height="30" align="center">&nbsp;</td>
             <td height="30" align="left">（2014年3月.1日 过期）</td>
             <td height="30" align="center">&nbsp;</td>
             <td height="30" align="center">&nbsp;</td>
           </tr>
         </table>
       </div>
        
        <div class="jif01">
        <div class="cz_lm"><li data-sort="all" class="out">全部明细</li>
          <li data-sort="income">全部收入</li>
          <li data-sort="spending">全部支出</li>
          <li>过期积分</li>
          <li>冻结积分</li>
          <li><input name="" type="text" value="订单编号" id="dingd" size="10" /></li>
          <li>
            <input type="submit" name="button" id="button123" value="查询" />
          </li>
          </div>
          <span id="pointsList">
          
          </span>
        </div>
        
    </div>
 </div>
 <script>
 function toPage(url) {
//	 	var url = '/member/pointDetail';
//     $("#pointsList").html('<center>数据载入中……</center>');
		Ajax.call(url, '', function(s){
		    $("#pointsList").html(s);
		});
	}
$(function(){
	$("li[data-sort]").css('cursor', 'pointer');
	$("li[data-sort]").click(function(){
	    var sort = $(this).attr('data-sort');
	    var url = '/member/pointDetail';
	    switch(sort) {
	        case 'income':
		        url = '/member/pointDetail?sort=1';
		        break;
	        case 'spending':
		        url = '/member/pointDetail?sort=2';
		        break;
		    default:
			    url = '/member/pointDetail';
		        break;
	    }
	    $(this).addClass('out').siblings('li[data-sort]').removeClass('out');
	    toPage(url);
	});
	$("input[_href]").click(function(){
		var href = $(this).attr('_href');
		location.href=href;
	});
	var url = '/member/pointDetail';
	Ajax.call(url, '', function(s){
	    $("#pointsList").html(s);
	});
})
 </script>