<div class="right">
    <div class="r_t">
    <h1>密码设置</h1>
    <h2>&nbsp;</h2></div>
    <div class="r_c">
       <div class="shouhuodizhi">
       <div class="mail_ts">
       <h1>温馨提示;</h1>
       <p>密保问题将作为重要的身份验证方式，请认真设置</p>
       </div>
       <div class="mibao"><table width="100%" border="0" cellspacing="0" cellpadding="0">
        <tr>
          <td width="93" height="38">&nbsp;</td>
          <td width="104" height="38" align="right">问题一：</td>
          <td width="265" height="30" colspan="2">我
            <select name="select" id="select">
              <option value="上海">请选择</option>
              <option value="1">1</option>
              </select>
            的
            <select name="select2" id="select2">
              <option value="上海市">请选择</option>
              </select>
            是</td>
          <td height="30" align="center"><img src="images/pic_2.jpg" alt="" width="19" height="19" /></td>
          <td height="30">请选择问题</td>
        </tr>
        <tr>
          <td height="38">&nbsp;</td>
          <td height="38" align="right">答案：</td>
          <td height="38" colspan="2"><input name="textfield2" type="text" id="textfield3" size="40" /></td>
          <td width="39" height="38" align="center"><img src="images/pic_2.jpg" width="19" height="19" /></td>
          <td width="227">请输入问题</td>
        </tr>
        <tr>
          <td height="38">&nbsp;</td>
          <td height="38" align="right">问题二：</td>
          <td height="38" colspan="2"><input name="textfield" type="text" id="textfield" size="40" /></td>
          <td height="38" align="center"><img src="images/pic_2.jpg" alt="" width="19" height="19" /></td>
          <td height="38">请填写答案</td>
        </tr>
        <tr>
          <td height="38">&nbsp;</td>
          <td height="38" align="right">答案：</td>
          <td height="38" colspan="2"><input name="textfield3" type="text" id="textfield221" size="40" /></td>
          <td colspan="2">&nbsp;</td>
        </tr>
        <tr>
          <td height="38">&nbsp;</td>
          <td height="38" align="right">&nbsp;</td>
          <td height="38" colspan="4"><input name="btn6" type="submit" id="btn6" value="确定" /></td>
        </tr>
        </table></div>
       
      </div>
    </div>
 </div>