<?php 
$this->headScript()->appendFile($this->basePath('js/jquery-validate.min.js'));
$secInfo = $this->secInfo;
$msg = $this->flashMessages();
?>
<div class="right">
    <div class="r_t">
    <h1>密保设置</h1>
    <h2>&nbsp;</h2></div>
    <div class="r_c">
    <?php if(!empty($secInfo)):?>
    <div class="mimaxiugai">
    <?php if(!empty($msg['success'])):?>
       <div class="mimaxiugai_gongxi">恭喜你，密保设置成功</div>
    <?php endif;?>
       <div class="mail_qd">
         <table width="500" border="0" cellspacing="1" cellpadding="0" bgcolor="#CCCCCC">
  <tr>
  <?php $title = $this->list['title'];$answer = $this->list['answer'];?>
    <td width="191" height="40" align="center" bgcolor="#FFFFFF"><?php echo $title[0];?></td>
    <td width="172" height="40" align="center" bgcolor="#FFFFFF"><?php echo $title[1];?></td>
    </tr>
  <tr>
    <td height="40" align="center" bgcolor="#FFFFFF"><?php echo $answer[0];?></td>
    <td height="40" align="center" bgcolor="#FFFFFF"><p><?php echo $answer[1];?></p></td>
    </tr>
         </table>
</div>
      </div>
    <?php else:?>
       <div class="shouhuodizhi">
       <?php if(!empty($msg['error'])):?>
            <div class="alert alert-error fade in">
            <button class="close" data-dismiss="alert" type="button">×</button>
            <?php foreach($msg['error'] as $v):?>
            <p><?php echo $v;?></p>
            <?php endforeach;?>
            </div>
            <?php endif;?>
            
            <?php if(!empty($msg['success'])):?>
            <div class="alert alert-success fade in">
            <button class="close" data-dismiss="alert" type="button">×</button>
            <?php foreach($msg['success'] as $v):?>
            <p><?php echo $v;?></p>
            <?php endforeach;?>
            </div>
            <?php endif;?>
       <div class="mail_ts">
       <h1>温馨提示;</h1>
       <p>密保问题将作为重要的身份验证方式，请认真设置</p>
       </div>
       <div class="mibao">
       <form action="" method="post" id="secretForm" >
       <table width="100%" border="0" cellspacing="0" cellpadding="0">
        <tr>
          <td width="93" height="38">&nbsp;</td>
          <td width="104" height="38" align="right">问题一：</td>
          <td width="265" height="30" colspan="2">我
            <select name="firstType" id="select">
              <option value="0">请选择</option>
              <option value="1">爸爸</option>
              <option value="2">妈妈</option>
              <option value="3">爷爷</option>
              <option value="4">奶奶</option>
              <option value="5">哥哥</option>
              <option value="6">姐姐</option>
              </select>
            的
            <select name="secondType" id="select2">
              <option value="0">请选择</option>
              <option value="1">名字</option>
              <option value="2">生日</option>
              <option value="3">出生地</option>
              </select>
            是</td>
          <td height="30" align="center"><img src="/images/FrontEnd/pic_2.jpg" alt="" width="19" height="19" /></td>
          <td height="30">请选择问题</td>
        </tr>
        <tr>
          <td height="38">&nbsp;</td>
          <td height="38" align="right">答案：</td>
          <td height="38" colspan="2"><input name="answer[]" type="text" id="textfield3" size="40" /></td>
          <td width="39" height="38" align="center"><img src="/images/FrontEnd/pic_2.jpg" width="19" height="19" /></td>
          <td width="227">请输入问题</td>
        </tr>
        <tr>
          <td height="38">&nbsp;</td>
          <td height="38" align="right">问题二：</td>
          <td height="38" colspan="2"><input name="question2" type="text" id="textfield" size="40" /></td>
          <td height="38" align="center"><img src="/images/FrontEnd/pic_2.jpg" alt="" width="19" height="19" /></td>
          <td height="38">请填写答案</td>
        </tr>
        <tr>
          <td height="38">&nbsp;</td>
          <td height="38" align="right">答案：</td>
          <td height="38" colspan="2"><input name="answer[]" type="text" id="textfield221" size="40" /></td>
          <td colspan="2">&nbsp;</td>
        </tr>
        <tr>
          <td height="38">&nbsp;</td>
          <td height="38" align="right">&nbsp;</td>
          <td height="38" colspan="4"><input name="btn6" type="submit" id="btn6" value="确定" /></td>
        </tr>
        </table></form></div>
       
      </div>
      <?php endif;?>
    </div>
 </div>