<?php 
$this->headScript()->appendFile($this->basePath('js/jquery-validate.min.js'));
$msg = $this->flashMessages();
?>
<div class="right">
    <div class="r_t">
    <h1>未提交订单</h1>
    <h2>&nbsp;</h2></div>
    <div class="r_c">
        <div class="wtj">
          <table width="728" border="0" cellspacing="0" cellpadding="0">
            <tr>
              <td width="30">&nbsp;</td>
              <td width="32">&nbsp;</td>
              <td width="95">&nbsp;</td>
              <td width="186">&nbsp;</td>
              <td colspan="3" align="right">已选商品（不含邮费）：￥<span class="red">0.00</span></td>
              <td width="85" align="center"><input type="submit" name="jiesuan" id="jiesuan" value="结算" /></td>
            </tr>
            <tr>
              <td align="right"  class="wtj_lm"><input type="checkbox" name="checkbox" id="checkbox" />
              <label for="checkbox"></label></td>
              <td align="center" valign="middle"  class="wtj_lm">全选</td>
              <td align="center" valign="middle"  class="wtj_lm">商品</td>
              <td align="center" valign="middle"  class="wtj_lm">商品信息</td>
              <td width="106" align="center" valign="middle"  class="wtj_lm">单价</td>
              <td width="95" align="center" valign="middle"  class="wtj_lm">数量</td>
              <td width="99" align="center" valign="middle"  class="wtj_lm">小计</td>
              <td align="center" valign="middle"  class="wtj_lm">操作</td>
            </tr>
            <tr>
              <td height="120" align="right"><input type="checkbox" name="checkbox2" id="checkbox2" /></td>
              <td>&nbsp;</td>
              <td align="center" class="wtjimg"><img src="images/wtj01.jpg" width="79" height="79" /></td>
              <td align="left" valign="middle" class="wtjtit">10月22日，国务院总理李克强在北京人民大会堂与俄罗斯总理梅德韦杰夫共同会见记者</td>
              <td align="center">120.00￥</td>
              <td align="center"><table width="76%" border="0" cellspacing="0" cellpadding="0">
                <tr>
                  <td width="34%" align="center"><input type="submit" name="button" id="button1" value="+" /></td>
                  <td width="24%" align="center"><input name="textfield" type="text" id="textfield1" value="2" /></td>
                  <td width="42%" align="center"><input type="submit" name="button2" id="button2" value="-" /></td>
                </tr>
              </table></td>
              <td align="center" class="red">120.00￥</td>
              <td align="center"><p>移入收藏夹</p>
              <p>删除</p></td>
            </tr>
            <tr>
              <td height="120" align="right" bgcolor="#F5F5F5"><input type="checkbox" name="checkbox3" id="checkbox3" /></td>
              <td bgcolor="#F5F5F5">&nbsp;</td>
              <td align="center" valign="middle" bgcolor="#F5F5F5" class="wtjimg"><img src="images/wtj01.jpg" alt="" width="79" height="79" /></td>
              <td align="left" valign="middle" bgcolor="#F5F5F5" class="wtjtit">10月22日，国务院总理李克强在北京人民大会堂与俄罗斯总理梅德韦杰夫共同会见记者</td>
              <td align="center" bgcolor="#F5F5F5">120.00￥</td>
              <td align="center" bgcolor="#F5F5F5"><table width="76%" border="0" cellspacing="0" cellpadding="0">
                <tr>
                  <td width="34%" align="center"><input type="submit" name="button3" id="button3" value="+" /></td>
                  <td width="24%" align="center"><input name="textfield2" type="text" id="textfield2" value="2" /></td>
                  <td width="42%" align="center"><input type="submit" name="button3" id="button4" value="-" /></td>
                </tr>
              </table></td>
              <td align="center" bgcolor="#F5F5F5" class="red">120.00￥</td>
              <td align="center" bgcolor="#F5F5F5"><p>移入收藏夹</p>
              <p>删除</p></td>
            </tr>
          </table>
      </div>
      
    <div class="wtj01">成功删除1件宝贝，如有误，可<a href="#"><span class="lanse">撤销本次操作</span></a></div>
    
    <div class="wtj02">
      <table width="728" border="0" cellspacing="0" cellpadding="0">
        <tr>
          <td width="41" align="center"><input type="checkbox" name="checkbox4" id="checkbox4" /></td>
          <td width="47" align="left">全选</td>
          <td width="47" align="center">删除</td>
          <td width="118" align="center">批量移入收藏夹</td>
          <td width="49" align="center" class="wrightk">分享</td>
          <td width="133" align="center"  class="wrightk">已选商品<span class="reddz">0</span>件</td>
          <td width="212" align="center"   class="wrightk">合计（不含运费）<span class="reddz">￥240.00</span></td>
          <td width="81" align="center" class="heidz"><a href="#">结算</a></td>
        </tr>
      </table>
    </div>
    
    </div>
 </div>
 <script>
$(function(){
	$("input[_href]").click(function(){
		var href = $(this).attr('_href');
		location.href=href;
	});
})
 </script>