
<div id="Tab2">
  <div class="Menubox2">
    <ul>
      <li class="hover">首 页</li>
      <li >珍藏页</li>
      <li >分类页</li>
    </ul>
  </div>
  <div class="zwf"></div>
  <div class="Contentbox2"> 
    <div id="con_men_1" class="hover">
    
    <ul class="menu">
    <?php foreach ($this->nav as $k=>$v):?>
    <?php 
    if ($v['pid']) continue;
    $line = $v['line'];?>
    <li more="<?php echo $line*7 < count($v['links']) ? 'true' : 'false';?>">
    <?php $first=1;if ($v['img']):?>
    <img src="<?php echo $v['img'];?>" alt="<?php echo $v['name'];?>" width="108" height="41" />
    <?php else:?>
        	<?php echo $v['name'];?>
    <?php endif;?>
    </li>
    <?php endforeach;?>
<!--      <li><img src="images/yi.jpg" width="108" height="41" /></li><li class="menu_a"><img src="images/shi.jpg" width="108" height="41" /></li><li><img src="images/zhu.jpg" width="108" height="41" /> -->
<!--      </li><li><img src="images/xing.jpg" width="108" height="41" /></li><li><img src="images/jiao.jpg" width="108" height="41" /></li><li><img src="images/yu.jpg" width="108" height="41" /></li><li><img src="images/jian.jpg" width="108" height="41" /></li><li><img src="images/cai.jpg" width="108" height="41" /></li> -->
   
    </ul>
    
    <?php foreach ($this->struct['rootNav'] as $k=>$v):?>
    <div class="menu_k none">
    <?php if (isset($v['subNav'])):?>
    <ul class="menu_k_u">
    
    <?php foreach ($v['subNav'] as $s=>$n):?>
    <?php if ($s > 4):break;
    		endif;?>
    <li><a href="javascript:;"><?php echo $n['name'];?></a></li>
    <?php endforeach;?>
    
    </ul>
    <?php $subCount = count($v['subNav']);
    	  $subLeft = ceil($subCount/2);
    	  $subRight = $subCount-$subLeft;
    ?>
    
    <?php if ($subLeft>0):?>
      <div class="menu_k_left">
      <?php foreach ($v['subNav'] as $sl=>$slv):?>
      <?php if ($subLeft < $sl+1) break;?>
         <div class="l1">
           <h1><?php echo $slv['name'];?></h1>
           <?php if (isset($slv['links'])):?>
           <span class="l2">
           <?php $linkCount = count($slv['links']);foreach ($slv['links'] as $j=>$lk):?>
           <a href="<?php echo $lk['url'];?>" target="<?php echo $lk['target'];?>" title="<?php echo $lk['title'];?>"><?php echo $lk['title'];?></a><?php echo $linkCount > $j+1 ? '|' : '';?>
           <?php endforeach;?>
           </span>
         	<?php endif;?>
         </div>
      <?php endforeach;?>
      </div>
      <?php endif;?>
      
      <?php if ($subRight>0):?>
      <div class="menu_k_right">
	      <?php foreach ($v['subNav'] as $sl=>$slv):?>
	      <?php if ($subLeft >= $sl+1) continue;?>
	         <div class="l1">
	           <h1><?php echo $slv['name'];?></h1>
	           <?php if (isset($slv['links'])):?>
	           <span class="l2">
	           <?php $linkCount = count($slv['links']);foreach ($slv['links'] as $j=>$lk):?>
	           <a href="<?php echo $lk['url'];?>" target="<?php echo $lk['target'];?>" title="<?php echo $lk['title'];?>"><?php echo $lk['title'];?></a><?php echo $linkCount > $j+1 ? '|' : '';?>
	           <?php endforeach;?>
	           </span>
	         	<?php endif;?>
	         </div>
	      <?php endforeach;?>
      </div>
      <?php endif;?>
      <?php elseif (isset($v['links'])):?>
      <div class="menu_k_all">
         <div class="l1">
           <h1><?php echo isset($v['info']['name']) ? $v['info']['name'] : '';?></h1>
           <?php if (!empty($v['links'])):?>
           <span class="l2">
           <?php $linkCount = count($v['links']);foreach ($v['links'] as $a=>$ks):?>
           <a href="<?php echo $ks['url'];?>" target="<?php echo $ks['target'];?>" title="<?php echo $ks['title'];?>"><?php echo $ks['title'];?></a><?php echo $linkCount > $a+1 ? '|' : '';?>
           <?php endforeach;?>
           </span>
         	<?php endif;?>
         </div>
      </div>
      <?php endif;?>
    </div>
    <?php endforeach;?>
    
    
    
    
    <div class="link_k">
    <?php foreach ($this->nav as $k=>$v):?>
    <?php 
    if ($v['pid']) continue;
    $line = $v['line'];?>
    <div class="list">
    <?php foreach ($v['links'] as $n=>$link):?>
    <?php if (($n+1) > ($line*7)) break;?>
    <li style="width:90px;"><a href="<?php echo $link['url'];?>" target="<?php echo $link['target'];?>" title="<?php echo $link['title'];?>"><?php echo $link['title'];?></a></li>
    <?php endforeach;;?>
    </div>
	<?php endforeach;?>
	</div>
    </div>
    
  </div>
</div>
<div id="Tab2" style="display:none;">
  <div class="Menubox2">
    <ul>
      <li  class="hover">首 页</li>
      <li >珍藏页</li>
      <li >分类页</li>
    </ul>
  </div>
  <div class="zwf"></div>
  <div class="Contentbox2"> 
    <div id="con_men_1" class="hover">
        <?php foreach ($this->nav as $k=>$v):?>
        <?php $line = $v['line'];?>
        <div class="list">
        	<span style="float: left; position:relative;" more="<?php echo $line*7 < count($v['links']) ? 'true' : 'false';?>">
        	<?php if ($v['img']):?>
        	<img src="<?php echo $v['img'];?>" alt="<?php echo $v['name'];?>" />
        	<?php else:?>
        	<?php echo $v['name'];?>
        	<?php endif;?>
        	<ul class="show_all none">
        	<?php foreach ($v['links'] as $n=>$link):?>
        	<li><a href="<?php echo $link['url'];?>" target="<?php echo $link['target'];?>" title="<?php echo $link['title'];?>"><?php echo $link['title'];?></a></li>
        	<?php endforeach;?>
        	</ul>
        	</span>
        	<ul style="float: left; width:740px;">
        	<?php foreach ($v['links'] as $n=>$link):?>
        	<?php if (($n+1) > ($line*7)) break;?>
        	<li><a href="<?php echo $link['url'];?>" target="<?php echo $link['target'];?>" title="<?php echo $link['title'];?>"><?php echo $link['title'];?></a></li>
        	<?php endforeach;?>
        	</ul>
        </div>
        <?php endforeach;?>
    </div>
    
  </div>
</div>
<script type="text/javascript">
var provList;
var defCity = '<?php echo ($this->defCity) ? $this->defCity : '全国';?>';
<?php foreach($this->provList as $k=>$v):?>
provList += "<option value='<?php echo $v['region_id'];?>'><?php echo $v['region_name'];?></option>";
<?php endforeach;?>
$(function() {
	$('.swith_area .area_name').html(z_loc != '' ? z_loc : defCity);
	$(".menu > li").each(function(i){
			$(this).bind('mouseover', function() {
				if ($(this).attr('more') == 'true') {
					$(this).addClass('menu_a')
					var s_top = $(document).scrollTop();
// 					var t = $(this).offset();
					var h = -150 + 20*i + s_top;
					$("#con_men_1 .menu_k").eq(i).css('top', h+'px').show();
// 					$(".menu > li").eq(0).removeClass('line');
				}
				$(this).siblings('li').removeClass('menu_a');
				$("#con_men_1 .menu_k").siblings('.menu_k').not($("#con_men_1 .menu_k").eq(i)).hide();
			}).bind('mouseout', function(){
// 				$(".menu > li").eq(0).addClass('line');
			});
	});
	$("#con_men_1 .menu_k").hover(function() {
	},
	function() {
		$(this).hide();
		var index = $("#con_men_1 .menu_k").index($(this));
		$(".menu > li").eq(index).removeClass('menu_a');
// 		$(".menu > li").eq(0).addClass('line');
	}
	);
	var oHtml = '';
	var swith_area = $("<div class='swith_area'></div>");
	var aName = $("<div class='area_name'>"+z_loc != '' ? z_loc : defCity+"</div>");
	var swith = $("<div class='switch_b'><a href='javascript:;'>[切换]</a></div>");
	var sel = $("<div><p>请选择城市：</p><select name='sel_prov'><option value='0'>请选择</option>"+provList+"</select>"
			+"<select name='sel_city'><option value='0'>请选择</option></select>"
			+"<select name='sel_area'><option value='0'>请选择</option></select>"
			+"<input type='button' name='return' value='返回' /><input type='button' name='submit' value='确定' />"
			+"</div>");
	$(".swith_area").delegate('.switch_b','click', function() {
		oHtml = $(".swith_area").html();
		if ($.browser.msie) {
			$(".swith_area").html(sel.html());
		} else {
			$(".swith_area").html(sel);
		}
	});
// 	swith_area.append(aName).append(swith);
// 	$(".weather").prepend(swith_area);
	$(".swith_area").delegate("select[name='sel_prov']",'change', function(){
		var p = $(this).val();
		if (p != 0) {
			$.ajax({
				type: "POST",
				url : "/ajax?s=region&p="+p,
				dataType :"json",
				success: function(s){
					var html = '<option value="0" >请选择</option>';
					for(var o in s) {
						html += "<option value='"+s[o].region_id+"'>"+s[o].region_name+"</option>";
					}
					$(".swith_area").find("select[name='sel_city']").html(html);
				}
			});
		}
	});
	$(".swith_area").delegate("select[name='sel_city']",'change', function(){
		var p = $(this).val();
		if (p != 0) {
			$.ajax({
				type: "POST",
				url : "/ajax?s=region&p="+p,
				dataType :"json",
				success: function(s){
					var html = '<option value="0" >请选择</option>';
					for(var o in s) {
						html += "<option value='"+s[o].region_id+"'>"+s[o].region_name+"</option>";
					}
					$(".swith_area").find("select[name='sel_area']").html(html);
				}
			});
		}
	});
	$(".swith_area").delegate("input[name='return']",'click', function(){
// 		$(".swith_area").html(swith).prepend(aName);
		$(".swith_area").html(oHtml);
	});
	$(".swith_area").delegate("input[name='submit']",'click', function(){
		var t = $(".swith_area").find("select[name='sel_area'] option:selected").text();
		var city = $(".swith_area").find("select[name='sel_city'] option:selected").text();
		var prov = $(".swith_area").find("select[name='sel_prov'] option:selected").text();
		t = t.replace('请选择', '');
		city = city.replace('请选择', '');
		prov = prov.replace('请选择', '');
		if (t || city || prov) {
			setAreaCookie('z_loc_c', city);
			setAreaCookie('z_loc_a', t);
			setAreaCookie('z_loc_p', prov);
			location.reload();
		} else {
			$(".swith_area").html(oHtml);
		}
	});
})
</script>