<div class="zwf"></div>
<div id="addMangeLinks" class="tj_k none"> 
<div class="t_wz">
<div class="wtjk"></div>
<div class="tj_rtxt"><h1>管理我的网址</h1> <h3>你有什么建议，或者遇到什么问题，点此告诉我们>></h3><span><a id="closeLink" href="javascript:;"><img src="/images/FrontEnd/tj_r2.gif" width="24" height="24" /></a></span></div>
</div>

<div class="t_wz">
<div class="wtj">我添加的网址</div>
<div class="tj_wz"><!--你添加的网址会显示在这里，快到下面添加吧-->
<ul>
<?php if (isset($this->customLinks) && !empty($this->customLinks)):?>
        <?php foreach ($this->customLinks as $link):?>
        <li style="width:95px;">
        <a class="hao-link" href="<?php echo $link['url'];?>" target="_blank" title=""><?php echo $link['title'];?></a><span class="del_c_link"><img src="/images/FrontEnd/colro.gif" width="12" height="13" /></span>
        </li>
        <?php endforeach;?>
        <?php endif;?>
<!-- 
<li><span><img src="/images/FrontEnd/sina.gif" width="18" height="17" /></span>天猫<span class="del_c_link"><img src="/images/FrontEnd/colro.gif" width="12" height="13" /></span></li>
        <li><span><img src="/images/FrontEnd/sina.gif" width="18" height="17" /></span>天猫<span class="del_c_link"><img src="/images/FrontEnd/colro.gif" width="12" height="13" /></span></li>
        <li><span><img src="/images/FrontEnd/sina.gif" width="18" height="17" /></span>天猫<span class="del_c_link"><img src="/images/FrontEnd/colro.gif" width="12" height="13" /></span></li>
        <li><span><img src="/images/FrontEnd/sina.gif" width="18" height="17" /></span>天猫<span class="del_c_link"><img src="/images/FrontEnd/colro.gif" width="12" height="13" /></span></li>
        <li><span><img src="/images/FrontEnd/sina.gif" width="18" height="17" /></span>天猫<span class="del_c_link"><img src="/images/FrontEnd/colro.gif" width="12" height="13" /></span></li>
         -->
        </ul>
        </div>
</div>

<div class="t_wz">
<div class="wtj">手动添加</div>
<div class="sdtj_wz">
          <table width="100%" border="0" cellspacing="0" cellpadding="0">
            <tr>
              <td width="14%" align="right">网站名称：</td>
              <td width="32%"><label for="wzmc"></label>
              <input name="wzmc" type="text" id="wzmc" value="如：导航" size="25" /></td>
              <td width="9%" align="right">网址：</td>
              <td width="32%"><label for="wwz"></label>
              <input name="wwz" type="text" id="wwz" value="如：daohang.com" size="25" /></td>
              <td width="13%"><input name="badu_btn" type="submit" id="tj_btn" value="添加" /></td>
            </tr>
          </table>
        </div>
</div>



<div class="t_wz" id="recommendLinks">
<div class="tj_left">
<div class="wtj">从推荐中添加</div>
<ul class="tj_cy">
<?php $f= 0;foreach ($this->commonLinksCate as $k=>$v):?>
        <li cate-val="<?php echo $k;?>" <?php echo $f==0 ? 'class="ot"' : '';?>><?php echo $v;?></li>
<?php $f = 1;endforeach;?>
<!--         <li>宅男福利</li> -->
<!--         <li>生活更方便</li> -->
<!--         <li>宅男福利</li> -->
<!--         <li>上班族定制</li> -->
<!--         <li>我爱我家</li> -->
<!--         <li>热门微博</li> -->
<!--         <li>宅男福利</li> -->
        
        </ul>
</div>

<?php $lfirst = 0;foreach ($this->commonLinks as $k=>$v):?>
<div data-cate="<?php echo $k;?>" class="<?php echo $lfirst!=0 ? 'none' : '';?>">
<?php echo htmlspecialchars_decode($v['html']);?>
</div>
<?php $lfirst++;endforeach;?>

</div>
  </div>
<div id="Tab2">
<div class="zwf"></div>
  <div class="Menubox2">
    <ul>
      <li class="hover">首 页</li>
      <li >珍藏页</li>
      <li >分类页</li>
    </ul>
  </div>
  <div class="zwf"></div>
  <div class="Contentbox2"> 
    <div id="con_men_1" class="hover">
    
    <ul class="menu">
    <li id="manageLinks"><a href="javascript:;"><img width="108" height="41" src="/images/FrontEnd/tj.jpg"></a></li>
    <?php foreach ($this->nav as $k=>$v):?>
    <?php 
    if ($v['pid']) continue;
    $line = $v['line'];?>
    <li more="<?php echo 'true';//$line*7 < count($v['links']) ? 'true' : 'false';?>">
    <?php $first=1;if ($v['img']):?>
    <img src="<?php echo $v['img'];?>" alt="<?php echo $v['name'];?>" width="108" height="41" />
    <?php else:?>
        	<?php echo $v['name'];?>
    <?php endif;?>
    </li>
    <?php endforeach;?>
    </ul>
    <div class="menu_k none"></div>
    <?php foreach ($this->struct['rootNav'] as $k=>$v):?>
    <div class="menu_k none">
    <?php if (isset($v['links'])):?>
    <ul class="menu_k_u">
    <?php $line=$v['line'];foreach ($v['links'] as $n=>$link):?>
    <?php if (($n+1) > ($line*7)) break;?>
    <li><span><?php if ($link['show_icon'] && !empty($link['icon'])):?>
    <img src="<?php echo $link['icon'];?>" width="18" height="17" />
    <?php endif;?>
    </span><a class="hao-link" href="<?php echo $link['url'];?>"target="<?php echo $link['target'];?>" title=""><?php echo$link['title'];?></a>
    </li>
    <?php endforeach;?>
    </ul>
    <?php endif;?>
    <?php if (isset($v['subNav'])):?>
    <?php $subCount = count($v['subNav']);
    	  $subLeft = ceil($subCount/2);
    	  $subRight = $subCount-$subLeft;
    ?>
    <?php if ($subLeft>0):?>
      <div class="menu_k_left">
      <?php foreach ($v['subNav'] as $sl=>$slv):?>
      <?php if ($subLeft < $sl+1) break;?>
         <div class="l1" <?php echo $subLeft == $sl ? 'id="wu"' : ''?>>
           <h1><?php echo $slv['name'];?></h1>
           <?php if (isset($slv['links'])):?>
           <span class="l2">
           <?php $linkCount = count($slv['links']);foreach ($slv['links'] as $j=>$lk):?>
           <a class="hao-link" href="<?php echo $lk['url'];?>" target="<?php echo $lk['target'];?>" title="">
           <span>
            <?php if ($lk['show_icon'] && !empty($lk['icon'])):?>
                <img src="<?php echo $lk['icon'];?>" width="18" height="17" />
            <?php endif;?>
           </span>
           <?php echo $lk['title'];?></a>
           <?php endforeach;?>
           </span>
         	<?php endif;?>
         </div>
      <?php endforeach;?>
      </div>
      <?php endif;?>
      
      <?php if ($subRight>0):?>
      <div class="menu_k_right">
	      <?php foreach ($v['subNav'] as $sl=>$slv):?>
	      <?php if ($subLeft >= $sl+1) continue;?>
	         <div class="l1" <?php echo $subLeft == $sl ? 'id="wu"' : ''?>>
	           <h1><?php echo $slv['name'];?></h1>
	           <?php if (isset($slv['links'])):?>
	           <span class="l2">
	           <?php $linkCount = count($slv['links']);foreach ($slv['links'] as $j=>$lk):?>
	           <a class="hao-link" href="<?php echo $lk['url'];?>" target="<?php echo $lk['target'];?>" title="">
	           <span>
            <?php if ($lk['show_icon'] && !empty($lk['icon'])):?>
                <img src="<?php echo $lk['icon'];?>" width="18" height="17" />
            <?php endif;?>
           </span>
	           <?php echo $lk['title'];?></a>
	           <?php endforeach;?>
	           </span>
	         	<?php endif;?>
	         </div>
	      <?php endforeach;?>
      </div>
      <?php endif;?>  
    <?php endif;?>
   
   </div>
    <?php endforeach;?>
    
    <div class="link_k">
        <div class="list">
        <?php if (isset($this->customLinks) && !empty($this->customLinks)):?>
        <?php foreach ($this->customLinks as $link):?>
        <li style="width:95px;">
        <a class="hao-link" href="<?php echo $link['url'];?>" target="_blank" title=""><?php echo $link['title'];?></a>
        </li>
        <?php endforeach;?>
        <?php endif;?>
        </div>
    <?php foreach ($this->nav as $k=>$v):?>
    <?php 
    if ($v['pid']) continue;
    $line = $v['line'];?>
    <div class="list">
    <?php foreach ($v['links'] as $n=>$link):?>
    <?php if (($n+1) > ($line*7)) break;?>
    <li style="width:95px;">
    	<?php if ($link['show_icon'] && !empty($link['icon'])):?>
    	<span><img src="<?php echo $link['icon'];?>" width="18" height="17"></span>
    	<?php endif;?>
    	<a class="hao-link" href="<?php echo $link['url'];?>" target="<?php echo $link['target'];?>" title=""><?php echo $link['title'];?></a></li>
    <?php endforeach;;?>
    </div>
	<?php endforeach;?>
	</div>
    </div>
    
  </div>
</div>
<script type="text/javascript">
var provList;
var defCity = '<?php echo ($this->defCity) ? $this->defCity : '全国';?>';
<?php foreach($this->provList as $k=>$v):?>
provList += "<option value='<?php echo $v['region_id'];?>'><?php echo $v['region_name'];?></option>";
<?php endforeach;?>
$(function() {
	$('.swith_area .area_name').html(z_loc != '' ? z_loc : defCity);
	$(".menu > li").each(function(i){
			$(this).bind('mouseover', function() {
				if ($(this).attr('more') == 'true') {
					$(this).addClass('menu_a')
					var s_top = $(document).scrollTop();
					var sBox = $("#con_men_1 .menu_k").eq(i);
					var off = $(this).offset();
					var h = -162 + s_top;

					h = h > 0 ? 0 : h;
					var diff = off.top + $(this).height() + 12 - (h+$('#con_men_1').offset().top + sBox.height());
					if (diff > 0) {
						sBox.height(sBox.height()+diff);
					}
					sBox.css('top', h+'px').show();
				}
				$(this).siblings('li').removeClass('menu_a');
				$("#con_men_1 .menu_k").siblings('.menu_k').not($("#con_men_1 .menu_k").eq(i)).hide();
			}).bind('mouseout', function(){
			});
	});
	$("#con_men_1 .menu_k").hover(function() {
	},
	function() {
		$(this).hide();
		var index = $("#con_men_1 .menu_k").index($(this));
		$(".menu > li").eq(index).removeClass('menu_a');
	}
	);
	var oHtml = '';
	var swith_area = $("<div class='swith_area'></div>");
	var aName = $("<div class='area_name'>"+z_loc != '' ? z_loc : defCity+"</div>");
	var swith = $("<div class='switch_b'><a href='javascript:;'>[切换]</a></div>");
	var sel = $("<div><p>请选择城市：</p><select name='sel_prov'><option value='0'>请选择</option>"+provList+"</select>"
			+"<select name='sel_city'><option value='0'>请选择</option></select>"
			+"<select name='sel_area'><option value='0'>请选择</option></select>"
			+"<input type='button' name='return' value='返回' /><input type='button' name='submit' value='确定' />"
			+"</div>");
	$(".swith_area").delegate('.switch_b','click', function() {
		oHtml = $(".swith_area").html();
		$(".show_weather").hide();
		if ($.browser.msie) {
			$(".swith_area").html(sel.html());
		} else {
			$(".swith_area").html(sel);
		}
	});
	$(".swith_area").delegate("select[name='sel_prov']",'change', function(){
		var p = $(this).val();
		if (p != 0) {
			$.ajax({
				type: "POST",
				url : "/ajax?s=region&p="+p,
				dataType :"json",
				success: function(s){
					var html = '<option value="0" >请选择</option>';
					for(var o in s) {
						html += "<option value='"+s[o].region_id+"'>"+s[o].region_name+"</option>";
					}
					$(".swith_area").find("select[name='sel_city']").html(html);
				}
			});
		}
	});
	$(".swith_area").delegate("select[name='sel_city']",'change', function(){
		var p = $(this).val();
		if (p != 0) {
			$.ajax({
				type: "POST",
				url : "/ajax?s=region&p="+p,
				dataType :"json",
				success: function(s){
					var html = '<option value="0" >请选择</option>';
					for(var o in s) {
						html += "<option value='"+s[o].region_id+"'>"+s[o].region_name+"</option>";
					}
					$(".swith_area").find("select[name='sel_area']").html(html);
				}
			});
		}
	});
	$(".swith_area").delegate("input[name='return']",'click', function(){
		$(".swith_area").html(oHtml);
		$(".show_weather").show();
	});
	$(".swith_area").delegate("input[name='submit']",'click', function(){
		var t = $(".swith_area").find("select[name='sel_area'] option:selected").text();
		var city = $(".swith_area").find("select[name='sel_city'] option:selected").text();
		var prov = $(".swith_area").find("select[name='sel_prov'] option:selected").text();
		t = t.replace('请选择', '');
		city = city.replace('请选择', '');
		prov = prov.replace('请选择', '');
		if (t || city || prov) {
			setAreaCookie('z_loc_c', city);
			setAreaCookie('z_loc_a', t);
			setAreaCookie('z_loc_p', prov);
			location.reload();
		} else {
			$(".swith_area").html(oHtml);
			$(".show_weather").show();
		}
	});
	$.ajax({
		type:'POST',
		url:'/ajax?s=weather',
		data:'area='+escape(z_loc),
		dataType:'json',
		cache:false,
		async:false,
		success:function(s) {
			if (s.day_1.temp) {
				$("#day_1 .wtpic").html(s.day_1.img);
				$("#day_1 .wt1 .wtline").eq(1).html(s.day_1.temp[1]+'～'+s.day_1.temp[0]);
			}
			if (s.day_2.temp) {
				$("#day_2 .wtpic").html(s.day_2.img);
				$("#day_2 .wt1 .wtline").eq(1).html(s.day_2.temp[1]+'～'+s.day_2.temp[0]);
			}
			if (s.day_3.temp) {
				$("#day_3 .wtpic").html(s.day_3.img);
				$("#day_3 .wt1 .wtline").eq(1).html(s.day_3.temp[1]+'～'+s.day_3.temp[0]);
			}
		}
	});
	if (loginStatus == 1) {
		$(".hao-link").click(function(){
			var url = $(this).attr('href');
			Ajax.call('/ajax?s=view', {url:url}, function(){}, 'POST', 'JSON', true, true);
		});
	}
	$("#manageLinks").click(function(){$("#addMangeLinks").removeClass('none');});
	$("#closeLink").click(function(){$("#addMangeLinks").addClass('none');});

	$(".tj_wz").delegate("ul>li>span.del_c_link", 'click', function(){
		var url = $(this).prev('a').attr('href');
		$(".link_k .list").eq(0).find("a.hao-link[href='"+url+"']").parents('li').remove();
		$(this).parents('li').remove();
		delCustomLinks(url);
	});
	$("#wzmc").focusin(function(){if ($(this).val() == '如：导航') {$(this).val('');}}).focusout(function(){if ($.trim($(this).val()) == '') {$(this).val('如：导航')}});
	$("#wwz").focusin(function(){if ($(this).val() == '如：daohang.com') {$(this).val('');}}).focusout(function(){if ($.trim($(this).val()) == '') {$(this).val('如：daohang.com')}});
	$("#tj_btn").click(function(){
		var title = $.trim($("#wzmc").val());
		var url = $.trim($("#wwz").val());
		addClinks(title, url);
	});
	$("#recommendLinks a").click(function(){var title = $(this).html();var url = $(this).attr('href');addClinks(title, url);});
	function addClinks(title, url) {
		var custom_links = getcookie('custom_links');
		
		if (title == '' || title == '如：导航') {
			alert('请输入网站名称');return false;
		}
		if (url == '' || url == '如：daohang.com') {
			alert('请输入网址');return false;
		}
		if (url.toLowerCase().indexOf('http://') == -1) {
			url = 'http://'+url;
		}
		if (checkIsExistUrl(url)) {
		    alert('已存在网址'+url);
		    return;
		}
		setcookie('custom_links', custom_links+'||'+title+'*'+url);
		$(".tj_wz ul").append('<li><a href="'+url+'" target="_blank">'+title+'</a><span class="del_c_link"><img width="12" height="13" src="/images/FrontEnd/colro.gif"></span></li>');
		$(".link_k .list").eq(0).append('<li style="width:95px;"><a title="" target="_blank" href="'+url+'" class="hao-link">'+title+'</a></li>');
		$("#wzmc").val('');
		$("#wwz").val('');
	}
	$("#recommendLinks .tj_cy li").css('cursor', 'pointer');
	$("#recommendLinks .tj_cy li").click(function(){
	    $(this).addClass('ot').siblings('.ot').removeClass('ot');
	    $("div[data-cate='"+$(this).attr('cate-val')+"']").removeClass('none').siblings("div[data-cate]").addClass('none');
	});
	function delCustomLinks(url) {
		var cLinksCookies = getcookie('custom_links');
		var cLinks = cLinksCookies.split('||');
		var newClinks = '';
		for(var i=0;i<cLinks.length;i++) {
			var linkItem = cLinks[i].split('*');
			if (typeof linkItem[1] != 'undefined' && linkItem[1] != url) {
				newClinks += "||"+linkItem[0]+"*"+linkItem[1];
			}
		}
		setcookie('custom_links', newClinks);
	}
	function checkIsExistUrl(url) {
		var cLinksCookies = getcookie('custom_links');
		var cLinks = cLinksCookies.split('||');
		for(var i=0;i<cLinks.length;i++) {
			var linkItem = cLinks[i].split('*');
			if (typeof linkItem[1] != 'undefined' && linkItem[1] == url) {
				return true;
			}
		}
		return false;
	}
})
</script>