<div id="Tab2">
  <div class="Menubox2">
    <ul>
      <li  class="hover">首 页</li>
      <li >珍藏页</li>
      <li >分类页</li>
    </ul>
  </div>
  <div class="Contentbox2"> 
    <div id="con_men_1" class="hover">
        <?php foreach ($this->nav as $k=>$v):?>
        <div class="list">
        	<span style="float: left;">
        	<?php if ($v['img']):?>
        	<img src="<?php echo $v['img'];?>" alt="<?php echo $v['name'];?>" />
        	<?php else:?>
        	<?php echo $v['name'];?>
        	<?php endif;?>
        	</span>
        	<ul style="float: left; width:740px;">
        	<?php foreach ($v['links'] as $n=>$link):?>
        	<li><a href="<?php echo $link['url'];?>" target="<?php echo $link['target'];?>" title="<?php echo $link['title'];?>"><?php echo $link['title'];?></a></li>
        	<?php endforeach;?>
        	</ul>
        </div>
        <?php endforeach;?>

<!--         <div class="list"><span class="shi"></span></span><li>凡客</li><li>天猫</li></div> -->
        

<!--         <div class="list"><span class="zhu"></span></span><li>凡客</li><li>天猫</li></div> -->


<!--         <div class="list"><span class="xing"></span></span><li><span><img src="/images/FrontEnd/sina.gif" width="18" height="17" /></span>凡客</li><li>天猫</li></div> -->

<!--         <div class="list"><span class="jiao"></span></span><li>凡客</li><li>天猫</li></div> -->

<!--         <div class="list"><span class="yu"></span></span><li>凡客</li><li>天猫</li></div> -->

<!--         <div class="list"><span class="jian"></span></span><li>凡客</li><li><span><img src="/images/FrontEnd/sina.gif" width="18" height="17" /></span>天猫</li></div> -->

<!--         <div class="list"><span class="cai"></span></span><li>凡客</li><li>天猫</li></div> -->

    </div>
    
  </div>
</div>