<div id="Tab2">
  <div class="Menubox2">
    <ul>
      <li  class="hover">首 页</li>
      <li >珍藏页</li>
      <li >分类页</li>
    </ul>
  </div>
  <div class="Contentbox2"> 
    <div id="con_men_1" class="hover">
        <?php foreach ($this->nav as $k=>$v):?>
        <?php $line = $v['line'];?>
        <div class="list">
        	<span style="float: left; position:relative;" more="<?php echo $line*7 < count($v['links']) ? 'true' : 'false';?>">
        	<?php if ($v['img']):?>
        	<img src="<?php echo $v['img'];?>" alt="<?php echo $v['name'];?>" />
        	<?php else:?>
        	<?php echo $v['name'];?>
        	<?php endif;?>
        	<ul class="show_all none">
        	<?php foreach ($v['links'] as $n=>$link):?>
        	<li><a href="<?php echo $link['url'];?>" target="<?php echo $link['target'];?>" title="<?php echo $link['title'];?>"><?php echo $link['title'];?></a></li>
        	<?php endforeach;?>
        	</ul>
        	</span>
        	<ul style="float: left; width:740px;">
        	<?php foreach ($v['links'] as $n=>$link):?>
        	<?php if (($n+1) > ($line*7)) break;?>
        	<li><a href="<?php echo $link['url'];?>" target="<?php echo $link['target'];?>" title="<?php echo $link['title'];?>"><?php echo $link['title'];?></a></li>
        	<?php endforeach;?>
        	</ul>
        </div>
        <?php endforeach;?>
    </div>
    
  </div>
</div>
<script type="text/javascript">
$(function() {
	$(".list > span").each(function(){
		if ($(this).attr('more') == 'true') {
			$(this).bind('mouseover', function() {
				$(this).find('ul.show_all').css({position:'absolute',left:"120px", top:"0"}).show();
			}).bind('mouseout', function() {
				$(this).find('ul.show_all').hide();
			});
		}
	});
})
</script>