<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<?php echo $this->headTitle(); ?>
<?php 
            echo $this->headLink()->prependStylesheet($this->basePath() . '/styles/FrontEnd/common.css')
            ->prependStylesheet($this->basePath() . '/styles/FrontEnd/member.css');
        ?>
        
        <?php
        echo $this->headScript()->prependFile($this->basePath('js/FrontEnd/comm.js'))
            ->prependFile($this->basePath('js/jquery.min.js'));
       ?>
<style>
.right {
	min-height:600px;
}       
</style>
</head>

<body>
<div class="header_bg stayHere">
  <div class="header">
    <h1><a href="/">欢迎来导航！</a></h1>
    <?php if ($this->container):?>
    <h2><?php echo $this->container->UserName;?></h2><h3><a href="/logout">安全退出</a>
    <?php else:?>
    <h2><a href="/login">请登录</a></h2><h3><a href="/register">免费注册</a>
    <?php endif;?>
    </h3><h4><a href="/">首页</a>|<a href="#">联系我们</a>|<a href="/">网站导航</a></h4></div>
</div>
<div class="warp">
<div class="top">
    <div class="logo"><img src="/images/FrontEnd/reg_logo.jpg" width="117" height="76" /></div>    <div class="logo_txt">会员中心</div>
</div>
</div>
<div class="main">
<?php echo $this->partial('layout/cLeft.phtml');?>
 <!--右侧-->
 <?php echo $this->content;?>
</div>
<?php echo $this->partial('layout/footer.phtml');?>
</body>
</html>