<div class="header_bg stayHere">
  <div class="header">
  <?php if ($this->container->UserID):?>
  <div class="dlh none">
      <p class="fegx"><a href="/member" style="padding-right:8px;">会员中心</a> <span style="color:#ccc;">|</span> <a href="/logout" style="padding-left:8px;">安全退出</a></p>
      <p>登录 <?php echo $this->container->LoginCount;?> 次        </p>
      <p>交易  <?php echo 0;?> 次</p>
      <p> 积分 <?php echo $this->container->Points;?>分        </p>
      <p>星级  一  星 </p>
   </div>
  <?php else:?>
   <div class="dl none" id="login_f">
   <div class="dl_yh"><span class="yh">用户名：</span><span>
     <label for="yhm"></label>
     <input type="text" name="yhm" id="yhm" value="<?php echo isset($_COOKIE['userName']) ? $_COOKIE['userName'] : ''?>" />
   </span></div>
      <div class="dl_yh"><span class="yh">密　码：</span><span>
     <label for="yhm"></label>
     <input type="password" name="mim" id="mim" />
   </span></div>
   <div id="curMsg" style="color:red;"></div>
   <div class="dl_yh"><span class="jiz">
     <input type="checkbox" name="remberMe" id="checkbox" />
     记住登录状态</span><span><a href="/forget_password/" class="forgetStyle">忘记密码</a></span><span class="dlb">
     <input type="submit" name="tcdl" id="tcdl" value="登录" />
   </span></div>
<!--    <div class="dl_yh1"><a href="/register">注册新用户</a> <a href="/forget_password/">忘记密码</a> <a href="#">帮助中心</a></div> -->
   </div>
   <?php endif;?>
  <ul class="lgoin"><li>我的导航</li><li class="dldt dldtjt none" id="login_cue">请输入</li>
  <?php if ($this->container->UserID):?>
  <li id="userTool" class="dldt02">你好，<?php echo $this->container->UserName;?></li>
  <?php else:?>
  <li class="login_li"><a href="javascript:;">请登录</a></li><li><a href="/register" style="color:#000;">免费注册</a></li>
  <?php endif;?>
  </ul>
  <div class="top_nav"><a href="javascript:;"  onClick="setHome(window.location);">设为首页</a>|<a href="/shortcut">下载桌面</a>|<a href="javascript:;" id="select_skin">换肤</a>|<a href="#">联系我们</a></div></div>
</div>
<div class="huaf none">
   <div class="hh">
   <div class="lm">选择皮肤</div>
   <div class="wk">
    <ul class="hf_n"><li>全部</li>
    <li>kit</li><li>全部</li><li>全部</li><li>全部</li><li class="outn">全部</li><li>全部</li>
    <li class="rig">当前第1共11页面</li></ul>
    <div class="hf_c">
      <div class="lf"><img src="/images/FrontEnd/hf_z.jpg" width="29" height="29" /></div>
          <div class="hf_xk">
         <div class="hft"><img src="/images/FrontEnd/hf_02.jpg" width="136" height="92" /><p><input name="" type="checkbox" value="" checked="checked" />
           <strong>小兔子</strong></p></div>
         <div class="hft"><img src="/images/FrontEnd/hf_02.jpg" width="136" height="92" /><p><input name="" type="checkbox" value="" />小兔子</p></div>
         <div class="hft"><img src="/images/FrontEnd/hf_02.jpg" width="136" height="92" /><p><input name="" type="checkbox" value="" />小兔子</p></div>
         <div class="hft"><img src="/images/FrontEnd/hf_02.jpg" width="136" height="92" /><p><input name="" type="checkbox" value="" />小兔子</p></div>
         <div class="hft"><img src="/images/FrontEnd/hf_02.jpg" width="136" height="92" /><p><input name="" type="checkbox" value="" />小兔子</p></div>
         <div class="hft"><img src="/images/FrontEnd/hf_02.jpg" width="136" height="92" /><p><input name="" type="checkbox" value="" />小兔子</p></div>
         </div>
      <div class="ri"><img src="/images/FrontEnd/hf_y.jpg" width="29" height="29" /></div>
    </div>
   </div>
   
   <div class="hf_btn"><input name="hf_bc" type="submit" id="hf_bc" value="保存" /> 
     <input name="hf_gb" type="submit" id="hf_gb" value="关闭" /></div>
   </div>
</div>
<script>
$(function(){
	$("#hf_gb").click(function(){
		$(".huaf").slideUp('fast');
	});
	$("#select_skin").click(function(){
		$(".huaf").slideDown('fast');
	});
	$(".login_li").click(function(){
		$(this).hide();
		$("#login_cue").show();
		$("#login_f").show();
	});
	$("#login_cue").click(function(){
		$("#login_f, #login_cue").hide();
		$(".login_li").show();
	});
	$("#userTool").hover(function() {
		$(".dlh").show();
		$(this).removeClass('dldt02').addClass('dldt01');
	},function(e){
		$(".dlh").hide();
		$(this).removeClass('dldt01').addClass('dldt02');
	});
	$(".dlh").hover(function(){$(".dlh").show();$("#userTool").removeClass('dldt02').addClass('dldt01');},function(){$(".dlh").hide();$("#userTool").removeClass('dldt01').addClass('dldt02');});
	$("#tcdl").click(function(){
		var userName = $.trim($("#yhm").val());
		var password = $.trim($("#mim").val());
		$("#curMsg").html('');
		if ($("input[name='remberMe']").is(':checked')) {
			var rememberMe = 1;
		} else {
			var rememberMe = 0;
		}
		
		
		if (userName != '' && password != '' && userName != '用户名' && password != '密码') {
			$("#curMsg").html('正在登录中……');
			$.ajax({
				type: 'POST',
				url:'/login',
				data: 'username='+userName+'&password='+password+'&rememberMe='+rememberMe,
				dataType:'json',
				success:function(e) {
					if (e.code == 0) {
						location.href='/';
					} else {
						$("#curMsg").html(e.msg);
					}
// 					$("#curMsg").html('');
				}
			});
		} else {
			$("#curMsg").html('请输入用户名和密码');
		}
	});
})
</script>