<div class="header_bg stayHere">
  <div class="header">
  <?php if ($this->container->UserID):?>
  <div class="dlh none">
      <p class="fegx"><a href="/member" style="padding-right:8px;">会员中心</a> <span style="color:#ccc;">|</span> <a href="/logout" style="padding-left:8px;">安全退出</a></p>
      <p>登录 <?php echo $this->container->LoginCount;?> 次        </p>
      <p>交易  <?php echo 0;?> 次</p>
      <p> 积分 <?php echo $this->container->Points;?>分        </p>
      <p>星级  一  星 </p>
   </div>
  <?php else:?>
   <div class="dl none" id="login_f">
   <div class="dl_yh"><span class="yh">用户名：</span><span>
     <label for="yhm"></label>
     <input type="text" name="yhm" id="yhm" value="<?php echo isset($_COOKIE['userName']) ? $_COOKIE['userName'] : ''?>" />
   </span></div>
      <div class="dl_yh"><span class="yh">密　码：</span><span>
     <label for="yhm"></label>
     <input type="password" name="mim" id="mim" />
   </span></div>
   <div id="curMsg" style="color:red;"></div>
   <div class="dl_yh"><span class="jiz">
     <input type="checkbox" name="remberMe" id="checkbox" />
     记住登录状态</span><span><a href="/forget_password/" class="forgetStyle">忘记密码</a></span><span class="dlb">
     <input type="submit" name="tcdl" id="tcdl" value="登录" />
   </span></div>
<!--    <div class="dl_yh1"><a href="/register">注册新用户</a> <a href="/forget_password/">忘记密码</a> <a href="#">帮助中心</a></div> -->
   </div>
   <?php endif;?>
  <ul class="lgoin"><li>我的导航</li><li class="dldt dldtjt none" id="login_cue">请输入</li>
  <?php if ($this->container->UserID):?>
  <li id="userTool" class="dldt02">您好  <font style="font-size:14px;"><?php echo $this->container->UserName;?> <span style="color:#999;font-size:12px;">^_^</span></font></li>
  <?php else:?>
  <li class="login_li"><a href="javascript:;">请登录</a></li><li><a href="/register" style="color:#000;">免费注册</a></li>
  <?php endif;?>
  </ul>
  <div class="top_nav"><a href="javascript:;"  onClick="setHome(window.location);">设为首页</a>|<a href="/shortcut">下载桌面</a>|<a href="javascript:;" id="select_skin">换肤</a>|<a href="#">联系我们</a></div></div>
</div>
<div class="huaf none">
   <div class="hh">
   <div class="lm">选择皮肤</div>
   <div class="wk">
    <ul class="hf_n"><li class="outn">全部</li>
    <li>风景</li><li>人物</li><li>萌宠</li><li>中国风</li><li>动漫</li><li>其他</li>
    <li class="rig none">当前第1共1页面</li></ul>
    <!-- <div class="hf_c" id="scrollable">
      <div class="lf" id="arrowLeft"><a href="javascript:;" class="prev"><img src="/images/FrontEnd/hf_z.jpg" width="29" height="29" /></a></div>
          <div class="hf_xk items">
         <div class="hft"><img src="/images/FrontEnd/bg_l.png" width="136" height="92" /><p><input name="select_skin" type="checkbox" value="bg_default" <?php echo (isset($_COOKIE['bg_class']) && $_COOKIE['bg_class'] == 'bg_default') ? 'checked="checked"' : '';?> />
           <strong>默认</strong></p></div>
         <div class="hft"><img src="/images/FrontEnd/bg1.jpg" width="136" height="92" /><p><input name="select_skin" type="checkbox" value="bg_1" <?php echo (isset($_COOKIE['bg_class']) && $_COOKIE['bg_class'] == 'bg_1') ? 'checked="checked"' : '';?>/>背景</p></div>
         <div class="hft"><img src="/images/FrontEnd/bg2.jpg" width="136" height="92" /><p><input name="select_skin" type="checkbox" value="bg_2" <?php echo (isset($_COOKIE['bg_class']) && $_COOKIE['bg_class'] == 'bg_2') ? 'checked="checked"' : '';?>/>背景</p></div>
         <div class="hft"><img src="/images/FrontEnd/bg3.jpg" width="136" height="92" /><p><input name="select_skin" type="checkbox" value="bg_3" <?php echo (isset($_COOKIE['bg_class']) && $_COOKIE['bg_class'] == 'bg_3') ? 'checked="checked"' : '';?>/>背景</p></div>
         <div class="hft"><img src="/images/FrontEnd/bg4.jpg" width="136" height="92" /><p><input name="select_skin" type="checkbox" value="bg_4" <?php echo (isset($_COOKIE['bg_class']) && $_COOKIE['bg_class'] == 'bg_4') ? 'checked="checked"' : '';?>/>背景</p></div>
         <div class="hft"><img src="/images/FrontEnd/bg5.jpg" width="136" height="92" /><p><input name="select_skin" type="checkbox" value="bg_5" <?php echo (isset($_COOKIE['bg_class']) && $_COOKIE['bg_class'] == 'bg_5') ? 'checked="checked"' : '';?>/>背景</p></div>
         <div class="hft"><img src="/images/FrontEnd/bg6.jpg" width="136" height="92" /><p><input name="select_skin" type="checkbox" value="bg_6" <?php echo (isset($_COOKIE['bg_class']) && $_COOKIE['bg_class'] == 'bg_6') ? 'checked="checked"' : '';?>/>背景</p></div>
         <div class="hft"><img src="/images/FrontEnd/bg7.jpg" width="136" height="92" /><p><input name="select_skin" type="checkbox" value="bg_7" <?php echo (isset($_COOKIE['bg_class']) && $_COOKIE['bg_class'] == 'bg_7') ? 'checked="checked"' : '';?>/>背景</p></div>
         </div>
      <div class="ri" id="arrowRight"><a href="javascript:;" class="next"><img src="/images/FrontEnd/hf_y.jpg" width="29" height="29" /></a></div>
    </div> -->
    	<div style="clear:both;"></div>
	    <div class="skin_lists">
	    	<div class="change_skin_left">
    <div class="div_lf" id="arrowLeft" style="z-index: 1000;"><a href="javascript:;" class="prev"><img src="/images/FrontEnd/hf_z.jpg" width="29" height="29" /><span class="d_span">默认</span></a></div>
    <div class="hft add_default_style"><img src="/images/FrontEnd/bg_l.png" width="136" height="92" /><p><input style="display: none;" name="select_skin" type="checkbox" value="bg_default" <?php echo (isset($_COOKIE['bg_class']) && $_COOKIE['bg_class'] == 'bg_default') ? 'checked="checked"' : '';?> />
           <label bg-data="bg_default"><strong>小兔子</strong></label></p></div>
    </div>
    <div class="hf_c scrollable"><!--实体部分 定宽 溢出隐藏-->
   <!-- root element for the items -->
   <ul class="items" id="chklist">
         <li><div class="hft"><img src="/images/FrontEnd/1.jpg" width="136" height="92" /><p><input style="display: none;" name="select_skin" type="checkbox" value="bg_1" <?php echo (isset($_COOKIE['bg_class']) && $_COOKIE['bg_class'] == 'bg_1') ? 'checked="checked"' : '';?>/>
         <label bg-data="bg_1"><strong>小兔子</strong></label></p></div></li>
         <li><div class="hft"><img src="/images/FrontEnd/2.jpg" width="136" height="92" /><p><input style="display: none;" name="select_skin" type="checkbox" value="bg_2" <?php echo (isset($_COOKIE['bg_class']) && $_COOKIE['bg_class'] == 'bg_2') ? 'checked="checked"' : '';?>/>
         <label bg-data="bg_2"><strong>小兔子</strong></label></p></div></li>
         <li><div class="hft"><img src="/images/FrontEnd/3.jpg" width="136" height="92" /><p><input style="display: none;" name="select_skin" type="checkbox" value="bg_3" <?php echo (isset($_COOKIE['bg_class']) && $_COOKIE['bg_class'] == 'bg_3') ? 'checked="checked"' : '';?>/>
         <label bg-data="bg_3"><strong>小兔子</strong></label></p></div></li>
         <li><div class="hft"><img src="/images/FrontEnd/1.jpg" width="136" height="92" /><p><input style="display: none;" name="select_skin" type="checkbox" value="bg_4" <?php echo (isset($_COOKIE['bg_class']) && $_COOKIE['bg_class'] == 'bg_4') ? 'checked="checked"' : '';?>/>
         <label bg-data="bg_4"><strong>小兔子</strong></label></p></div></li>
         <li><div class="hft"><img src="/images/FrontEnd/2.jpg" width="136" height="92" /><p><input style="display: none;" name="select_skin" type="checkbox" value="bg_5" <?php echo (isset($_COOKIE['bg_class']) && $_COOKIE['bg_class'] == 'bg_5') ? 'checked="checked"' : '';?>/>
         <label bg-data="bg_5"><strong>小兔子</strong></label>
         </p></div></li>
         <li><div class="hft"><img src="/images/FrontEnd/3.jpg" width="136" height="92" /><p><input style="display: none;" name="select_skin" type="checkbox" value="bg_6" <?php echo (isset($_COOKIE['bg_class']) && $_COOKIE['bg_class'] == 'bg_6') ? 'checked="checked"' : '';?>/>
         <label bg-data="bg_6"><strong>小兔子</strong></label></p></div></li>
         <li><div class="hft"><img src="/images/FrontEnd/1.jpg" width="136" height="92" /><p><input style="display: none;" name="select_skin" type="checkbox" value="bg_7" <?php echo (isset($_COOKIE['bg_class']) && $_COOKIE['bg_class'] == 'bg_7') ? 'checked="checked"' : '';?>/>
         <label bg-data="bg_7"><strong>小兔子</strong></label></p></div></li>
   </ul>
   <div class="ri" id="arrowRight"><a href="javascript:;" class="next"><img src="/images/FrontEnd/hf_y.jpg" width="29" height="29" /></a></div>
</div>
<div style="clear:both;"></div>
	    </div>
    
   </div>
   
   <div class="hf_btn"><input name="hf_bc" type="submit" id="hf_bc" value="保存" /> 
     <input name="hf_gb" type="submit" id="hf_gb" value="关闭" /></div>
   </div>
</div>
<style>
.scrollable {
position:relative;
overflow:hidden;
width:986px;
height:130px;
}
.scrollable .items {
width:20000em;
position:absolute;
}
.items li {
float:left;
padding:5px;
}
</style>
<script>
$(function(){
	$(".add_default_style").hcheckbox();
	$('#chklist').hcheckbox();
	$('#radiolist').hradio();
	$("div.scrollable").scrollable({circular: false,next:".next",
        prev:".prev", mousewheel: false});
	$("#arrowRight").click(function(){
		var left = $(".huaf .hh .wk .hf_c .hf_xk").css('left');
		$(".huaf .hh .wk .hf_c .hf_xk").animate({'left': '-'+left+150+'px'},1000);
	});
	$("#arrowLeft").click(function(){
		var left = $(".huaf .hh .wk .hf_c .hf_xk").css('left');
		$(".huaf .hh .wk .hf_c .hf_xk").animate({'left': left+150+'px'},1000);
	});
	$(".hf_c input[name='select_skin'], .items .hft p label").click(function(){
		$(".add_default_style p label").removeClass('checked');
		$(".add_default_style input[name='select_skin']").removeAttr('checked');
		$('body').removeClass().addClass($(this).attr('bg-data'));
		$(".hf_c input[name='select_skin']").not($(this)).removeAttr('checked');
		$(this).addClass('checked');
		$(".items .hft p label").not($(this)).removeClass("checked");
	});
	$(".add_default_style p label").click(function(){
		$('body').removeClass().addClass($(this).attr('bg-data'));
		$(".hf_c input[name='select_skin']").removeAttr('checked');
		$(this).addClass('checked');
		$(".items .hft p label").removeClass("checked");
	});
	$(".add_default_style img,.change_skin_left .d_span").click(function() {$(".add_default_style p label").trigger('click');});
	$("#hf_gb").click(function(){
		$(".huaf").slideUp('fast');
		$("#select_skin").html('换肤');
	});
	$("#hf_bc").click(function(){
		var bg_class = $(".hf_c input[name='select_skin']:checked").val();
		var bg_class = $(".add_default_style p label.checked").attr('bg-data') ? $(".add_default_style p label.checked").attr('bg-data') : $(".items .hft p label.checked").attr('bg-data');
		if (bg_class) {
			setcookie('bg_class', bg_class, 7000*24*3600);
			$("#hf_gb").trigger('click');
		} else {
			alert('请选择皮肤');
		}
	});
	$(".hf_n li").click(function(){
		$(this).addClass('outn');
		$(this).siblings().not(this).removeClass('outn');
	});
	$(".scrollable .items li img").click(function(){$(this).next('p').find('label').trigger('click');});
	$("#select_skin").click(function(){
		$(".huaf").slideDown('fast');
		if ($(this).html() == '换肤') {
			$(this).html('收起');
		} else {
			$(this).html('换肤');
			$("#hf_gb").trigger('click');
		}
	});
	$(".login_li").click(function(){
		$(this).hide();
		$("#login_cue").show();
		$("#login_f").show();
	});
	$("input[name='yhm'], input[name='mim']").focusin(function(){$("#curMsg").html('');});
	$("#login_cue").click(function(){
		$("#login_f, #login_cue").hide();
		$(".login_li").show();
	});
	$("#userTool").hover(function() {
		$(".dlh").show();
		$(this).removeClass('dldt02').addClass('dldt01');
	},function(e){
		e = window.event || e;
		if (!$(e.srcElement || e.target).is('.header .lgoin *,.header .dlh *')) {
			$(".dlh").hide();
			$(this).removeClass('dldt01').addClass('dldt02');
		}
	});
	$(".header .lgoin").hover(function(){}, function(){$(".dlh").hide();$("#userTool").removeClass('dldt01').addClass('dldt02');});
	$(".dlh").hover(function(){$(".dlh").show();$("#userTool").removeClass('dldt02').addClass('dldt01');},function(){$(".dlh").hide();$("#userTool").removeClass('dldt01').addClass('dldt02');});
	$("#tcdl").click(function(){
		var userName = $.trim($("#yhm").val());
		var password = $.trim($("#mim").val());
		$("#curMsg").html('');
		if ($("input[name='remberMe']").is(':checked')) {
			var rememberMe = 1;
		} else {
			var rememberMe = 0;
		}
		
		
		if (userName != '' && password != '' && userName != '用户名' && password != '密码') {
			$("#curMsg").html('正在登录中……');
			$.ajax({
				type: 'POST',
				url:'/login',
				data: 'username='+userName+'&password='+password+'&rememberMe='+rememberMe,
				dataType:'json',
				success:function(e) {
					if (e.code == 0) {
						location.href='/';
					} else {
						$("#curMsg").html(e.msg);
					}
// 					$("#curMsg").html('');
				}
			});
		} else {
			$("#curMsg").html('请输入用户名和密码');
		}
	});
})
</script>