<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<?php echo $this->headTitle(); ?>
<?php 
            echo $this->headLink()->prependStylesheet($this->basePath() . '/styles/FrontEnd/style.css')
            ->prependStylesheet($this->basePath() . '/styles/FrontEnd/common.css');
        ?>
        
        <?php
        echo $this->headScript()->prependFile($this->basePath('js/FrontEnd/comm.js'))
            ->prependFile($this->basePath('js/jquery.min.js'));
       ?>
<style type="text/css"> 
.Calendar { 
font-family:Verdana; 
font-size:9pt; 
background-color:#eee; 
text-align:center; 
width:198px; 
height:158px; 
padding:10px; 
line-height:1.5em; 
} 
.Calendar a{ 
color:#0066CC; 
} 
.Calendar table{ 
width:100%; 
border:0;
	background-color:#eee;
	z-index:50;
} 
.Calendar table thead{color:#acacac;} 
.Calendar table td { 
font-size: 11px; 
padding:1px; 
} 
#idCalendarPre{ 
cursor:pointer; 
float:left; 
padding-right:5px; 
} 
#idCalendarNext{ 
cursor:pointer; 
float:right; 
padding-right:5px; 
} 
#idCalendar td.onToday { 
font-weight:bold; 
color:#C60; 
} 
#idCalendar td.onSelect { 
font-weight:bold; 
} 
</style>
</head>

<body>
<?php echo $this->partial('layout/header.phtml');?>
<?php 
use Custom\Util\Lunar;
?>
<div class="wrap">

<div class="top">
<div class="logo"><a href="/"><img src="/images/FrontEnd/logo.jpg" width="147" height="98" /></a></div> 
<div class="tq">
	<div class="weather"><div class="swith_area"><div class="area_name"></div><div class="switch_b"><a href="javascript:;">[切换]</a></div></div><script type="text/javascript" src="http://ext.weather.com.cn/49388.js"></script><!-- <img src="/images/FrontEnd/tq.jpg" width="572" height="65" /> --></div>
	<div class="lunar">
	<ul>
		<li><span><?php echo date("n月d日");$weekarray=array("日","一","二","三","四","五","六");  
echo "周".$weekarray[date("w")]; ?></span></li>
		<li style="margin-top:8px;"><?php $today = date("Y-m-d");
		$lunar = new Lunar();
		$nl = $lunar->S2L($today);
		echo $nl;?></li>
	</ul>
	<div class="Calendar none"> 
		<div id="idCalendarPre"></div> 
		<div id="idCalendarNext"></div> 
		<span id="idCalendarYear">2008</span>年 <span id="idCalendarMonth">8</span>月 
		<table cellspacing="0"> 
		<thead> 
		<tr> 
		<td>日</td> 
		<td>一</td> 
		<td>二</td> 
		<td>三</td> 
		<td>四</td> 
		<td>五</td> 
		<td>六</td> 
		</tr> 
		</thead> 
		<tbody id="idCalendar"> 
		</tbody> 
		</table> 
	</div>
	</div>
</div>
<div class="btn">
<?php if ($this->container->UserID):?>
<div>欢迎您，<?php echo $this->container->UserName;?></div>
<div><a href="/logout">退出</a></div>
<?php else:?>
<div class="btn_zc"><a href="/register">免费注册</a></div>
<div class="btn_dl"> <a href="/login">请 登 录</a></div>
<?php endif;?>
</div>
</div>

<div class="search">
    <div class="drop_down">
    <div class="drop_down_logo"><img src="/images/FrontEnd/zongh.jpg" width="88" height="26" /></div><div class="drop"><a href="#"><img src="/images/FrontEnd/btn_jj.jpg" width="20" height="19" /></a></div>
    </div>
	<div id="Tab1">
         <div class="Menubox1">
           <ul>
            <li class="hover" date-tab="site">网页</li>
            <li date-tab="news">新闻</li>
            <li date-tab="video">视频</li>
            <li date-tab="image">图片</li>
            <li date-tab="music">音乐</li>
            <li date-tab="map">地图</li>
            <li date-tab="zhidao">问答</li>
            <li date-tab="shopping">购物</li>
            <li date-tab="fly">机票</li>
            <li date-tab="auto">汽车</li>
          </ul>
          </div>
   <div class="Contentbox1"> 
           <div id="con_menu_1" class="hover">
               <div class="search_bg">
                   <div class="search_input">
                     <form id="form1" name="form1" method="post" action="/engine_search" target="_blank">
                       <p>
                         <label for="search_in"></label>
                         <input name="word" type="text" id="search_in" value="输入关键字" />
                         <input type="hidden" name="engine" value="baidu_web" />
                         <input type="hidden" name="tab"  value="site" />
                       </p>
                     </form>
                   </div>
                   
               </div>
<!--             <div class="search_btn"><a href="javascript:;" id="btn_baidu"><img src="/images/FrontEnd/btn_baidu.jpg" width="90" height="39" /></a><a href="javascript:;" id="btn_google"><img src="/images/FrontEnd/btn_google.jpg" width="90" height="39" /></a></div> -->
            <div class="search_btn">
              <input name="badu_btn" type="button" id="badu_btn" value="百度" />
              <input name="google_btn" type="button" id="google_btn" value="Google" />
             </div>
            <div class="search_btn"></div>

       </div>
    
   </div>
  </div>

</div>


<?php echo $this->content;?>



</div>
<?php echo $this->partial('layout/footer.phtml');?>
</body>
</html>
<script type="text/javascript"> 
var jq = function (id) { 
return "string" == typeof id ? document.getElementById(id) : id; 
}; 
var Class = { 
create: function() { 
return function() { 
this.initialize.apply(this, arguments); 
} 
} 
} 
Object.extend = function(destination, source) { 
for (var property in source) { 
destination[property] = source[property]; 
} 
return destination; 
} 
var Calendar = Class.create(); 
Calendar.prototype = { 
initialize: function(container, options) { 
this.Container = jq(container);//table结构容器
this.Days = [];//日期列表 
this.SetOptions(options); 
this.Year = this.options.Year; 
this.Month = this.options.Month; 
this.SelectDay = this.options.SelectDay ? new Date(this.options.SelectDay) : null; 
this.onSelectDay = this.options.onSelectDay; 
this.onToday = this.options.onToday; 
this.onFinish = this.options.onFinish; 
this.Draw(); 
}, 
 
SetOptions: function(options) { 
this.options = {//默认值 
Year: new Date().getFullYear(), 
Month: new Date().getMonth() + 1, 
SelectDay: null,//选择日期 
onSelectDay: function(){}, 
onToday: function(){}, 
onFinish: function(){} 
}; 
Object.extend(this.options, options || {}); 
}, 
//上月 
PreMonth: function() { 
//取得上月日期对象 
var d = new Date(this.Year, this.Month - 2, 1); 
//设置属性 
this.Year = d.getFullYear(); 
this.Month = d.getMonth() + 1; 
//重绘日历 
this.Draw(); 
}, 
//下一个月 
NextMonth: function() { 
var d = new Date(this.Year, this.Month, 1); 
this.Year = d.getFullYear(); 
this.Month = d.getMonth() + 1; 
this.Draw(); 
}, 

Draw: function() { 
//保存日期列表 
var arr = []; 
//用当月第一天在一周中的日期值作为当月离第一天的天数 
for(var i = 1, firstDay = new Date(this.Year, this.Month - 1, 1).getDay(); i <= firstDay; i++){ arr.push(" "); } 
//用当月最后一天在一个月中的日期值作为当月的天数 
for(var i = 1, monthDay = new Date(this.Year, this.Month, 0).getDate(); i <= monthDay; i++){ arr.push(i); } 
// /
var frag = document.createDocumentFragment(); 
this.Days = []; 
while(arr.length > 0){ 
//每个星期插入一个tr
var row = document.createElement("tr"); 
//星期 
for(var i = 1; i <= 7; i++){ 
var cell = document.createElement("td"); 
cell.innerHTML = " "; 
if(arr.length > 0){ 
var d = arr.shift(); 
cell.innerHTML = d; 
if(d > 0){ 
this.Days[d] = cell; 
//获取今日 
if(this.IsSame(new Date(this.Year, this.Month - 1, d), new Date())){ this.onToday(cell); } 
//判断用户是否作了选择
if(this.SelectDay && this.IsSame(new Date(this.Year, this.Month - 1, d), this.SelectDay)){ this.onSelectDay(cell); } 
} 
} 
row.appendChild(cell); 
} 
frag.appendChild(row); 
} 
//此先清空然后再插入(ie的table不能用innerHTML) 
while(this.Container.hasChildNodes()){ this.Container.removeChild(this.Container.firstChild); } 
this.Container.appendChild(frag); 
this.onFinish(); 
}, 
//判断是否同一日
IsSame: function(d1, d2) { 
return (d1.getFullYear() == d2.getFullYear() && d1.getMonth() == d2.getMonth() && d1.getDate() == d2.getDate()); 
} 
}; 
var cale = new Calendar("idCalendar", { 
SelectDay: new Date().setDate(10), 
onSelectDay: function(o){ o.className = "onSelect"; }, 
onToday: function(o){ o.className = "onToday"; }, 
onFinish: function(){ 
jq("idCalendarYear").innerHTML = this.Year; jq("idCalendarMonth").innerHTML = this.Month; 
// var flag = [10,15,20]; 
// for(var i = 0, len = flag.length; i < len; i++){ 
// this.Days[flag[i]].innerHTML = "<a href='javascript:void(0);' onclick=\"alert('您选择的日期是："+this.Year+"/"+this.Month+"/"+flag[i]+"');return false;\">" + flag[i] + "</a>"; 
// 	this.Days[flag[i]].innerHTML = "<a href='javascript:void(0);'>" + flag[i] + "</a>";
// } 
} 
}); 
jq("idCalendarPre").onclick = function(){ cale.PreMonth(); } 
jq("idCalendarNext").onclick = function(){ cale.NextMonth(); } 
$(function(){
	$(".lunar").hover(function(){
		$(".Calendar").slideDown();
	},
	function() {
		$(".Calendar").slideUp();
	});
})
</script>