<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<?php echo $this->headTitle(); ?>
<?php 
            echo $this->headLink()->prependStylesheet($this->basePath() . '/styles/FrontEnd/common.css')
            ->prependStylesheet($this->basePath() . '/styles/FrontEnd/style.css');
        ?>
        
        <?php
        echo $this->headScript()->prependFile($this->basePath('js/FrontEnd/comm.js'))
        	->prependFile($this->basePath('js/FrontEnd/Calendar.js'))
            ->prependFile($this->basePath('js/jquery.min.js'));
       ?>
<style type="text/css"> 
.Calendar .aorange {
	font-size: 14px;
	color: #ff5f07;
	font-family: "黑体",serif;
	font-weight: bold;
}
.Calendar .agreen {
	font-size: 14px;
	color: #55e8df;
	font-weight: bold;
}

.Calendar .one {
	font-family: "黑体",serif;
	font-size: 14px;
	color: #000;
	font-weight: normal;
}

.Calendar .spc {
	color:#ff5f07;
}

.Calendar div,select,p {
	font-size: 12px;
	color:#000;
	margin:1px;
}

.Calendar div#festival {
	color: #d8f6f8; 
	width: 130px; 
	padding: 2px; 
	margin: 0; 
	background-color: #0978a6; 
}
.Calendar div#datedetail {
	width: 130px; 
	border: 0; 
	padding: 2px; 
	margin: 0; 
	background-color:#e8f5f9; 
	text-align:right; 
}
.Calendar div#datedetail span {
	color: #23460f;
}
.Calendar div#detail {
	position: absolute;
	top:20px;
	visibility: hidden;
	margin: 0;
	border:1px solid #a6a8ab;
}

.Calendar div#date {
	width:99%;
	font-size:14px;
	border: 1px solid #a6a8ab; 
	background-color: #e6f0fa;
}
.Calendar div#calendar {
	float:left;
	text-align:center;
	width:290px;
	border: 1px solid #a6a8ab; 
	border-top:0;
	height:auto;
}
.Calendar #calendarhead {
	color: #fafbfb;
	border:0;
	padding:0;
	margin:0;
	background-color: #0978a6;
}

.Calendar #calendarhead tr td {
	width:40px;
	font-weight:bold;
	font-family:"黑体",serif;
	font-size:14px;
	padding:1px;
}

.Calendar div#panel {
	margin:0;
	padding:10px;
	}
.Calendar div#panel div {
	padding:2px;
	margin-top:20px;
	background:#e8f5f9;
	border:1px solid #a6a8ab;
	font-size:9pt;
	cursor:pointer;
}

.Calendar #week {
	background-color: #fcfcfc;
	border:0;
	padding:0;
	margin:0;
}
.Calendar #week tr td {
	padding:1px;
	margin:0;
	width:40px;
	border-bottom: 1px solid #efefef;
	border-left: 1px solid #efefef;
}

.Calendar .tr2 td {
	background-color: #e8f5f9;
}

.Calendar #valid {
	float:left;
	margin:0;
	padding: 30px;
}
.Calendar #valid div {
	padding:2px;
	margin-top:20px;
}
.Calendar #valid a img {
	border:0;
}
</style>
</head>

<body class="<?php echo isset($_COOKIE['bg_class']) ? $_COOKIE['bg_class'] : '';?>">
<?php echo $this->partial('layout/header.phtml');?>
<?php 
use Custom\Util\Lunar;
?>
<div class="wrap">
<?php echo $this->partial('front-end/default/Calendar.phtml');?>
<div class="top">
<div class="logo"><a href="/"><img src="/images/FrontEnd/logo.png" width="147" height="70" /></a></div> 
<div class="tq">
	<div class="weather"><div class="swith_area"><div class="area_name"></div><div class="switch_b"><a href="javascript:;">[切换]</a></div></div><script type="text/javascript" src="http://ext.weather.com.cn/49388.js"></script><!-- <img src="/images/FrontEnd/tq.jpg" width="572" height="65" /> --></div>
	<div class="lunar">
	<ul>
		<li><span><?php echo date("n月d日");$weekarray=array("日","一","二","三","四","五","六");  
echo "周".$weekarray[date("w")]; ?></span></li>
		<li style="margin-top:8px;"><?php $today = date("Y-m-d");
		$lunar = new Lunar();
		$nl = $lunar->S2L($today);
		echo $nl;?></li>
	</ul>
	
	</div>
</div>
<div class="btn">
<div class="btn_dl">
  <input name="search_in3" type="text" id="search_in3" value=" 网盘登录" />
</div>
<div id="disk_login" class="none">
<div class="btn_zc1">
  <input name="search_in3" type="text" id="dsearch_in3" value="网盘登录" />
</div>
<select name="disk_url" id="disk_url">
	<option value="">请选择</option>
	<option value="http://pan.baidu.com/disk/home">百度网盘</option>
	<option value="http://yunpan.360.cn/">360云盘</option>
	<option value="http://wp.163.com/">网易网盘</option>
	<option value="http://www.kuaipan.cn/">金山快盘</option>
</select>
</div>
<div class="btn_zc">
  <input name="search_in2" type="text" id="search_in2" value=" 邮箱登录" />
</div>
<div class="tancmail none">
<div class="btn_zc1">
  <input name="search_in2" type="text" id="dsearch_in2" value="邮箱登录" />
</div>
<div class="btn_zc1">
    <label for="mailxl"></label>
  <select name="mailxl" id="mailxl">
    <option act="http://reg.163.com/CheckUser.jsp" value="@163.com" selected="selected">@163.com</option>
    <option act="https://reg.163.com/logins.jsp" value="@126.com">@126.com</option>
<option act="http://mail.sina.com.cn/cgi-bin/login.cgi" value="@sina.com">@sina.com</option>
<option act="http://passport.sohu.com/login.jsp" value="@sohu.com">@sohu.com</option>
<option act="https://reg.163.com/logins.jsp" value="@yeah.net">@yeah.net</option>
<option act="http://login.mail.tom.com/cgi/login" value="@tom.com">@tom.com</option>
<option act="http://passport.21cn.com/maillogin.jsp" value="@21cn.com">@21cn.com</option>
<option act="https://mail.10086.cn/Login/Login.ashx?clientid=5025" value="@139.com">@139.com</option>
<option style="font-weight:600;" value="以下在弹出页登录">以下在弹出页登录</option>
<option value="@qq.com">@qq.com</option>
<option value="@gmail.com">@gmail.com</option>
<option value="@hotmail.com">@hotmail.com</option>
<option value="阿里云邮箱">阿里云邮箱</option>
<option value="淘宝账号">淘宝账号</option>
<option value="支付宝">支付宝</option>
<option value="新浪微博">新浪微博</option>
<option value="开心网">开心网</option>
<option value="人人网">人人网</option>
<option value="百度">百度</option>
<option value="51.com">51.com</option>
<option value="chinaren校友录">chinaren校友录</option>
<option value="天涯社区">天涯社区</option>
  </select>
</div>
<div class="btn_zc2">
  <input name="search_in3" type="password" id="search_in4" value="邮箱密码" />
</div>
<form target="_blank" method="post" id="mail-form" name="mail-form">
<span class="mail-hide none"></span>
<div class="btn_zc3"><input name="mail_dl" type="button" id="mail_dl" value="登录" /></div>
</form>
</div>
</div>
</div>


<div class="search">
    <div class="drop_down">
    <div class="drop_down_logo"><img src="/images/FrontEnd/zongh.jpg" width="88" height="26" /></div><div class="drop"><a href="#"><img src="/images/FrontEnd/btn_jj.jpg" width="20" height="19" /></a></div>
    </div>
	<div id="Tab1">
         <div class="Menubox1">
           <ul>
            <li class="hover" date-tab="site">网页</li>
            <li date-tab="news">新闻</li>
            <li date-tab="video">视频</li>
            <li date-tab="image">图片</li>
            <li date-tab="music">音乐</li>
            <li date-tab="map">地图</li>
            <li date-tab="zhidao">问答</li>
            <li date-tab="shopping">购物</li>
            <li date-tab="fly">机票</li>
            <li date-tab="auto">汽车</li>
          </ul>
          </div>
   <div class="Contentbox1"> 
           <div id="con_menu_1" class="hover">
               <div class="search_bg">
                   <div class="search_input">
                     <form id="form1" name="form1" method="post" action="/engine_search" target="_blank">
                       <p>
                         <label for="search_in"></label>
                         <input name="word" type="text" id="search_in" value="输入关键字" />
                         <input type="hidden" name="engine" value="baidu_web" />
                         <input type="hidden" name="tab"  value="site" />
                       </p>
                     </form>
                   </div>
                   
               </div>
<!--             <div class="search_btn"><a href="javascript:;" id="btn_baidu"><img src="/images/FrontEnd/btn_baidu.jpg" width="90" height="39" /></a><a href="javascript:;" id="btn_google"><img src="/images/FrontEnd/btn_google.jpg" width="90" height="39" /></a></div> -->
            <div class="search_btn">
              <input name="badu_btn" type="button" id="badu_btn" value="百度" />
              <input name="google_btn" type="button" id="google_btn" value="Google" />
             </div>
            <div class="search_btn"></div>

       </div>
    
   </div>
  </div>

</div>

<?php echo $this->content;?>


</div>

<?php echo $this->partial('layout/footer.phtml');?>
</body>
</html>
<script type="text/javascript"> 

$(function(){
	initial();
	$(".lunar").hover(function(){
		var t = $(this).offset();
		$(".Calendar").css({position:'absolute',left:t.left+'px',top:t.top+'px'}).slideDown();
	},
	function() {
// 		$(".Calendar").slideUp();
	});
	$(".Calendar").hover(function(e){
		e = window.event || e;
		if (!$(e.srcElement || e.target).is('.tq .lunar *,.Calendar *, #sy *')) {
			$(".Calendar").slideUp();
		}
	},function(e){
		e = window.event || e;
		if (!$(e.srcElement || e.target).is('#sy,#sm')) {
			$(".Calendar").slideUp();
		}
	});
// 	var mailDomain = {@163.com:'http://reg.163.com/CheckUser.jsp',}
	$("#dsearch_in2").focusin(function(){
		if ($(this).val() == '邮箱登录') {
			$(this).val('');
		}
	});
	$("#dsearch_in2").focusout(function(){
		if ($(this).val() == '') {
			$(this).val('邮箱登录');
		}
	});
	$("#search_in4").focusin(function(){
		if ($(this).val() == '邮箱密码') {
			$(this).val('');
		}
	});
	$("#mail_dl").click(function(){
		var optVal = $("select[name='mailxl']").val();
		var optAct = $("select[name='mailxl']").find('option:selected').attr('act');
		var p = $("#search_in4").val();
		var u = $("#dsearch_in2").val();
		if (typeof optAct != 'undefined') {
			switch(optVal) {
			  case '@163.com':
				  $(".mail-hide").html('<input type="hidden" name="url" value="http://entry.mail.163.com/coremail/fcg/ntesdoor2?lightweight=1&verifycookie=1&language=-1&style=15"><input type="hidden" name="username" value="'+u+'"><input type="hidden" name="password" value="'+p+'">');
				  break;
			  case '@126.com':
				  $(".mail-hide").html('<input type="hidden" name="domain" value="126.com">'
						  +'<input type="hidden" name="username" value="'+u+'@126.com">'
						  +'<input type="hidden" name="password" value="'+p+'">'
						  +'<input type="hidden" name="url" value="http://entry.mail.126.com/cgi/ntesdoor?lightweight%3D1%26verifycookie%3D1%26language%3D0%26style%3D-1">');
				  break;
			  case '@sina.com':
				  $(".mail-hide").html('<input type="hidden" name="u" value="'+u+'@sina.com">'
						  +'<input type="hidden" name="psw" value="'+p+'">');
				  break;
			  case '@sohu.com':
				  $(".mail-hide").html('<input type="hidden" name="loginid" value="'+u+'@sohu.com">'
						  +'<input type="hidden" name="passwd" value="'+p+'">'
						  +'<input type="hidden" name="fl" value="1">'
						  +'<input type="hidden" name="vr" value="1|1">'
						  +'<input type="hidden" name="appid" value="1000">'
						  +'<input type="hidden" name="ru" value="http://login.mail.sohu.com/servlet/LoginServlet">'
						  +'<input type="hidden" name="ct" value="1173080990">'
						  +'<input type="hidden" name="sg" value="5082635c77272088ae7241ccdf7cf062">');
				  break;
			  case '@yeah.net':
				  $(".mail-hide").html('<input type="hidden" name="domain" value="yeah.net">'
						  +'<input type="hidden" name="username" value="'+u+'@yeah.net">'
						  +'<input type="hidden" name="password" value="'+p+'">'
						  +'<input type="hidden" name="url" value="http://entry.mail.yeah.net/cgi/ntesdoor?lightweight%3D1%26verifycookie%3D1%26style%3D-1">');
				  break;
			  case '@tom.com':
				  $(".mail-hide").html('<input type="hidden" name="user" value="'+u+'">'
						  +'<input type="hidden" name="pass" value="'+p+'">');
				  break;
			  case '@21cn.com':
				  $(".mail-hide").html('<input type="hidden" name="UserName" value="'+u+'@21cn.com">'
						  +'<input type="hidden" name="passwd" value="'+p+'">'
						  +'<input type="hidden" name="domainname" value="21cn.com">');
				  break;
			  case '@139.com':
				  $(".mail-hide").html('<input type="hidden" name="UserName" value="'+u+'">'
						  +'<input type="hidden" name="Password" value="'+p+'">'
						  +'<input type="hidden" name="ClientId" value="5025">');
				  break;
			  default:
				  break;
			}
			  $("#mail-form").attr('action', optAct).submit();
		}
	});
	$("#mailxl").change(function(){
		var optVal = $("select[name='mailxl']").val();
		switch(optVal) {
		case '@qq.com':
			window.open('http://mail.qq.com');
			break;
		case '@gmail.com':
			window.open('http://mail.google.com');
			break;
		case '@hotmail.com':
			window.open('http://www.hotmail.com');
			break;
		case '阿里云邮箱':
			window.open('https://passport.alipay.com/login/login.htm?return_url=http%3A%2F%2Fmail.aliyun.com%2Falimail%2Fauth%2FcallbackForHavana%3Freurl%3D%252Falimail%252F&fromSite=9');
			break;
		case '淘宝账号':
			window.open('https://login.taobao.com/member/login.jhtml');
			break;
		case '支付宝':
			window.open('https://www.alipay.com/user/login.htm');
			break;
		case '新浪微博':
			window.open('http://t.sina.com.cn/');
			break;
		case '开心网':
			window.open('http://www.kaixin001.com/');
			break;
		case '人人网':
			window.open('http://www.renren.com');
			break;
		case '百度':
			window.open('https://passport.baidu.com/?login');
			break;
		case '51.com':
			window.open('http://www.51.com/');
			break;
		case 'chinaren校友录':
			window.open('http://class.chinaren.com/');
			break;
		case '天涯社区':
			window.open('http://www.tianya.cn/');
			break;
		default:
			break;
		}
	});
	$("#disk_url").change(function(){var url = $(this).val();if (url != '') {window.open(url);}});
	$("#search_in2").click(function(){
		$(".tancmail").show();
	});
	$("#search_in3").click(function(){
		$("#disk_login").removeClass('none');
	});
	$(document).click(function(e){
		e = window.event || e;
		if (!$(e.srcElement || e.target).is(".tancmail *") && !$(e.srcElement || e.target).is("#search_in2")) {
			$(".tancmail").hide();
		}
		if (!$(e.srcElement || e.target).is("#search_in3") && !$(e.srcElement || e.target).is("#disk_login *")) {
			$("#disk_login").addClass('none');
		}
	});
	$(document).mouseover(function(e){
		e = window.event || e;
		if (!$(e.srcElement || e.target).is("#con_men_1 *")) {
			$("#con_men_1 .menu_k").hide();
			$(".menu > li").removeClass('menu_a');
		}
	});
})
</script>