<?php
$this->headScript()->appendFile($this->basePath('js/jquery-ui-1.10.2.custom.min.js'))
					->appendFile($this->basePath('js/jquery.ajaxfileupload.js'));
$msg = $this->flashMessages();
?>
<div class="box">
    <div class="box-header">
        <div class="t_top">
        	<div class="t_inline">
        <form class="form-inline" action="<?php echo $this->url('backend', array('controller' 
            => 'promotion', 'action' => 'index')); ?>" method="get">
                <div class="input-group">
                	<label>分类</label>
                    <select name="cid">
                    <?php foreach ($this->rule_type as $k=>$v):?>
                    	<option value="<?php echo $k;?>" <?php echo $this->cid==$k ? 'selected=selected' : '';?>><?php echo $v;?></option>
                    <?php endforeach;?>
                    </select>
                    <input autocomplete="off" class="input-element span3" name="title" type="text">
                <button class="button-element" type="submit">搜索</button>
                </div>
        </form>
        	</div>
        	<p class='t_right'>
        	<!-- <a class="btn btn-return" href="<?php echo $this->url('backend' 
            , array('controller' => 'nav' , 'action' => 'category'))?>">
        <i class="icon-plus"></i>返回</a> -->
        	<a class="btn btn-success" href="<?php echo $this->url('backend' 
            , array('controller' => 'promotion' , 'action' => 'save'));?>">
        <i class="icon-plus"></i>新增</a>
        <a class="btn btn-edit" href="javascript:;" _href="<?php echo $this->url('backend', array('controller' 
                                => 'promotion', 'action' => 'save')) ?>?id=">
                                <i class="icon-edit"></i>编辑
                            </a>
                            <a class="btn btn-delete" href="javascript:;" _href="<?php echo $this->url('backend', array('controller' 
                                => 'promotion', 'action' => 'delete')) ?>?id=" onClick="diyConfirm('删除' , $(this).attr('href'), this);return false;"><i class="icon-delete"></i>删除
                            </a>
        </p>
        </div>
    </div>
    <div class="box-content">
    <?php if(!empty($msg['error'])):?>
            <div class="alert alert-error fade in">
            <button class="close" data-dismiss="alert" type="button">×</button>
            <?php foreach($msg['error'] as $v):?>
            <p><?php echo $v;?></p>
            <?php endforeach;?>
            </div>
            <?php endif;?>
            
            <?php if(!empty($msg['success'])):?>
            <div class="alert alert-success fade in">
            <button class="close" data-dismiss="alert" type="button">×</button>
            <?php foreach($msg['success'] as $v):?>
            <p><?php echo $v;?></p>
            <?php endforeach;?>
            </div>
            <?php endif;?>
        <table class="table" id="table1">
            <thead>
                <tr class="row">
                	<th>全选<input type="checkbox" name="select_all" value="all"/></th>
                    <th>编号</th>
                    <th>
                    <?php if (isset($this->order['type_name'])):?>
                    <?php $name = $this->order['type_name'];?>
                    <a href="<?php echo $name['href'];?>">活动分类<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	活动分类
                    <?php endif;?>
                    	</th>
                    <th  key="points" editable="true">
                    <?php if (isset($this->order['points'])):?>
                    <?php $name = $this->order['points'];?>
                    <a href="<?php echo $name['href'];?>">积分基数<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	积分基数
                    <?php endif;?>
                    </th>
                    <th>
                    <?php if (isset($this->order['start_time'])):?>
                    <?php $name = $this->order['start_time'];?>
                    <a href="<?php echo $name['href'];?>">开始时间<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	开始时间
                    <?php endif;?>
                    </th>
                    <th>
                    <?php if (isset($this->order['end_time'])):?>
                    <?php $name = $this->order['end_time'];?>
                    <a href="<?php echo $name['href'];?>">结束时间<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	结束时间
                    <?php endif;?>
                    </th>
                    <th key="is_active" editable="true">
                    <?php if (isset($this->order['is_active'])):?>
                    <?php $name = $this->order['is_active'];?>
                    <a href="<?php echo $name['href'];?>">是否启用<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	是否启用
                    <?php endif;?>
                    </th>
                    <th>
                    <?php if (isset($this->order['last_update'])):?>
                    <?php $name = $this->order['last_update'];?>
                    <a href="<?php echo $name['href'];?>">更新时间<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	更新时间
                    <?php endif;?>
                    </th>
                    <th>
                    <?php if (isset($this->order['updateUser'])):?>
                    <?php $name = $this->order['updateUser'];?>
                    <a href="<?php echo $name['href'];?>">更新人<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	更新人
                    <?php endif;?>
                    </th>
                </tr>
            </thead>
            <tfoot>
                <tr class="row">
                	<th>全选<input type="checkbox" name="select_all" value="all"/></th>
                    <th>编号</th>
                    <th>
                    <?php if (isset($this->order['type_name'])):?>
                    <?php $name = $this->order['type_name'];?>
                    <a href="<?php echo $name['href'];?>">活动类型<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	活动类型
                    <?php endif;?>
                    	</th>
                    <th  key="points" editable="true">
                    <?php if (isset($this->order['points'])):?>
                    <?php $name = $this->order['points'];?>
                    <a href="<?php echo $name['href'];?>">积分基数<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	积分基数
                    <?php endif;?>
                    </th>
                    <th>
                    <?php if (isset($this->order['start_time'])):?>
                    <?php $name = $this->order['start_time'];?>
                    <a href="<?php echo $name['href'];?>">开始时间<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	开始时间
                    <?php endif;?>
                    </th>
                    <th>
                    <?php if (isset($this->order['end_time'])):?>
                    <?php $name = $this->order['end_time'];?>
                    <a href="<?php echo $name['href'];?>">结束时间<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	结束时间
                    <?php endif;?>
                    </th>
                    <th key="is_active" editable="true">
                    <?php if (isset($this->order['is_active'])):?>
                    <?php $name = $this->order['is_active'];?>
                    <a href="<?php echo $name['href'];?>">是否启用<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	是否启用
                    <?php endif;?>
                    </th>
                    <th>
                    <?php if (isset($this->order['last_update'])):?>
                    <?php $name = $this->order['last_update'];?>
                    <a href="<?php echo $name['href'];?>">更新时间<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	更新时间
                    <?php endif;?>
                    </th>
                    <th>
                    <?php if (isset($this->order['updateUser'])):?>
                    <?php $name = $this->order['updateUser'];?>
                    <a href="<?php echo $name['href'];?>">更新人<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	更新人
                    <?php endif;?>
                    </th>
                </tr>
            </tfoot>
            <tbody>
                <?php $startNumber = $this->startNumber;foreach ($this->lists as $pro): ?>
                    <tr class="row" key="id" primary_value="<?php echo $pro['id']; ?>">
                    	<td width="60"><input type="checkbox" name="select" value="<?php echo $pro['id']; ?>" data-key="促销" data-value="<?php echo $pro['type_name']; ?>" /></td>
                        <td><?php echo $startNumber++;?></td>
                        <td><?php echo $pro['type_name'];?></td>
                        <td key="points" editable="true"><?php echo $pro['points']; ?></td>
                        <td><?php echo $pro['start_time']; ?></td>
                        <td><?php echo $pro['end_time']; ?></td>
                        <td key="is_active" editable="true"><?php echo $pro['is_active'] ? '启用' : '未启用'; ?></td>
                        <td><?php echo $pro['last_update']; ?></td>
                        <td><?php echo $pro['updateUser']; ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
        <?php echo $this->paginationControl($this->paginaction,'Sliding','layout/pagination' , array('link' 
            => $this->url('backend' , array('controller' => 'promotion' , 'action' => 'index')).'?'.$this->query));?>
    </div>
</div>
<script type="text/javascript">
<!--
var productEditableParam={
		'postUrl':'/index/updateColumn',
		'primary_key':'id',
		'table':'PromotionTable',
		'is_active':{
			type:'radio',
	        group:{
	            1:'启用',
	            0:'未启用'
	        }
		},
		'points':{
			type:'text',
			reg: /^\d+$/,
			tip:'只能为数字!'
		}
	};
var options={
		tableID:'table1',
		editableParam:productEditableParam
}
new Editable(options,$("#table1"));
$(function() {
	$("select[name='cid']").change(function(){
		$("button.button-element[type='submit']").click();
	});
})
//-->
</script>