<?php
$this->headScript()->prependFile($this->basePath('js/jquery.min.js'))
->appendFile($this->basePath('js/BackEnd/validator.js'))
->appendFile($this->basePath('js/BackEnd/login.js'));
$msg = $this->flashMessages();
?>
<div></div>

<div id=user_login>
<dl>
  <dd id=user_top>
  <ul>
    <li class=user_top_l></li>
    <li class=user_top_c></li>
    <li class=user_top_r></li>
  </ul>
  <dd id=user_main>
  <form  class="form-login" method="post" action="<?php echo $this->url('backend' , array('controller' => 'login' , 'action' => 'submit'));?>">
  <ul>
    <li class=user_main_l></li>
    <li class=user_main_c>
    <div class=user_main_box>
    <ul>
      <li class=user_main_text>用户名： </li>
      <li class=user_main_input>
      	<input class=TxtUserNameCssClass id=TxtUserName 
      maxLength=20 name="username"> 
      </li>
    </ul>
    <ul>
      <li class=user_main_text>密 码： </li>
      <li class=user_main_input>
      <input class=TxtPasswordCssClass id=TxtPassword 
      type=password name="password"> </li>
     </ul>
     <ul>
     <?php if(!empty($msg['error'])):?>
            <div class="alert alert-error fade in">
            <?php foreach($msg['error'] as $v):?>
            <p><?php echo $v;?></p>
            <?php endforeach;?>
            </div>
            <?php endif;?>
            
            <?php if(!empty($msg['success'])):?>
            <div class="alert alert-success fade in">
            <?php foreach($msg['success'] as $v):?>
            <p><?php echo $v;?></p>
            <?php endforeach;?>
            </div>
            <?php endif;?>
     <?php if($this->msg):?>
    <?php foreach($this->msg as $msg):?>
    <li class="help-block"><i class="icon-warning-sign"></i><?php echo $msg;?></li>
    <?php endforeach;?>
    <?php endif;?>
     </ul>
    </div>
    </li>
    <li class=user_main_r><input class=IbtnEnterCssClass id=IbtnEnter 
    style="BORDER-TOP-WIDTH: 0px; BORDER-LEFT-WIDTH: 0px; BORDER-BOTTOM-WIDTH: 0px; BORDER-RIGHT-WIDTH: 0px" 
    type=image src="/images/BackEnd/user_botton.gif" name=IbtnEnter> </li></ul>
    </form>
  <dd id=user_bottom>
  <ul>
    <li class=user_bottom_l></li>
    <li class=user_bottom_c><span style="MARGIN-TOP: 40px">&nbsp;</span> </li>
    <li class=user_bottom_r></li></ul></dd></dl></div>
    <span id=ValrUserName style="DISPLAY: none; COLOR: red"></span><span id=ValrPassword 
style="DISPLAY: none; COLOR: red"></span><span id=ValrValidateCode 
style="DISPLAY: none; COLOR: red"></span>
<div id=ValidationSummary1 style="DISPLAY: none; COLOR: red"></div>

<div></div>
<script type="text/javascript">
$(function(){
	$("#TxtUserName").focus();
})
</script>