<?php
/**
* save.phtml
*-------------------------
*
* 
*
* PHP versions 5
*
* LICENSE: This source file is from Smarter Ver2.0, which is a comprehensive shopping engine 
* that helps consumers to make smarter buying decisions online. We empower consumers to compare 
* the attributes of over one million products in the common channels and common categories
* and to read user product reviews in order to make informed purchase decisions. Consumers can then 
* research the latest promotional and pricing information on products listed at a wide selection of 
* online merchants, and read user reviews on those merchants.
* The copyrights is reserved by http://www.mezimedia.com. 
* Copyright (c) 2006, Mezimedia. All rights reserved.
*
* @author Yaron Jiang <yjiang@corp.valueclick.com.cn>
* @copyright (C) 2004-2013 Mezimedia.com
* @license http://www.mezimedia.com PHP License 5.0
* @version CVS: $Id: save.phtml,v 1.1 2013/04/15 10:57:15 rock Exp $
* @link http://www.dahongbao.com/
* @deprecated File deprecated in Release 3.0.0
*/

$form = $this->form;
?>
<div class="box">
    <div class="box-header">
        <h2><i class="icon-box"></i>资源编辑</h2>
        <div class="t_top">
    <p class='t_right'>
        <a class="btn btn-return" href="<?php echo $this->url('backend' 
            , array('controller' => 'resource' , 'action' => 'index'))?>">
        <i class="icon-plus"></i>返回</a>
    <a class="btn btn-submit" href="javascript:;">
        <i class="icon-plus"></i>保存</a>
        <a class="btn btn-reset" href="javascript:;">
        <i class="icon-plus"></i>重填</a>
    </p>
    </div>
    </div>
    
    <div class="box-content">
        <form class="box-form" action="<?php echo $this->url('backend' , array('controller' => 'resource'
            , 'action' => 'save'));?>" method="post">
        <?php echo $this->formText($form->get('Name'))?>
        <?php echo $this->formText($form->get('Controller'))?>
        <?php echo $this->formText($form->get('ControllerName'))?>
        <?php echo $this->formText($form->get('Action'))?>
        <?php echo $this->formText($form->get('ActionName'))?>
        <?php echo $this->formHidden($form->get('ResourceID'))?>
        <?php echo $this->formSubmit($form->get('submit') , '提交')?>
        </form>
    </div>
</div>