<?php
$this->headScript()->appendFile($this->basePath('js/jquery-ui-1.10.2.custom.min.js'));
$msg = $this->flashMessages();?>
<div class="box">
    <div class="box-header">
<!--         <h2><i class="icon-box"></i>广告申请</h2> -->
        <div class="t_top">
            <div class="t_inline">
        	<form class="form-inline" action="<?php echo $this->url('backend', array('controller' 
            => 'site', 'action' => 'advApply')); ?>" method="get">
                <div class="input-group">
                    <input autocomplete="off" class="input-element span3" value="<?php echo isset($this->k) ? $this->k : '';?>" name="k" type="text">
                    
                <button class="button-element" type="submit">搜索</button>
                </div>
        	</form>
        	</div>
        	<p class='t_right'>
        <a class="btn btn-delete" href="javascript:;" _href="<?php echo $this->url('backend', array('controller' 
                                => 'site', 'action' => 'deleteAdvApply')) ?>?id=" onClick="diyConfirm('删除' , $(this).attr('href'), this);return false;"><i class="icon-delete"></i>删除
                            </a>
        </p>
        </div>
    </div>
    <div class="box-content">
    <?php if(!empty($msg['error'])):?>
            <div class="alert alert-error fade in">
            <button class="close" data-dismiss="alert" type="button">×</button>
            <?php foreach($msg['error'] as $v):?>
            <p><?php echo $v;?></p>
            <?php endforeach;?>
            </div>
            <?php endif;?>
            
            <?php if(!empty($msg['success'])):?>
            <div class="alert alert-success fade in">
            <button class="close" data-dismiss="alert" type="button">×</button>
            <?php foreach($msg['success'] as $v):?>
            <p><?php echo $v;?></p>
            <?php endforeach;?>
            </div>
            <?php endif;?>
        <table class="table" id="table1">
            <thead>
                <tr class="row">
                	<th>全选<input type="checkbox" name="select_all" value="all"/></th>
                    <th>编号</th>
                    <th key="title" editable="true">
                    <?php if (isset($this->order['title'])):?>
                    <?php $name = $this->order['title'];?>
                    <a href="<?php echo $name['href'];?>">网站名称<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	网站名称
                    <?php endif;?>
                    	</th>
                    <th key="url" editable="true">
                    <?php if (isset($this->order['url'])):?>
                    <?php $name = $this->order['url'];?>
                    <a href="<?php echo $name['href'];?>">网址<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	网址
                    <?php endif;?>
                    </th>
                    
                    <th>
                    <?php if (isset($this->order['QQ'])):?>
                    <?php $name = $this->order['QQ'];?>
                    <a href="<?php echo $name['href'];?>">QQ<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	QQ
                    <?php endif;?>
                    </th>
                    <th>
                    <?php if (isset($this->order['email'])):?>
                    <?php $name = $this->order['email'];?>
                    <a href="<?php echo $name['href'];?>">Email<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	Email
                    <?php endif;?>
                    </th>
                    <th>
                    <?php if (isset($this->order['tel'])):?>
                    <?php $name = $this->order['tel'];?>
                    <a href="<?php echo $name['href'];?>">电话<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	电话
                    <?php endif;?>
                    </th>
                    <th>
                    <?php if (isset($this->order['position'])):?>
                    <?php $name = $this->order['position'];?>
                    <a href="<?php echo $name['href'];?>">投放位置<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	投放位置
                    <?php endif;?>
                    </th>
                    <th>
                    <?php if (isset($this->order['build_time'])):?>
                    <?php $name = $this->order['build_time'];?>
                    <a href="<?php echo $name['href'];?>">建站时间<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	建站时间
                    <?php endif;?>
                    </th>
                    <th>
                    <?php if (isset($this->order['dailyView'])):?>
                    <?php $name = $this->order['dailyView'];?>
                    <a href="<?php echo $name['href'];?>">日访问量<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	日访问量
                    <?php endif;?>
                    </th>
                    <th>
                    <?php if (isset($this->order['summary'])):?>
                    <?php $name = $this->order['summary'];?>
                    <a href="<?php echo $name['href'];?>">网站介绍<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	网站介绍
                    <?php endif;?>
                    </th>
                    <th>
                    <?php if (isset($this->order['ip'])):?>
                    <?php $name = $this->order['ip'];?>
                    <a href="<?php echo $name['href'];?>">ip<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	ip
                    <?php endif;?>
                    </th>
                    <th>
                    <?php if (isset($this->order['add_time'])):?>
                    <?php $name = $this->order['add_time'];?>
                    <a href="<?php echo $name['href'];?>">提交时间<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	提交时间
                    <?php endif;?>
                    </th>
                </tr>
            </thead>
            <tfoot>
                <tr class="row">
                	<th>全选<input type="checkbox" name="select_all" value="all"/></th>
                    <th>编号</th>
                    <th key="title" editable="true">
                    <?php if (isset($this->order['title'])):?>
                    <?php $name = $this->order['title'];?>
                    <a href="<?php echo $name['href'];?>">网站名称<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	网站名称
                    <?php endif;?>
                    	</th>
                    <th key="url" editable="true">
                    <?php if (isset($this->order['url'])):?>
                    <?php $name = $this->order['url'];?>
                    <a href="<?php echo $name['href'];?>">网址<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	网址
                    <?php endif;?>
                    </th>
                    
                    <th>
                    <?php if (isset($this->order['QQ'])):?>
                    <?php $name = $this->order['QQ'];?>
                    <a href="<?php echo $name['href'];?>">QQ<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	QQ
                    <?php endif;?>
                    </th>
                    <th>
                    <?php if (isset($this->order['email'])):?>
                    <?php $name = $this->order['email'];?>
                    <a href="<?php echo $name['href'];?>">Email<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	Email
                    <?php endif;?>
                    </th>
                    <th>
                    <?php if (isset($this->order['tel'])):?>
                    <?php $name = $this->order['tel'];?>
                    <a href="<?php echo $name['href'];?>">电话<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	电话
                    <?php endif;?>
                    </th>
                    <th>
                    <?php if (isset($this->order['position'])):?>
                    <?php $name = $this->order['position'];?>
                    <a href="<?php echo $name['href'];?>">投放位置<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	投放位置
                    <?php endif;?>
                    </th>
                    <th>
                    <?php if (isset($this->order['build_time'])):?>
                    <?php $name = $this->order['build_time'];?>
                    <a href="<?php echo $name['href'];?>">建站时间<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	建站时间
                    <?php endif;?>
                    </th>
                    <th>
                    <?php if (isset($this->order['dailyView'])):?>
                    <?php $name = $this->order['dailyView'];?>
                    <a href="<?php echo $name['href'];?>">日访问量<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	日访问量
                    <?php endif;?>
                    </th>
                    <th>
                    <?php if (isset($this->order['summary'])):?>
                    <?php $name = $this->order['summary'];?>
                    <a href="<?php echo $name['href'];?>">网站介绍<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	网站介绍
                    <?php endif;?>
                    </th>
                    <th>
                    <?php if (isset($this->order['ip'])):?>
                    <?php $name = $this->order['ip'];?>
                    <a href="<?php echo $name['href'];?>">ip<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	ip
                    <?php endif;?>
                    </th>
                    <th>
                    <?php if (isset($this->order['add_time'])):?>
                    <?php $name = $this->order['add_time'];?>
                    <a href="<?php echo $name['href'];?>">提交时间<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	提交时间
                    <?php endif;?>
                    </th>
                </tr>
            </tfoot>
            <tbody>
                <?php $startNumber = $this->startNumber;foreach ($this->lists as $nav): ?>
                    <tr class="row" key="id" primary_value="<?php echo $nav['id']; ?>">
                    	<td width="60"><input type="checkbox" name="select" value="<?php echo $nav['id']; ?>" data-key="网站名称" data-value="<?php echo $nav['title']; ?>" /></td>
                        <td><?php echo $startNumber++;?></td>
                        <td><?php echo $nav['title']; ?></td>
                        <td><a href="<?php echo $nav['url']; ?>" target="_blank" title="<?php echo $nav['title'];?>"><?php echo $nav['url']; ?></a></td>
                        <td><?php echo $nav['QQ']; ?></td>
                        <td><?php echo $nav['email']; ?></td>
                        <td><?php echo $nav['tel']; ?></td>
                        <td><?php echo $nav['position']; ?></td>
                        <td><?php echo $nav['build_time']; ?></td>
                        <td><?php echo $nav['dailyView']; ?></td>
                        <td><?php echo $nav['summary']; ?></td>
                        <td><?php echo $nav['ip']; ?></td>
                        <td><?php echo $nav['add_time']; ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
        <?php echo $this->paginationControl($this->paginaction,'Sliding','layout/pagination' , array('link' 
            => $this->url('backend' , array('controller' => 'site' , 'action' => 'advApply')).'?'.$this->query));?>
    </div>
</div>