<?php 

?>
<div class="box">
<!-- <p style="text-indent: 2em; font-size:20px;margin:50px; text-align:center; height:400px;">
Welcome to Easy Content Managent System!
</p> -->
	<div>
	<table class="index_table">
		<tr>
			<td>
			<h3>会员统计</h3>
			<ul>
				<li><span class="left_sort">今日新注册：</span><span class="red"><?php echo $memberStatist->todayTotal;?></span>个</li>
				<li><span class="left_sort">本周新注册：</span><span class="red"><?php echo $memberStatist->weekTotal;?></span>个</li>
				<li><span class="left_sort">本月新注册：</span><span class="red"><?php echo $memberStatist->monthTotal;?></span>个</li>
				<li><span class="left_sort">本季度新注册：</span><span class="red"><?php echo $memberStatist->quarterTotal;?></span>个</li>
				<li><span class="left_sort">本年新注册：</span><span class="red"><?php echo $memberStatist->yearTotal;?></span>个</li>
				<li><span class="left_sort">会员总数：</span><span class="red"><?php echo $memberStatist->allTotal;?></span>个</li>
			</ul>
			</td>
			<td>
			<h3>订单统计</h3>
			<ul>
				<li><span class="left_sort">今日新单：</span><span class="red"><?php echo 0;?></span>个</li>
				<li><span class="left_sort">今日新单：</span><span class="red"><?php echo 0;?></span>个</li>
				<li><span class="left_sort">今日新单：</span><span class="red"><?php echo 0;?></span>个</li>
				<li><span class="left_sort">今日新单：</span><span class="red"><?php echo 0;?></span>个</li>
				<li><span class="left_sort">今日新单：</span><span class="red"><?php echo 0;?></span>个</li>
				<li><span class="left_sort">今日新单：</span><span class="red"><?php echo 0;?></span>个</li>
			</ul>
			</td>
		</tr>
	</table>
	</div>
</div>