<?php
$this->headLink()->appendStylesheet($this->basePath('styles/jquery.cleditor.css'));
$this->headScript()->appendFile($this->basePath('js/jquery.cleditor.min.js'));
$config = $this->config;
?>
<div class="box">
    <div class="box-header">
        <h2><i class="icon-box"></i><?php echo $this->cateTitle;?></h2>
    </div>
    <div class="box-content">
    <form method="post" action="" enctype= "multipart/form-data"=>
    <fieldset>
    <?php foreach($config as $k=>$v) :?>
         <div class="input-group">
         	<label for="<?php echo $v->cKey;?>" class="input-label"><?php echo $v->cName;?></label>
         	<?php if ('text' == $v->cType):?>
         	<div class="input-item"><input autocomplete="off" type="text" value="<?php echo $v->cValue;?>" name="<?php echo $v->cKey;?>" class="input-element"></div>
         	<?php elseif ('password' == $v->cType):?>
         	<div class="input-item"><input type="password" value="<?php echo $v->cValue;?>" name="<?php echo $v->cKey;?>" class="input-element"></div>
         	<?php elseif ('select' == $v->cType):?>
         	<div class="input-item">
         	<select class="input-element select-element" name="<?php echo $v->cKey;?>">
         	<?php $select = explode('|', $v->cRange);$selectName = explode('|', $v->cRangeName);?>
         	<?php foreach($select as $key=>$val):?>
         	<option value="<?php echo $val;?>" <?php echo $v->cValue==$val ? "selected=selected" : '';?>><?php echo $selectName[$key];?></option>
         	<?php endforeach;?>
			</select>
         	</div>
         	<?php elseif ('file' == $v->cType):?>
         	<div class="input-item"><input type="file" value="<?php echo $v->cValue;?>" name="<?php echo $v->cKey;?>" class="input-element"></div>
         	<?php if (!empty($v->cValue)):?>
         	<div class="input-item" style="margin-top: 6px;">
				<img  src="<?php echo $v->cValue;?>" />
				</div>
         	<?php endif;?>
         	<?php elseif ('edit' == $v->cType):?>
         	<div class="input-item"><textarea class="cleditor" type="text" name="<?php echo $v->cKey;?>" class="input-element"><?php echo $v->cValue;?></textarea>
         	<?php if (!empty($v->summary)):?>
         	<span class="help-inline note"><i class="icon-info-sign"></i>
         	<?php echo $v->summary;?>
         	</span>
         	<?php endif;?>
         	</div>
         	<?php endif;?>
         </div>
    <?php endforeach;?>
    <div class="button-group"><input type="submit" value="提交保存" name="submit" class="button-element"></div>
    </fieldset>
    </form>
    </div>
</div>
<script>
$(function(){
    
    $(".cleditor").cleditor({
        width:        600, // width not including margins, borders or padding
        height:       300, // height not including margins, borders or padding
        controls:     // controls to add to the toolbar
                      "bold italic underline strikethrough subscript superscript | font size " +
                      "style | color highlight removeformat | bullets numbering | outdent " +
                      "indent | alignleft center alignright justify | undo redo | " +
                      "rule image link unlink | cut copy paste pastetext | print source",
        colors:       // colors in the color popup
                      "FFF FCC FC9 FF9 FFC 9F9 9FF CFF CCF FCF " +
                      "CCC F66 F96 FF6 FF3 6F9 3FF 6FF 99F F9F " +
                      "BBB F00 F90 FC6 FF0 3F3 6CC 3CF 66C C6C " +
                      "999 C00 F60 FC3 FC0 3C0 0CC 36F 63F C3C " +
                      "666 900 C60 C93 990 090 399 33F 60C 939 " +
                      "333 600 930 963 660 060 366 009 339 636 " +
                      "000 300 630 633 330 030 033 006 309 303",    
        fonts:        // font names in the font popup
                      "Arial,Arial Black,Comic Sans MS,Courier New,Narrow,Garamond," +
                      "Georgia,Impact,Sans Serif,Serif,Tahoma,Trebuchet MS,Verdana",
        sizes:        // sizes in the font size popup
                      "1,2,3,4,5,6,7",
        styles:       // styles in the style popup
                      [["Paragraph", "<p>"], ["Header 1", "<h1>"], ["Header 2", "<h2>"],
                      ["Header 3", "<h3>"],  ["Header 4","<h4>"],  ["Header 5","<h5>"],
                      ["Header 6","<h6>"]],
        useCSS:       false, // use CSS to style HTML when possible (not supported in ie)
        docType:      // Document type contained within the editor
                      '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">',
        docCSSFile:   // CSS file used to style the document contained within the editor
                      "", 
        bodyStyle:    // style to assign to document body contained within the editor
                      "margin:4px; font:10pt Arial,Verdana; cursor:text"
    });
})
</script>