<div class="box">
    <div class="box-header">
        <h2><i class="icon-box"></i>角色列表</h2>
    </div>
    <div class="box-content">
    <p><a class="btn btn-success" href="<?php echo $this
    ->url('backend' , array('controller' => 'role' , 'action' => 'save'));
    ?>"><i class="icon-plus"></i>添加角色</a>
    <a class="btn btn-edit" href="javascript:;" _href="<?php echo $this->url('backend' , array('controller' => 'acl'
                            , 'action' => 'allow'))?>?role="><i class="icon-edit"></i>
                            绑定资源</a>
                        <a class="btn btn-delete" href="javascript:;" _href="<?php echo $this->url('backend' , array('controller' => 'role'
                            , 'action' => 'delete'));?>?name=" onClick="diyConfirm('删除' , $(this).attr('href'), this);return false;"><i class="icon-delete"></i>
                            删除</a></p>
    <div class="t_top">
    	<div class="t_right" style="margin-bottom:6px;">
        	 
        	</div>
    </div>
        <table class="table">
        <thead>
            <tr class="row">
            	<td>选择</td>
                <th>角色</th>
                <th>角色别名</th>
                <th>添加时间</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($this->list as $role):?>
                <tr class="row">
                	<td><input type="checkbox" name="select" value="<?php echo $role->Name;?>"/></td>
                    <td><?php echo $role->Name;?></td>
                    <td><?php echo $role->CnName;?></td>
                    <td><?php echo $role->AddTime;?></td>
                </tr>
            <?php endforeach;?>
        </tbody>
        </table>
        
    </div>
</div>